--Welcome to DataBase Administraror by ./HernaldoMeneses
-- objetivo -> aprender T-SQL (Transact-SQL)
-- Getting Started
-- T-SQL - Transact-SQL is Microsoft's implemntation 
-- of the Structured Query Language (SQL)