SELECT 
PCMETARCA.CODFILIAL AS CODIGOFILIAL,
pcsuperv.codgerente,
pcsuperv.codsupervisor,
PCMETARCA.CODUSUR AS CODIGORCA,
               
        PCMETARCA.DATA,
        
        NVL(PCMETARCA.VLVENDAPREV,0) AS VALOR,
        NVL(PCMETARCA.QTPEDPREV,0) AS QTPEDPREV,
        NVL(PCMETARCA.QTITENSPEDPREV,0) AS QTITENSPEDPREV,
        NVL(PCMETARCA.NUMCLIPOS,0) AS POSITIVACAO

FROM PCMETARCA, pcsuperv
WHERE 
--DATA BETWEEN TO_DATE('01/08/2023','DD/MM/YYYY') AND TO_DATE('31/08/2023','DD/MM/YYYY')
TO_CHAR(PCMETARCA.DATA , 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -6), 'YYYY')
 AND PCMETARCA.codusur = pcsuperv.cod_cadrca
  AND PCMETARCA.CODFILIAL = 2
ORDER BY DATA