SELECT BAN.CODBANCO AS CODIGOBANCO,
BAN.NUMBANCO AS NUMEROBANCO,
BAN.NOME AS BANCO,
BAN.AGENCIA,
BAN.CONTA,

FIL.CODIGO AS CODIGOFILIAL,
FIL.RAZAOSOCIAL AS FILIAL,
BAN.FLUXOCX
FROM PCBANCO BAN
LEFT JOIN PCFILIAL FIL ON FIL.CODIGO = BAN.CODFILIAL