SELECT ('F'||TRIM(TO_CHAR(PCFORNEC.CODFORNEC,'000000000'))) CODIGOPARCEIRO, 
PCFORNEC.FORNECEDOR NOMEPARCEIRO, 
'FORNECEDOR' AS TIPOPARCEIRO
FROM PCFORNEC

UNION

SELECT ('C'||TRIM(TO_CHAR(PCCLIENT.CODCLI,'000000000'))) CODIGOPARCEIRO, 
PCCLIENT.CLIENTE NOMEPARCEIRO, 
'CLIENTE' AS TIPOPARCEIRO
FROM PCCLIENT


UNION
SELECT ('R'||TRIM(TO_CHAR(PCUSUARI.CODUSUR,'000000000'))) CODIGOPARCEIRO, 
PCUSUARI.NOME NOMEPARCEIRO, 
'RCA' AS TIPOPARCEIRO
FROM PCUSUARI


UNION
SELECT '0' AS CODIGOPARCEIRO, 
'OUTROS' AS NOMEPARCEIRO, 
'OUTROS' AS TIPOPARCEIRO
FROM PCUSUARI