SELECT ENDE.CODENDERECO AS CODIGOENDERECO, 
TIPPAL.VOLUMEPAL AS VOLUME,
TIPPAL.ALTURA,
TIPPAL.LARGURA,
TIPPAL.COMPRIMENTO,
TIPPAL.PESO 
FROM PCENDERECO ENDE
INNER JOIN PCTIPOPAL TIPPAL ON TIPPAL.CODIGO = ENDE.TIPOPAL