SELECT
RATEIO.RECNUM AS NUMEROLANCAMENTO,
RATEIO.CODCONTA AS CODIGOCONTA,
RATEIO.CODIGOCENTROCUSTO AS CODIGOCENTROCUSTO,
PCLANC.CODFILIAL AS CODIGOFILIAL,
TO_CHAR(RATEIO.DTLANC,'DD/MM/YYYY') AS DATALANCAMENTO,
PCLANC.DTVENC AS DATAVENCIMENTO,
PCLANC.DTLANC AS DATATITULO,
PCLANC.DTPAGTO AS DATAPAGAMENTO,
PCLANC.NUMBANCO AS NUMEROBANCO,
CASE 
     WHEN PCLANC.TIPOPARCEIRO = 'F' THEN ('F'||TRIM(TO_CHAR(PCLANC.CODFORNEC,'000000000'))) 
     WHEN PCLANC.TIPOPARCEIRO = 'C' THEN ('C'||TRIM(TO_CHAR(PCLANC.CODFORNEC,'000000000')))
     WHEN PCLANC.TIPOPARCEIRO = 'R' THEN ('R'||TRIM(TO_CHAR(PCLANC.CODFORNEC,'000000000')))
     ELSE '0'
END AS CODIGOPARCEIRO,
RATEIO.PERCRATEIO AS PERCRATEIO,
RATEIO.VALOR AS VALORRATEIO
FROM PCRATEIOCENTROCUSTO RATEIO
LEFT JOIN PCLANC ON RATEIO.RECNUM = PCLANC.RECNUM