SELECT 
MOV.CODFILIAL AS CODIGOFILIAL,
MOV.CODPROD AS CODIGOPRODUTO,
MOV.CODENDERECO AS CODIGOENDERECO,
MOV.NUMPED AS NUMEROPEDIDO,
MOV.NUMOS AS NUMEROOS, 
MOV.NUMBONUS AS NUMEROBONUS,
MOV.NUMCAR AS NUMEROCARREGAMENTO,
MOV.NUMTRANSVENDA AS NUMEROTRANSVENDA,
MOV.CODMOTIVO AS CODIGOMOVITODEVOLUCAO,
MOV.CODFUNCEMBALADOR AS CODIGOEMBALADOR,
MOV.CODFUNCCOFERENTE AS CODIGOCONFERENTE,
MOV.CODFUNCOS AS CODIGOSEPARADOR,
MOV.DATA AS DATAGERACAOOS,
TRUNC(MOV.DTINICIOOS) AS DATAINICIOOS,
TRUNC(MOV.DTFIMOS) AS DATAFIMOS,
MOV.QT AS QUANTIDADE,
PRO.PESOBRUTO AS PESOBRUTO,
PRO.PESOLIQ AS PESOLIQUIDO,
PRO.VOLUME AS VOLUME
FROM PCMOVENDPEND MOV
LEFT JOIN PCENDERECO END ON END.CODENDERECO = MOV.CODENDERECO
LEFT JOIN PCPRODUT PRO ON PRO.CODPROD = MOV.CODPROD
WHERE MOV.DTINICIOOS IS NOT NULL
  AND MOV.DTFIMOS IS NOT NULL
  AND MOV.DTESTORNO IS NULL
   AND MOV.NUMOS IS NOT NULL
AND TO_CHAR(MOV.DATA, 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -24), 'YYYY')