




/* SQL UTILIZADO PELA ROTINA PCSIS322 RELATORIO(S) - 14 */ SELECT 
       PCSUPERV.CODSUPERVISOR,
       PCSUPERV.NOME,
       NVL(VENDAS.QT, 0) QT,
       NVL(VENDAS.PVENDA, 0) PVENDA,
       NVL(VENDAS.TOTPESO, 0) TOTPESO,
       NVL(VENDAS.Volume, 0) Volume,
       NVL(VENDAS.Litragem, 0) Litragem,
       NVL(VENDAS.TOTQTUNIT, 0) TOTQTUNIT,
       NVL(VENDAS.TOTQTUNITCX, 0) TOTQTUNITCX,
       NVL(VENDAS.QTCLIPOS, 0) QTCLIPOS,
       NVL(METAS.VLMETA, 0) VLMETA,
       NVL(METAS.QTMETA, 0) QTMETA,
       NVL(METAS.QTPESOMETA, 0) QTPESOMETA,
       NVL(METAS.MIXPREV, 0) MIXPREV,
       NVL(METAS.CLIPOSPREV, 0) CLIPOSPREV
  FROM PCSUPERV, PCPEDC, PCPEDI,
       (/* SQL UTILIZADO PELA ROTINA PCSIS322 RELATORIO(S) - 14 */ SELECT 
                PCPEDC.CODSUPERVISOR  CODSUPERVISOR,
               PCSUPERV.NOME SUPERV,
               COUNT(DISTINCT(PCPEDC.CODCLI)) QTCLIPOS,
               SUM(ROUND(NVL(PCPEDI.QT, 0) * (NVL(PCPEDI.PVENDA, 0) + NVL(PCPEDI.VLOUTRASDESP, 0) + NVL(PCPEDI.VLFRETE, 0)),2)) 
PVENDA,
    SUM(NVL(PCPEDI.QT,0) / DECODE(NVL(PCPRODUT.QTUNITCX,0),0,1,NVL(PCPRODUT.QTUNITCX,1))) AS QT,
               SUM(ROUND(NVL(PCPRODUT.PESOBRUTO, 0) * NVL(PCPEDI.QT, 0),2)) AS TOTPESO,
               SUM(ROUND(NVL(PCPRODUT.VOLUME, 0) * NVL(PCPEDI.QT, 0),2)) Volume,
       ROUND(SUM(NVL(PCPRODUT.LITRAGEM, 0)*NVL(PCPEDI.QT,0)) ,2) LITRAGEM,
       SUM(NVL(PCPEDI.QT,0) / DECODE(NVL(PCPRODUT.QTUNIT,0),0,1,NVL(PCPRODUT.QTUNIT,1))) TOTQTUNIT,
       SUM(NVL(PCPEDI.QT,0) / DECODE(NVL(PCPRODUT.QTUNITCX,0),0,1,NVL(PCPRODUT.QTUNITCX,1))) TOTQTUNITCX,
               COUNT(DISTINCT(PCPEDC.NUMPED)) AS QTPEDIDO,
               COUNT(DISTINCT(PCPEDI.CODPROD)) AS QTMIX,
               COUNT(PCPEDI.CODPROD) NUMITENS,
               MAX((/* SQL UTILIZADO PELA ROTINA PCSIS322 RELATORIO(S) - 14 */ SELECT COUNT(P.CODPROD)
                     FROM PCPRODUT P, PCDEPTO D
                    WHERE P.CODEPTO = D.CODEPTO
                      AND P.CODFORNEC = PCFORNEC.CODFORNEC
                    AND (((P.CODFILIAL IS NULL) OR (P.CODFILIAL = '99')) OR ( P.CODFILIAL IN ('2')))
                      AND NVL(P.OBS2, '  ') <> ('FL'))) AS QTMIXCAD
          FROM PCPEDI,
               PCPEDC,
               PCPRODUT,
               PCFORNEC,
               PCDEPTO,
               PCCLIENT,
               PCUSUARI,
               PCSUPERV,
               PCATIVI,
               PCPRACA
         WHERE PCPEDI.NUMPED = PCPEDC.NUMPED
AND PCPEDC.DATA BETWEEN :DATAI AND :DATAF
AND PCPEDC.CODFILIAL IN ('2')
AND PCPEDC.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
 AND NVL(PCPEDI.BONIFIC, 'N') =  'N' 

AND PCPRODUT.CODFORNEC IN(3091)
  AND (PCPRODUT.CODEPTO IN 
              ( SELECT CODIGON 
                FROM PCLIB 
                WHERE CODFUNC = :CODFUNC 
                AND CODTABELA = 2) ) 
           AND PCPEDC.CODCLI = PCCLIENT.CODCLI
           AND PCCLIENT.CODATV1 = PCATIVI.CODATIV(+)
           AND PCPEDC.DTCANCEL IS NULL
           AND PCPEDI.CODPROD = PCPRODUT.CODPROD
           AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO
           AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
           AND  PCPEDC.CODUSUR  = PCUSUARI.CODUSUR 
           AND  PCPEDC.CODSUPERVISOR  = PCSUPERV.CODSUPERVISOR 
           AND PCPEDC.CODPRACA = PCPRACA.CODPRACA
           AND PCPEDC.NUMPED >= (SELECT MIN(NUMPED) FROM PCPEDC)
           AND PCPEDI.CODPROD >= (SELECT MIN(CODPROD) FROM PCPEDI)
         GROUP BY 
 PCPEDC.CODSUPERVISOR  ,PCSUPERV.NOME) VENDAS,
       (/* SQL UTILIZADO PELA ROTINA PCSIS322 RELATORIO(S) - 14 */ SELECT PCUSUARI.CODSUPERVISOR CODIGO,
               SUM(NVL(PCMETA.VLVENDAPREV, 0)) VLMETA,
               SUM(NVL(PCMETA.QTVENDAPREV, 0)) QTMETA,
               SUM(NVL(PCMETA.QTPESOPREV, 0)) QTPESOMETA,
               SUM(NVL(PCMETA.MIXPREV, 0)) MIXPREV,
               SUM(NVL(PCMETA.CLIPOSPREV, 0)) CLIPOSPREV
          FROM PCMETA, PCUSUARI, PCFORNEC,  
PCPRODUT
         WHERE PCMETA.CODUSUR = PCUSUARI.CODUSUR
           AND PCMETA.TIPOMETA = 'P'
           AND PCPRODUT.CODPROD = PCMETA.CODIGO
           AND PCFORNEC.CODFORNEC = PCPRODUT.CODFORNEC 
                   AND PCMETA.TIPOMETA = 'P'
   AND PCMETA.DATA BETWEEN  TO_DATE('01/10/2023', 'DD/MM/YYYY') AND 
                            TO_DATE('30/10/2023', 'DD/MM/YYYY') 
      AND (SELECT 
               SUM(ROUND(NVL(PCPEDI.QT, 0) * (NVL(PCPEDI.PVENDA, 0) + NVL(PCPEDI.VLOUTRASDESP, 0) + NVL(PCPEDI.VLFRETE, 0)),2)) 
PVENDA
          FROM PCPEDI,
               PCPEDC,
               PCPRODUT,
               PCFORNEC,
               PCDEPTO,
               PCCLIENT,
               PCUSUARI,
               PCSUPERV,
               PCATIVI,
               PCPRACA
         WHERE PCPEDI.NUMPED = PCPEDC.NUMPED
AND PCPEDC.DATA BETWEEN :DATAI AND :DATAF
AND PCPEDC.CODFILIAL IN ('2')
AND PCPEDC.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
 AND NVL(PCPEDI.BONIFIC, 'N') =  'N' 

AND PCPRODUT.CODFORNEC IN(3091)
  AND (PCPRODUT.CODEPTO IN 
              ( SELECT CODIGON 
                FROM PCLIB 
                WHERE CODFUNC = :CODFUNC 
                AND CODTABELA = 2) ) 
           AND PCPEDC.CODCLI = PCCLIENT.CODCLI
           AND PCCLIENT.CODATV1 = PCATIVI.CODATIV(+)
           AND PCPEDC.DTCANCEL IS NULL
           AND PCPEDI.CODPROD = PCPRODUT.CODPROD
           AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO
           AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
           AND PCPEDC.CODUSUR = PCMETA.CODUSUR
           AND  PCPEDC.CODUSUR  = PCUSUARI.CODUSUR 
           AND  PCPEDC.CODSUPERVISOR  = PCSUPERV.CODSUPERVISOR 
           AND PCPEDC.CODPRACA = PCPRACA.CODPRACA ) > 0

           AND PCMETA.CODFILIAL IN ('2')
  AND PCPRODUT.CODFORNEC IN (3091)
 GROUP BY PCUSUARI.CODSUPERVISOR) METAS
 WHERE 1=1 
 AND PCPEDC.NUMPED = PCPEDI.NUMPED 
AND PCPEDC.DATA BETWEEN :DATAI AND :DATAF
AND PCPEDC.CODFILIAL IN ('2')
AND PCPEDC.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
 AND NVL(PCPEDI.BONIFIC, 'N') =  'N' 
 and PCSUPERV.CODSUPERVISOR = METAS.CODIGO(+)
 AND PCSUPERV.CODSUPERVISOR = VENDAS.CODSUPERVISOR(+)
 AND PCSUPERV.CODSUPERVISOR NOT IN ('9999')
AND NVL(VENDAS.PVENDA,0)+NVL(VENDAS.TOTPESO,0) + NVL(VENDAS.QT,0)>0
    AND PCPEDC.NUMPED >= (SELECT MIN(NUMPED) FROM PCPEDC)
    AND PCPEDI.CODPROD >= (SELECT MIN(CODPROD) FROM PCPEDI)
GROUP BY 
       PCSUPERV.CODSUPERVISOR,
       PCSUPERV.NOME,
       VENDAS.QT,
       VENDAS.PVENDA,
       VENDAS.TOTPESO,
       VENDAS.Volume,
       VENDAS.Litragem,
       VENDAS.TOTQTUNIT,
       VENDAS.TOTQTUNITCX,
       VENDAS.QTCLIPOS,
       METAS.VLMETA,
       METAS.QTMETA,
       METAS.QTPESOMETA,
       METAS.MIXPREV,
       METAS.CLIPOSPREV
ORDER BY PVENDA DESC
DATAI = '30/10/2023'
DATAF = '30/10/2023'
CODFUNC = 1261
----------------------------------
Timestamp: 17:23:30.933
SELECT PARAMFILIAL.OBTERCOMOVARCHAR2('CON_DIRWINTHOR', '99')
  FROM DUAL