SELECT 
'1-Faturamento Bruto' AS INDICADOR,
PCNFSAID.CODFILIAL AS CODIGOFILIAL,
PCNFSAID.DTSAIDA AS DATA,
PCNFSAID.VLTOTGER AS VALOR    
FROM PCNFSAID                                               
WHERE                    
PCNFSAID.CODFILIAL NOT IN ('99')    
AND (PCNFSAID.CODFISCAL NOT IN (522,622,722,532,632,732) )
AND (PCNFSAID.CONDVENDA NOT IN (4, 8, 10, 13, 20))        
AND (PCNFSAID.DTCANCEL IS NULL)
AND TO_CHAR(PCNFSAID.DTSAIDA, 'YYYY') >= TO_CHAR(SYSDATE, 'YYYY') - 10
AND PCNFSAID.VLTOTGER <> 0