SELECT 
'4-CMV Devolução' AS INDICADOR, 
DEVOL.CODFILIAL AS CODIGOFILIAL,
DEVOL.DTENT AS DATA,
/* A PARTIR DA VERSÃO 26
(DEVOL.VLCMVDEVOLBONIF + DEVOL.VLCMVDEVOL) AS VALOR 
*/
(DEVOL.VLCMVDEVOL) AS VALOR 
FROM VIEW_DEVOL_RESUMO_FATURAMENTO DEVOL 
WHERE DEVOL.CONDVENDA NOT IN (4, 8, 10, 13, 20, 98, 99)
AND TO_CHAR(DEVOL.DTENT, 'YYYY') >= TO_CHAR(SYSDATE, 'YYYY') - 10