SELECT 
U.CODUSUR AS CODIGORCA,
U.NOME AS RCA,
C.CODCLI AS CODIGOCLIENTE,
C.CLIENTE AS CLIENTE,
'RCA 1' AS TIPOVINCULO
FROM PCCLIENT C
LEFT JOIN PCUSUARI U ON U.CODUSUR = C.CODUSUR1
WHERE U.CODUSUR <> 0
AND C.CODCLI <> 0

UNION

SELECT 
U.CODUSUR AS CODIGORCA,
U.NOME AS RCA,
C.CODCLI AS CODIGOCLIENTE,
C.CLIENTE AS CLIENTE,
'RCA 2' AS TIPOVINCULO
FROM PCCLIENT C
LEFT JOIN PCUSUARI U ON U.CODUSUR = C.CODUSUR2
WHERE U.CODUSUR <> 0
AND C.CODCLI <> 0
UNION

SELECT 
U.CODUSUR AS CODIGORCA,
U.NOME AS RCA,
C.CODCLI AS CODIGOCLIENTE,
C.CLIENTE AS CLIENTE,
'RCA 3' AS TIPOVINCULO
FROM PCCLIENT C
LEFT JOIN PCUSUARI U ON U.CODUSUR = C.CODUSUR3
WHERE U.CODUSUR <> 0
AND C.CODCLI <> 0
UNION


SELECT 
U.CODUSUR AS CODIGORCA,
U.NOME AS RCA,
USUCLI.CODCLI AS CODIGOCLIENTE,
C.CLIENTE,
'MÚLTIPLO' AS TIPOVINCULO
FROM PCUSUARI U
LEFT JOIN  PCUSURCLI USUCLI ON USUCLI.CODUSUR = U.CODUSUR
LEFT JOIN PCCLIENT C ON C.CODCLI = USUCLI.CODCLI
WHERE U.CODUSUR <> 0
AND C.CODCLI <> 0