SELECT
	PCHISTEST.CODPROD AS CODIGOPRODUTO, 
	PCHISTEST.CODFILIAL AS CODIGOFILIAL,
	PCMOVAVARIA.CODOPER AS CODIGOOPERACAO,
	PCMOVAVARIA.CODDEVOL AS CODIGOMOTIVODEVOLUCAO,
	PCHISTEST.DATA AS DATA,
	PCHISTEST.CUSTOULTENT AS CUSTOULTIMAENTRADA,
	PCHISTEST.CUSTOREAL AS CUSTOREALUNITARIO,
	PCHISTEST.CUSTOFIN AS CUSTOFINANCEIROUNITARIO,
	PCHISTEST.CUSTOCONT AS CUSTOCONTABILUNITARIO,
	PCHISTEST.CUSTOREP AS CUSTOREPOSICAOUNITARIO,
	PCHISTEST.QTESTGER AS QUANTIDADEGERENCIAL,
	PCHISTEST.QTBLOQUEADA AS QUANTIDADEBLOQUEADO,
	PCHISTEST.QTRESERV AS QUANTIDADERESERVADO,
	PCHISTEST.QTPENDENTE AS QUANTIDADEPENDENTE,
	PCMOVAVARIA.QT AS QUANTIDADEAVARIA,
	PCPRODUT.PESOBRUTO AS PESOBRUTO,
	PCPRODUT.PESOLIQ AS PESOLIQUIDO,
	PCPRODUT.VOLUME AS VOLUME,
	PCPRODUT.QTUNIT AS QUANTIDADEUNITARIA,
	PCPRODUT.QTUNITCX AS QUANTIDADEUNITARIACAIXA,
	1 AS GIRODIA,
	CAST( NVL(PCPRODUT.TEMREPOS, 0) AS NUMERIC(8,0))  AS TEMPOREPOSICAO,
	CAST( NVL(PCFORNEC.PRAZOENTREGA, 0) AS NUMERIC(8,0)) AS PRAZOENTREGA,
	CAST( NVL(PCTABPR.PVENDA1, 0) AS NUMERIC(18,6)) AS VALORUNITARIOVENDA
	
FROM PCHISTEST, PCPRODUT, PCFORNEC, PCMOVAVARIA, PCEST, PCTABPR

 WHERE PCHISTEST.CODPROD = PCPRODUT.CODPROD
 
   AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
   
   AND PCMOVAVARIA.CODFILIAL = PCHISTEST.CODFILIAL 
   AND PCMOVAVARIA.DATA = PCHISTEST.DATA 
   AND PCMOVAVARIA.CODPROD = PCPRODUT.CODPROD
   
   AND PCPRODUT.CODPROD = PCEST.CODPROD
   AND PCEST.CODFILIAL = PCMOVAVARIA.CODFILIAL
   
   AND PCPRODUT.CODPROD = PCTABPR.CODPROD

 AND PCHISTEST.CODFILIAL NOT IN ('99')
 AND PCTABPR.NUMREGIAO IN (1)
 AND PCHISTEST.DATA >= ADD_MONTHS(SYSDATE, -2)