SELECT  EST.CODENDERECO AS CODIGOENDERECO,
EST.CODPROD AS CODIGOPRODUTO ,
ENDE.CODFILIAL AS CODIGOFILIAL,
EST.QT AS QUANTIDADE,
EST.QTBLOQUEADA AS QUANTIDADEBLOQUEADA,
EST.QTRESERV AS QUANTIDADERESERVADA,
EST.QTPENDSAIDA AS QUANTIDADEPENDETESAIDA,
EST.QTPENDENTRADA AS QUANTIDADEPENDENTEENTRADA,
PRO.VOLUME AS VOLUMEUNITARIO,
EST.DTVAL AS DATAVALIDADE
FROM PCESTENDERECO EST
INNER JOIN PCENDERECO ENDE ON ENDE.CODENDERECO = EST.CODENDERECO
INNER JOIN PCPRODUT PRO ON PRO.CODPROD = EST.CODPROD
WHERE TO_CHAR(EST.DTVAL , 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -36), 'YYYY')