SELECT 
PCHISTEST.CODPROD AS CODIGOPRODUTO, 
PCHISTEST.CODFILIAL AS CODIGOFILIAL,
PCFornec.codfornec,
PCHISTEST.DATA AS DATA,
PCHISTEST.CUSTOULTENT AS CUSTOULTIMAENTRADA,
PCHISTEST.CUSTOREAL AS CUSTOREALUNITARIO,
PCHISTEST.CUSTOFIN AS CUSTOFINANCEIROUNITARIO,
PCHISTEST.CUSTOCONT AS CUSTOCONTABILUNITARIO,
PCHISTEST.CUSTOREP AS CUSTOREPOSICAOUNITARIO,
PCHISTEST.QTESTGER AS QUANTIDADEGERENCIAL,
PCHISTEST.QTBLOQUEADA AS QUANTIDADEBLOQUEADO,
PCHISTEST.QTRESERV AS QUANTIDADERESERVADO,
PCHISTEST.QTPENDENTE AS QUANTIDADEPENDENTE,
PCHISTEST.QTINDENIZ AS QUANTIDADEAVARIA,
(PKG_ESTOQUE.ESTOQUE_DISPONIVEL(PCEST.CODPROD, PCEST.CODFILIAL, 'V')) QTDISP,

--QuantidadeBloqueioVenda (numeric(18,6), nulo)
--QuantidadePedida (numeric(18,6), nulo)

--ValorVendaUnitario (numeric(18,6), nulo)
PCHISTEST.VLVENDA AS VALORVENDAUNITARIO,

PCPRODUT.PESOBRUTO AS PESOBRUTO,
PCPRODUT.PESOLIQ AS PESOLIQUIDO,
PCPRODUT.VOLUME AS VOLUME,
PCPRODUT.QTUNIT AS QUANTIDADEUNITARIA,
PCPRODUT.QTUNITCX AS QUANTIDADEUNITARIACAIXA,


CAST( NVL(PCFORNEC.PRAZOENTREGA, 0) AS NUMERIC(8,0)) AS PRAZOENTREGA,
CAST( NVL(PCPRODUT.TEMREPOS, 0) AS NUMERIC(8,0))  AS TEMPOREPOSICAO,

PCEST.QTGIRODIA  AS GIRODIA


FROM PCHISTEST, PCPRODUT, PCFORNEC, PCEST
 WHERE  PCHISTEST.CODPROD = PCPRODUT.CODPROD
AND PCHISTEST.CODPROD = PCEST.codprod
and pcest.codfilial = 2
   AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
 --AND PCHISTEST.CODFILIAL NOT IN ('99')
 AND PCHISTEST.CODFILIAL IN ('2')
 ANd  PCPRODUT.OBS2 not in ('FL')
AND TO_CHAR(PCHISTEST.DATA, 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -24), 'YYYY')