SELECT 
CORI.CODFUNC AS  CODIGOFUNCIONARIO,
CORI.CODFILIAL AS CODIGOFILIAL,
CORI.CODCLI AS CODIGOCLIENTE, 
CORI.CODPROD AS CODIGOPRODUTO,
NFS.CODCOB AS CODIGOCOBRANCA,
NFS.CODPLPAG AS CODIGOPLANOPAGAMENTO,
NFS.NUMPED AS NUMEROPEDIDO,
NFS.NUMTRANSVENDA AS NUMEROTRANSACAOVENDA,
CORI.QTSEPARADA AS QUANTIDADESEPARADA,
CORI.QTCORTADA AS QUANTIDADECORTADA,
TRUNC(CORI.DATA) AS DATACORTE,
NFS.DTSAIDA AS DATAVENDA,
CORI.CODUSUR AS CODIGORCA,
CORI.MOTIVO AS MOTIVOCORTE,
CORI.PVENDA AS PRECOVENDA
FROM PCCORTEI CORI
LEFT JOIN PCNFSAID NFS ON NFS.NUMPED = CORI.NUMPED
WHERE TO_CHAR(CORI.DATA  , 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -36), 'YYYY')