SELECT DATA, 
CASE WHEN NVL(DIAUTIL, 'S') = 'S' THEN 1 ELSE 0 END AS DIAUTIL,
CASE WHEN NVL(DIAUTIL, 'S') = 'N' THEN 1 ELSE 0 END AS DIANAOUTIL,
CASE WHEN (DATA < SYSDATE AND NVL(DIAUTIL, 'S') = 'S') THEN 1 ELSE 0 END AS DIASTRANSCORRIDOS
FROM PCDATAS