SELECT TABLE_NAME,
        COLUMN_NAME, 
       DATA_TYPE, 
       DATA_LENGTH, 
       DATA_PRECISION 
  FROM ALL_TAB_COLUMNS 
 WHERE UPPER(TABLE_NAME)  like 'PCFORNEC'
 AND UPPER(COLUMN_NAME)   like '%COMPR%';