SELECT
REC.NUMTRANSVENDA AS NUMEROTRANSACAOVENDA,
REC.PREST AS PRESTACAO, 
REC.DUPLIC AS NUMERONOTA, 
CASE    WHEN REC.DTPAG IS NULL AND REC.DTBAIXA IS NULL   THEN 'ABERTO'
        ELSE 'PAGO' END AS SITUACAO,
CASE WHEN REC.DTPAG IS NULL AND REC.DTVENC < TRUNC(SYSDATE) THEN 'INADIMPLENTE' ELSE 'ADIMPLENTE' END AS INADIMPLENCIA,
CASE WHEN (REC.DTPAG IS NOT NULL AND REC.DTPAG > REC.DTVENC) OR  
          (REC.DTPAG IS NULL AND REC.DTVENC < TRUNC(SYSDATE)) THEN 'ATRASO' 
     ELSE 'NO PRAZO' END AS ATRASO
FROM PCPREST REC
  WHERE TO_CHAR(REC.DTEMISSAO, 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -6), 'YYYY')