SELECT CON.CODCONTA AS CODIGOCONTA,
TO_CHAR(CON.CODCONTA||' - '||CON.CONTA) AS CONTA,
GRU.CODGRUPO AS CODIGOGRUPO,
TO_CHAR(GRU.CODGRUPO||' - '||GRU.GRUPO) AS GRUPOCONTA 
FROM PCCONTA CON
INNER JOIN PCGRUPO GRU ON GRU.CODGRUPO = CON.GRUPOCONTA