----------------------------------
Timestamp: 08:21:45.860
SELECT PCCONSUM.PRECOPOREMBALAGEM FROM PCCONSUM
----------------------------------
Timestamp: 08:21:45.874
SELECT PCFILIAL.AUTOSERVICO 
FROM PCFILIAL 
 WHERE PCFILIAL.CODIGO IN('2')
ORDER BY PCFILIAL.CODIGO
----------------------------------
Timestamp: 08:21:45.959
SELECT SUM((NVL(PCEST.QTESTGER, 0) - NVL(PCEST.QTRESERV, 0) - 
           NVL(PCEST.QTINDENIZ, 0)) * NVL(PCEST.CUSTOFIN, 0)) VLESTOQUE, 
       SUM((NVL(PCEST.QTESTGER, 0) - NVL(PCEST.QTRESERV, 0) - 
           NVL(PCEST.QTINDENIZ, 0)) * NVL(PCEST.CUSTOREAL, 0)) VLESTOQUEREAL, 
       SUM((NVL(PCEST.QTESTGER, 0) - NVL(PCEST.QTRESERV, 0) - 
           NVL(PCEST.QTINDENIZ, 0)) * (CASE 
             WHEN ((SELECT PCCONSUM.PRECOPOREMBALAGEM 
                      FROM PCCONSUM) = 'S') AND 
                  (PCFILIAL.AUTOSERVICO = 'S') THEN 
              (SELECT NVL(PCEMBALAGEM.PVENDA, 0) 
                 FROM PCEMBALAGEM 
                WHERE PCEMBALAGEM.CODFILIAL = PCEST.CODFILIAL 
                  AND (PCEMBALAGEM.CODPROD = PCEST.CODPROD) 
                  AND PCEMBALAGEM.QTUNIT = 1 
                  AND ROWNUM = 1) 
             ELSE 
              (SELECT NVL(PCTABPR.PVENDA, 0) 
                 FROM PCTABPR 
                WHERE PCTABPR.CODPROD = PCEST.CODPROD 
                  AND PCTABPR.NUMREGIAO = :NUMREGIAO) 
           END)) VLVENDA, 
       SUM((NVL(PCEST.QTGIRODIA, 0) * 
           (NVL(PCFORNEC.PRAZOENTREGA, 0) + NVL(PCPRODUT.TEMREPOS, 0))) * 
           NVL(PCEST.CUSTOFIN, 0)) VLESTIDEAL 
  FROM PCPRODUT, 
       PCEST, 
       PCFORNEC, 
       PCDEPTO, 
       PCSECAO, 
       PCPRODFILIAL PF, 
       PCFILIAL 
 WHERE PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC 
   AND PCEST.CODFILIAL = PCFILIAL.CODIGO 
   AND PCPRODUT.CODPROD = PCEST.CODPROD 
   AND PCEST.CODPROD = PF.CODPROD(+) 
   AND PCEST.CODFILIAL = PF.CODFILIAL(+) 
   AND PCDEPTO.TIPOMERC NOT IN ('IM', 'CI') 
    AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO(+)
   AND PCPRODUT.CODSEC = PCSECAO.CODSEC(+)
   AND ((NVL(PCEST.QTESTGER,0)-NVL(PCEST.QTRESERV,0)-Nvl(PCEST.QTINDENIZ,0)) > 0)
   AND PCEST.CODFILIAL IN('2')
NUMREGIAO = '1'
----------------------------------
Timestamp: 08:21:46.144
SELECT SUM ((NVL(PCEST.QTGIRODIA,0)* 
       (NVL(PCFORNEC.PRAZOENTREGA,0) + NVL(PCPRODUT.TEMREPOS,0)) )
       * NVL(PCEST.CUSTOFIN,0)) VLESTIDEAL
  FROM PCPRODUT, PCEST, PCFORNEC, PCDEPTO, PCSECAO, PCPRODFILIAL PF 
WHERE PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
AND PCPRODUT.CODPROD = PCEST.CODPROD
 AND PCEST.CODPROD = PF.CODPROD(+)                                  
 AND PCEST.CODFILIAL = PF.CODFILIAL(+)                              
AND PCDEPTO.TIPOMERC NOT IN ('IM', 'CI') 
AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO(+)
AND PCPRODUT.CODSEC = PCSECAO.CODSEC(+)
 AND PCEST.CODFILIAL IN('2')
----------------------------------
Timestamp: 08:21:46.225
--Totalizador
SELECT
SUM ((((Nvl(PCEST.QTESTGER,0)-Nvl(PCEST.QTRESERV,0)-Nvl(PCEST.QTINDENIZ,0))-(NVL(QTGIRODIA,0)*
    (((Nvl(PCFORNEC.PRAZOENTREGA,0))+Nvl(PCPRODUT.TEMREPOS,0))*(:QTVEZES))))*
       Nvl(PCEST.CUSTOFIN,0))) VLEXCESSO,
 SUM((NVL(PCEST.QTESTGER,0)- NVL(PCEST.QTRESERV,0)-Nvl(PCEST.QTINDENIZ,0)-(NVL(QTGIRODIA,0)*   
 (((Nvl(PCFORNEC.PRAZOENTREGA,0))+Nvl(PCPRODUT.TEMREPOS,0))*(:QTVEZES)))) *                    
(CASE WHEN ((SELECT PRECOPOREMBALAGEM                  
             FROM PCCONSUM) = 'S'                    
           AND NVL(PCFILIAL.AUTOSERVICO,'N') = 'S')
     THEN                                              
 (SELECT NVL(PCEMBALAGEM.PVENDA,0)                     
     FROM PCEMBALAGEM                                  
 	 WHERE PCEMBALAGEM.CODFILIAL = PCEST.CODFILIAL      
      AND (PCEMBALAGEM.CODPROD = PCEST.CODPROD)        
      AND PCEMBALAGEM.QTUNIT = 1 AND ROWNUM = 1        
 )                                                     
 ELSE                                                  
 (SELECT NVL(PCTABPR.PVENDA,0)                         
     FROM PCTABPR                                      
 	 WHERE PCTABPR.CODPROD = PCEST.CODPROD              
      AND (PCTABPR.NUMREGIAO = :NUMREGIAO)             
 ) END)) VLVENDA                                       
FROM PCPRODUT, PCMARCA, PCEST, PCFORNEC, PCDEPTO, PCSECAO, PCPRODFILIAL PF, PCFILIAL 
WHERE PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
AND PCPRODUT.CODPROD = PCEST.CODPROD       
AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO(+)  
AND PCPRODUT.CODSEC = PCSECAO.CODSEC(+)    
AND PCPRODUT.CODMARCA = PCMARCA.CODMARCA(+)
AND PCEST.CODPROD = PF.CODPROD(+)          
AND PCEST.CODFILIAL = PF.CODFILIAL(+)      
AND PCEST.CODFILIAL = PCFILIAL.CODIGO      
AND PCDEPTO.TIPOMERC NOT IN ('IM', 'CI') 
AND  ((NVL(PCEST.QTESTGER,0) - NVL(PCEST.QTRESERV,0)-Nvl(PCEST.QTINDENIZ,0)) > 0)
AND  ((NVL(PCEST.QTESTGER,0)-Nvl(PCEST.QTRESERV,0)-Nvl(PCEST.QTINDENIZ,0) )>
     (((NVL(QTGIRODIA,0)*(Nvl(PCFORNEC.PRAZOENTREGA,0)
        +NVL(PCPRODUT.TEMREPOS,0) ) )*(:QTVEZES))))
 AND PCEST.CODFILIAL IN('2')
QTVEZES = 1
NUMREGIAO = '1'
----------------------------------
Timestamp: 08:21:46.386
--Select grid 
SELECT PCEST.CODFILIAL, 
       PCPRODUT.CODPROD, 
       PCPRODUT.DESCRICAO, 
       NVL(DECODE(PF.FORALINHA, 
                  'S', 
                  'FL', 
                  PF.FORALINHA), 
           NVL(PCPRODUT.OBS2, '')) OBS2, 
       PCPRODUT.DTCADASTRO, 
       PCPRODUT.NUMORIGINAL, 
       PCPRODUT.CODSEC,
       PCPRODUT.EMBALAGEM, 
       PCEST.CUSTOFIN, 
       PCEST.QTESTGER, 
       NVL(PCEST.QTRESERV, 0) QTRESERV,
       NVL(PCEST.QTINDENIZ, 0) QTINDENIZ,
       PCFORNEC.PRAZOENTREGA, 
       PCEST.QTVENDMES1, 
       PCEST.QTVENDMES2,
       PCEST.QTVENDMES3, 
       PCPRODUT.CODEPTO, 
       PCPRODUT.CODFORNEC, 
       PCPRODUT.CODMARCA, 
       PCMARCA.MARCA,
       ((NVL(PCEST.QTGIRODIA, 0) * (NVL(PCFORNEC.PRAZOENTREGA, 0) + 
         NVL(PCPRODUT.TEMREPOS, 0))) * (:QTVEZES)) ESTIDEAL, 
       ((NVL(PCEST.QTESTGER, 0) - NVL(PCEST.QTRESERV, 0) - NVL(PCEST.QTINDENIZ, 0)) - 
         ((NVL(PCEST.QTGIRODIA, 0) * (NVL(PCFORNEC.PRAZOENTREGA, 0) + NVL(PCPRODUT.TEMREPOS, 0))) * 
         (:QTVEZES))) EXCESSO, 
       (((NVL(PCEST.QTESTGER, 0) - NVL(PCEST.QTRESERV, 0) - NVL(PCEST.QTINDENIZ, 0)) - 
         (NVL(QTGIRODIA, 0) * (((NVL(PCFORNEC.PRAZOENTREGA, 0)) + NVL(PCPRODUT.TEMREPOS, 0)) * 
         (:QTVEZES)))) * NVL(PCEST.CUSTOFIN, 0)) VLEXCESSO, 
       PCPRODUT.CLASSEVENDA,
       PCDEPTO.DESCRICAO, 
       PCFORNEC.FORNECEDOR, 
       PCEST.DTULTENT, 
       PCPRODUT.OBS, 
       PCPRODUT.CLASSE,
       PCEST.QTVENDMES, 
       PCEST.QTESTANT, 
       PCEST.VLVENDMESREAL,
       PCEST.VLCUSTOMESFIN, 
       PCPRODUT.TEMREPOS,
       ROUND((DECODE(NVL(PCEST.QTGIRODIA, 0), 
                     0, 
                     (PCEST.QTESTGER - PCEST.QTRESERV - NVL(PCEST.QTINDENIZ,0)),
                     ((PCEST.QTESTGER - PCEST.QTRESERV - NVL(PCEST.QTINDENIZ,0)) / 
                     PCEST.QTGIRODIA))), 
             6) ESTDIAS, 
       NVL(PCEST.QTGIRODIA,0) GIRODIA, 
       PCEST.QTPEDIDA, 
       PCEST.CUSTOULTENT, 
       PCEST.QTULTENT, 
       PCEST.QTVENDAPERDIDA, 
       PCPRODUT.CODFAB,
       (CASE 
         WHEN ((SELECT PRECOPOREMBALAGEM 
                  FROM PCCONSUM) = 'S' 
                   AND NVL(PCFILIAL.AUTOSERVICO,'N') = 'S') THEN
           (SELECT NVL(PCEMBALAGEM.PVENDA,0)
              FROM PCEMBALAGEM
 	           WHERE PCEMBALAGEM.CODFILIAL = PCEST.CODFILIAL
               AND (PCEMBALAGEM.CODPROD = PCEST.CODPROD)
               AND PCEMBALAGEM.QTUNIT = 1 AND ROWNUM = 1) 
         ELSE 
           (SELECT NVL(PCTABPR.PVENDA,0)
              FROM PCTABPR
 	           WHERE PCTABPR.CODPROD = PCEST.CODPROD
               AND (PCTABPR.NUMREGIAO = :NUMREGIAO)) 
       END) PVENDA
  FROM PCPRODUT, 
       PCEST, 
       PCFORNEC, 
       PCDEPTO, 
       PCSECAO, 
       PCMARCA, 
       PCPRODFILIAL PF, 
       PCFILIAL 
 WHERE PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
   AND PCPRODUT.CODPROD = PCEST.CODPROD
   AND PCPRODUT.CODMARCA = PCMARCA.CODMARCA(+)
   AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO(+)
   AND PCEST.CODFILIAL = PCFILIAL.CODIGO
   AND PCPRODUT.CODSEC = PCSECAO.CODSEC(+)
   AND PCEST.CODPROD = PF.CODPROD(+) 
   AND PCEST.CODFILIAL = PF.CODFILIAL(+) 
   AND PCDEPTO.TIPOMERC NOT IN ('IM', 'CI') 
   AND ((NVL(PCEST.QTESTGER, 0) - NVL(PCEST.QTRESERV, 0) - NVL(PCEST.QTINDENIZ, 0)) > 0)
   AND ((NVL(PCEST.QTESTGER, 0) - NVL(PCEST.QTRESERV, 0) - NVL(PCEST.QTINDENIZ, 0) ) > 
       (((NVL(QTGIRODIA, 0) * (NVL(PCFORNEC.PRAZOENTREGA, 0) + NVL(PCPRODUT.TEMREPOS, 0))) * 
       (:QTVEZES)))) 
   AND PCEST.CODFILIAL IN('2')
QTVEZES = 1
NUMREGIAO = '1'
----------------------------------
Timestamp: 08:21:46.817
SELECT TXVENDA, MARGEMPREV, MARGEMMIN, EMPRESA,
USACATEGORIA, TIPOVALORGIRODIA, NUMREGIAOPADRAO 
FROM PCCONSUM