 
SELECT
       PCPRODUT.CODFORNEC,  
       PCFORNEC.FORNECEDOR, 
       PCPRODUT.CODPROD, 
       PCPRODUT.DESCRICAO, 


       ROUND((DECODE(NVL(PCEST.QTGIRODIA, 0), 
                     0, 
                     (PCEST.QTESTGER - PCEST.QTRESERV - NVL(PCEST.QTINDENIZ,0)),
                     ((PCEST.QTESTGER - PCEST.QTRESERV - NVL(PCEST.QTINDENIZ,0)) / 
                     PCEST.QTGIRODIA))), 
             6) ESTDIAS, 
       NVL(PCEST.QTGIRODIA,0) GIRODIA 

  FROM PCPRODUT, 
       PCEST, 
       PCFORNEC, 
       PCDEPTO, 
       PCSECAO, 
       PCMARCA, 
       PCPRODFILIAL PF, 
       PCFILIAL 
 WHERE PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
   AND PCPRODUT.CODPROD = PCEST.CODPROD
   AND PCPRODUT.CODMARCA = PCMARCA.CODMARCA(+)
   AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO(+)
   AND PCEST.CODFILIAL = PCFILIAL.CODIGO
   AND PCPRODUT.CODSEC = PCSECAO.CODSEC(+)
   AND PCEST.CODPROD = PF.CODPROD(+) 
   AND PCEST.CODFILIAL = PF.CODFILIAL(+) 
   AND PCDEPTO.TIPOMERC NOT IN ('IM', 'CI') 
   AND ((NVL(PCEST.QTESTGER, 0) - NVL(PCEST.QTRESERV, 0) - NVL(PCEST.QTINDENIZ, 0)) > 0)
   AND ((NVL(PCEST.QTESTGER, 0) - NVL(PCEST.QTRESERV, 0) - NVL(PCEST.QTINDENIZ, 0) ) > 
       (((NVL(QTGIRODIA, 0) * (NVL(PCFORNEC.PRAZOENTREGA, 0) + NVL(PCPRODUT.TEMREPOS, 0))) * 
       (1)))) 
   AND PCEST.CODFILIAL IN('2')
