SELECT PED.NUMPED AS NUMEROPEDIDO,
PED.CODCLI AS CODIGOCLIENTE,
PED.CODFILIAL AS CODIGOFILIAL,
PED.CODUSUR AS CODIGORCA,
PED.DATA AS DATAVENDA,
DEV.DTESTORNO AS DATAESTORNO,
DEV.VLDEVOLUCAO AS VALORDEVOLUCAO
FROM PCESTCOM DEV
INNER JOIN PCPEDC PED ON PED.NUMTRANSVENDA = DEV.NUMTRANSVENDA
WHERE TO_CHAR(PED.DATA  , 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -36), 'YYYY')