SELECT 
MOV.NUMOS AS NUMEROOS, 
MOV.DATA AS DATAGERACAOOS,
CASE WHEN MOV.NUMPED = 0 THEN NULL ELSE MOV.NUMPED END AS NUMEROPEDIDO,
CASE WHEN MOV.NUMCAR = 0 THEN NULL ELSE MOV.NUMCAR END AS NUMEROCARREGAMENTO,
MIN(MOV.DTINICIOOS) AS DATAINICIOOS, 
MAX(MOV.DTFIMOS) AS DATAFIMOS, 
MAX(MOV.DTFIMSEPARACAO) AS DATAFIMSEPARACAO,
MIN(MOV.DTINICIOCONFERENCIA) AS DATAINICIOCONFERENCIA, 
MIN(MOV.DTFIMCONFERENCIA) AS DATAFIMCONFERENCIA 
FROM PCMOVENDPEND MOV
INNER JOIN PCENDERECO END ON END.CODENDERECO = MOV.CODENDERECO
WHERE TO_CHAR(MOV.DATA, 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -24), 'YYYY')
GROUP BY MOV.NUMOS, MOV.DATA, MOV.POSICAO, MOV.DTESTORNO, MOV.CODOPER, MOV.NUMPED, MOV.NUMTRANSVENDA, MOV.NUMCAR