SELECT 
INV.NUMINVENT AS NUMEROINVENTARIO,
MIN(INV.DATA) AS DATAGERACAO,
MAX(INV.DTATUALIZACAO) AS DATAATUALIZACAO,
MIN(IVEI.DTCONTINI) AS DATAINICIOCONTAGEM,
MAX(IVEI.DTCONTFIM) AS DATAFIMCONTAGEM 
FROM  PCINVENTENDERECO INV
INNER JOIN PCINVENTENDERECOI IVEI ON IVEI.NUMINVENT = INV.NUMINVENT  AND IVEI.CODENDERECO = INV.CODENDERECO
WHERE TO_CHAR(INV.DATA, 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -24), 'YYYY')
GROUP BY INV.NUMINVENT