/* SQL UTILIZADO PELA ROTINA PCSIS322 PARA TODOS OS RELATÓRIOS */
SELECT
to_date('05/11/2023','dd/mm/yyyy') as DATAINIT,
to_date('02/12/2023','dd/mm/yyyy') as DATAEND,
 PCPRODUT.CODCATEGORIA,
     PCPRODUT.CODSUBCATEGORIA,
    PCPRODUT.CODPROD,
    PCPRODUT.Descricao,
   

       SUM(PCPEDI.QT) AS QT,
       SUM(ROUND(NVL(PCPEDI.QT,0)*(NVL(PCPEDI.PVENDA, 0) + NVL(PCPEDI.VLOUTRASDESP, 0) + NVL(PCPEDI.VLFRETE, 0)),2)) AS PVENDA,
       SUM(ROUND(NVL(PCPRODUT.PESOBRUTO,0)*NVL(PCPEDI.QT,0),2)) AS TOTPESO
       /*
       COUNT(DISTINCT(PCPEDC.CODCLI)) AS QTCLIPOS,
       SUM(ROUND(NVL(PCPEDI.QT,0)*NVL(PCPEDI.VLCUSTOFIN,0),2)) AS VLCUSTOFIN,
  ((SUM(ROUND(NVL(PCPEDI.QT,0)*(NVL(PCPEDI.PVENDA, 0) + NVL(PCPEDI.VLOUTRASDESP, 0) + NVL(PCPEDI.VLFRETE, 0)),2))
  -  SUM(ROUND(NVL(PCPEDI.QT,0)*NVL(PCPEDI.VLCUSTOFIN,0),2))) /  decode(SUM(ROUND(NVL(PCPEDI.QT,0)*NVL(PCPEDI.PVENDA,0),2)),0,1,
SUM(ROUND(NVL(PCPEDI.QT,0)*NVL(PCPEDI.PVENDA,0),2))) * 100 ) as clPERLUC
*/
FROM     
PCPEDI,  
PCPEDC,  
PCPRODUT,
PCCLIENT,
PCFORNEC,
PCLIB   
WHERE 1=1 
--AND PCPEDC.DATA BETWEEN :DATAI AND :DATAF
--AND PCPEDI.DATA BETWEEN :DATAI AND :DATAF
AND PCPEDC.DATA BETWEEN to_date('05/11/2023','dd/mm/yyyy') AND to_date('02/12/2023','dd/mm/yyyy')
AND PCPEDI.DATA BETWEEN to_date('05/11/2023','dd/mm/yyyy') AND to_date('02/12/2023','dd/mm/yyyy')
AND PCPEDC.CODFILIAL IN ('2')
AND PCPEDC.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
and PCPEDC.NUMPED    = PCPEDI.NUMPED
AND   PCPEDI.CODPROD   = PCPRODUT.CODPROD
AND   PCPEDC.CODCLI    = PCCLIENT.CODCLI
AND   PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
AND   PCPRODUT.CODEPTO = PCLIB.CODIGON
AND   PCLIB.CODTABELA  = 2
--AND   PCLIB.CODFUNC    = :CODFUNC
 AND NVL(PCPEDI.BONIFIC, 'N') =  'N' 
  AND PCPRODUT.CODSEC IN(10230)

AND PCPRODUT.CODCATEGORIA IN (101126,101125)
--AND PCPRODUT.CODSUBCATEGORIA IN (561,573,581,575,580,570,562,563,572,123867,123866,123868)
AND PCPRODUT.CODSUBCATEGORIA IN (561,573,581,575,580,570,562,563,572)
AND   PCPEDC.DTCANCEL IS NULL
AND PCPEDC.NUMPED >= (SELECT MIN(NUMPED) FROM PCPEDC)
AND PCPEDI.CODPROD >= (SELECT MIN(CODPROD) FROM PCPEDI)
--DATAI = '05/11/2023'
--DATAF = '02/12/2023'
--CODFUNC = 1261




Group by
    PCPRODUT.CODCATEGORIA,
    PCPRODUT.CODSUBCATEGORIA,
        PCPRODUT.CODPROD,
    PCPRODUT.Descricao

    order by
 PCPRODUT.CODCATEGORIA,
     PCPRODUT.CODSUBCATEGORIA,
    PCPRODUT.CODPROD
