SELECT CABECALHO.NUMNOTA
     --, CABECALHO.NUMTRANSENT
     --, CABECALHO.NUMTRANSORIGEM
     , CABECALHO.CODFORNEC
     , PCFORNEC.FORNECEDOR
     , CABECALHO.CODFILIAL
     , NVL(CABECALHO.VLTOTAL, 0) VLTOTAL
     , CABECALHO.SERIE
     , CABECALHO.ESPECIE
     , NVL(CABECALHO.RESTRINGIRCREDICMSTV10,'N') RESTRINGIRCREDICMSTV10
     , NVL(CABECALHO.GERANFVENDA,'N') GERANFVENDA
     , CABECALHO.DTENT
     , CABECALHO.CODFISCAL
     , CABECALHO.CODCONT
     , CABECALHO.DTEMISSAO
     , CABECALHO.DTSAIDA
     , CABECALHO.TIPODESCARGA
     , CABECALHO.ROTINALANC
     , CABECALHO.CODENTVEICULO
     , CABECALHO.FUNCLANC
     , CABECALHO.CODFUNCLANC
     , NVL(CABECALHO.PERCALTERCUSTOENT, 0) PERCALTERCUSTOENT
     , PCEMPR.NOME FUNCIONARIOLANC
     , CABECALHO.CODFORNECFRETE
     , PCTRANSPORTE.FORNECEDOR TRANSPORTADORA
     , NVL(CABECALHO.VLIPI,0) VLIPI
     , NVL(CABECALHO.VLBASEIPI,0) VLBASEIPI
     , NVL(CABECALHO.VLDESCFIN,0) VLDESCFIN
     , NVL(CABECALHO.VLFRETE,0) VLFRETE
     , NVL(CABECALHO.TIPOFRETECIFFOB,'C') TIPOFRETECIFFOB
     , NVL(CABECALHO.VLDESCONTO, 0) VLDESCONTO
     , NVL(CABECALHO.BASEICST, 0) BASEICST
     , NVL(CABECALHO.VLST, 0) VLST
     , NVL(CABECALHO.VLICMS, 0) VLICMS
     , NVL(CABECALHO.VLISENTAS, 0) VLISENTAS
     , NVL(CABECALHO.VLBONIFIC, 0) VLBONIFIC
     , CABECALHO.OBS
     , CABECALHO.OBS1
     , CABECALHO.OBS2
     /*
     , PCFORNEC.OBS FORNECOBS          
     , PCFORNEC.OBS2 FORNECOBS2
     , PCFORNEC.OBSERVACAO FORNECOBSERVACAO
     , PCFORNEC.ENDER
     , PCFORNEC.CGC
     , PCFORNEC.CIDADE
     , PCFORNEC.ESTADO
     , PCFORNEC.TELFAB
     , PCFORNEC.TELREP
     , PCFORNEC.FAXREP
     , PCFORNEC.FAXFAB
     , PCFORNEC.TELEXREP     
     , PCFORNEC.TELEXFAB
     , PCFORNEC.TELCOB
     , PCFORNEC.TELEFONECOM     
     , PCFORNEC.TELEFONEADM
     */
     , CABECALHO.NUMBONUS                                                                        
     , CABECALHO.NUMVOL           
     , CABECALHO.NUMDIIMPORTACAO
     , NVL(CABECALHO.TOTPESOLIQ,0) TOTPESOLIQ
     , DECODE(CABECALHO.TIPODESCARGA, 'F', 0, NVL(CABECALHO.VLSISCOMEX,     0)) VLSISCOMEXNF
     , DECODE(CABECALHO.TIPODESCARGA, 'F', 0, NVL(CABECALHO.VLADUANEIRA,    0)) VLADUANEIRANF
     , DECODE(CABECALHO.TIPODESCARGA, 'F', 0, NVL(CABECALHO.VLOUTRASDESPIMP,0)) VLOUTRASDESPIMPNF     
     , PCCONSUM.DTPROXATU
     , PCCONSUM.TX TXDIA
     , POWER(PCCONSUM.TX,30) TXMES
     , CASE WHEN ((NVL(PCCONSUM.PRECOPOREMBALAGEM,'N') = 'S') AND (NVL(PCFILIAL.AUTOSERVICO,'N') = 'S') AND 
(NVL(PCFILIAL.PRECOPOREMBALAGEM,'N') = 'S'))
            THEN 'S'
            ELSE 'N'
       END PRECOPOREMBALAGEM
     , NVL(CABECALHO.TOTPESO,0) TOTPESO                                                                        
     , SUM(NVL(ITENS.PUNIT,0) * (DECODE(NVL(ITENS.QT,0),0, ITENS.QTCONT, ITENS.QT))) VLTOTPUNIT                                                                   
     , COUNT(ITENS.CODPROD) TOTALITENS
     , SUM(NVL(ITENS.VLBONIFIC,0)       * (DECODE(NVL(ITENS.QT,0),0, ITENS.QTCONT, ITENS.QT))) VLBONDINHEIRO
     , ROUND(SUM((NVL(ITENS.PUNIT,0) - (NVL(ITENS.PUNIT,0) / (1+(NVL(ITENS.PERCBON,0)/100))))      *
                 (DECODE(NVL(ITENS.QT,0),0, ITENS.QTCONT, ITENS.QT))),6) VLBONMERCADORIA
     , ROUND(SUM((NVL(ITENS.PUNIT,0) * (NVL(ITENS.PERCBONOUTRAS,0)/100))      *
                 (DECODE(NVL(ITENS.QT,0),0, ITENS.QTCONT, ITENS.QT))),6) VLBONOUTRAS
     , CASE WHEN SUM(NVL(ITENS.PERICMGUIAPROPRIA,0)) > 0 
            THEN ''
            ELSE '** NF C/GUIA PROPRIA DE ICMS **'
       END NFCOMGUIAPROPRIAICMS
     , PCBONUSC.DTMONTAGEM
     , PCBONUSC.DTFECHAMENTOTOTAL
     , CASE
          WHEN((PCFILIAL.CONTROLENFEPORSERIE = 'S') AND(NVL(CABECALHO.CONSUMIUNUMNFE, 'N') = 'N'))
             THEN 'S'
          ELSE 'N'
       END NFPROVISORIO 
     , NVL(CABECALHO.CALCREDPISSERVICO, 'N') CALCREDPISSERVICO
     , NVL(CABECALHO.CALCREDPISSERVICOCONT, 'N') CALCREDPISSERVICOCONT
     , CABECALHO.CALCCREDICMS
     , CABECALHO.CALCCREDICMCUSTOCONT
     , CABECALHO.CALCCREDPISCOFINS
     , CABECALHO.CALCCREDPISCUSTOCONT
     , CABECALHO.REBAIXACUSTOCOMDESCFIN   
     , CABECALHO.NUMTRANSORIGEM
     , PCCONSUM.NUMREGIAOPADRAO
     , NVL(CABECALHO.CONSPOLITICATRIBUTNOTAH, 'N') CONSPOLITICATRIBUTNOTAH
     , NVL(CABECALHO.DEDUZIRICMSBASEPISCOFINS, 'N') DEDUZIRICMSBASEPISCOFINS
     , NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('PRECIFICREGIAOFORAUFSEMST'), 'N') PRECIFICREGIAOFORAUFSEMST
     , CABECALHO.VERSAOROTINA
     , NVL(CABECALHO.IMPORTADOXML,'N') IMPORTADOXML
     , SUM(NVL(ITENSC.VLICMSDESONERACAO, 0) * (DECODE(NVL(ITENS.QT, 0), 0, ITENS.QTCONT, ITENS.QT))) VLICMSDESONERACAO 
     , NVL(CABECALHO.REMESSACOMBENEFIC,'N')REMESSACOMBENEFIC
     , CABECALHO.ORIGEMCUSTOTRANSF ORIGEMCUSTOTRANSF
  FROM PCNFENT CABECALHO
     , PCFORNEC
     , PCEMPR
     , PCFORNEC PCTRANSPORTE
     , PCCONSUM
     , PCMOV ITENS
     , PCMOVCOMPLE ITENSC
     , PCPEDIDO
     , PCFILIAL 
     , PCBONUSC
 WHERE (((CABECALHO.CODFORNEC      = PCFORNEC.CODFORNEC
   AND CABECALHO.CODFUNCLANC    = PCEMPR.MATRICULA(+)
   AND CABECALHO.CODFORNECFRETE = PCTRANSPORTE.CODFORNEC(+)
   AND ((CABECALHO.CODCONT = NVL(CABECALHO.CODCONTFOR,PCCONSUM.CODCONTFOR)) OR
       (CABECALHO.CODCONT = PCCONSUM.CODCONTAJUSTEEST AND CABECALHO.TIPODESCARGA = '4') OR
       (CABECALHO.TIPODESCARGA = 'S' AND ((CABECALHO.ESPECIE = 'NF') OR (CABECALHO.ESPECIE = 'NE'))))
   AND CABECALHO.NUMTRANSENT    = ITENS.NUMTRANSENT
   AND CABECALHO.CODFILIAL      = ITENS.CODFILIAL
   AND ITENS.NUMTRANSITEM       = ITENSC.NUMTRANSITEM
   AND CABECALHO.NUMBONUS       = PCBONUSC.NUMBONUS(+)
   AND ITENS.NUMPED             = PCPEDIDO.NUMPED(+)
   AND PCFILIAL.CODIGO          = CABECALHO.CODFILIAL
   AND CABECALHO.TIPODESCARGA  IN ('1','2','3','4','5','9','R','S','A','E','N','I','F', 'D', 'B', 'M', 'G', 'H', 'J')
   AND ((CABECALHO.VLTOTAL > 0) OR (CABECALHO.VLTOTAL >= 0 AND CABECALHO.TIPODESCARGA = 'G') OR (CABECALHO.TIPODESCARGA = 'R' 
AND CABECALHO.NFBRINDE = 'S')) /*Descarga tipo G nem sempre tem valor total de NF*/
   AND ITENS.DTCANCEL          IS NULL) AND PCFILIAL.CODIGO = 2) AND  TO_CHAR(ITENS.DTMOV, 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -12), 'YYYY')) 
   AND TO_CHAR(CABECALHO.DTENT, 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -12), 'YYYY') 
 GROUP BY CABECALHO.NUMNOTA
     --, CABECALHO.NUMTRANSENT
    --, CABECALHO.NUMTRANSORIGEM
     , PCFILIAL.CONTROLENFEPORSERIE 
     , CABECALHO.CONSUMIUNUMNFE
     , CABECALHO.CODFORNEC
     , PCFORNEC.FORNECEDOR
     , CABECALHO.CODFILIAL
     , CABECALHO.VLTOTAL
     , CABECALHO.SERIE
     , CABECALHO.ESPECIE
     , CABECALHO.DTENT
     , CABECALHO.CODFISCAL
     , CABECALHO.CODCONT
     , CABECALHO.GERANFVENDA
     , CABECALHO.DTEMISSAO
     , CABECALHO.DTSAIDA
     , CABECALHO.TIPODESCARGA
     , CABECALHO.ROTINALANC
     , CABECALHO.CODENTVEICULO
     , CABECALHO.FUNCLANC
     , CABECALHO.CODFUNCLANC
     , CABECALHO.PERCALTERCUSTOENT
     , PCEMPR.NOME 
     , CABECALHO.CALCREDPISSERVICO
     , CABECALHO.CALCREDPISSERVICOCONT     
     , CABECALHO.CODFORNECFRETE
     , PCTRANSPORTE.FORNECEDOR 
     , CABECALHO.VLIPI
     , CABECALHO.VLBASEIPI
     , CABECALHO.VLDESCFIN
     , CABECALHO.VLFRETE
     , CABECALHO.TIPOFRETECIFFOB
     , CABECALHO.VLDESCONTO
     , CABECALHO.VLST
     , CABECALHO.BASEICST
     , CABECALHO.VLICMS
     , CABECALHO.VLISENTAS
     , CABECALHO.VLBONIFIC
     , CABECALHO.OBS
     , CABECALHO.OBS1
     , CABECALHO.OBS2

     , CABECALHO.NUMBONUS                                                                        
     , CABECALHO.NUMVOL                                                                          
     , PCCONSUM.DTPROXATU
     , PCCONSUM.TX
     , CABECALHO.NUMDIIMPORTACAO
     , CABECALHO.TOTPESOLIQ
     , PCCONSUM.TX
     , CABECALHO.TOTPESO
     , PCCONSUM.PRECOPOREMBALAGEM
     , PCFILIAL.AUTOSERVICO
     , PCFILIAL.PRECOPOREMBALAGEM
     , CABECALHO.VLSISCOMEX
     , CABECALHO.VLADUANEIRA
     , CABECALHO.VLOUTRASDESPIMP
     , PCBONUSC.DTMONTAGEM
     , PCBONUSC.DTFECHAMENTOTOTAL 
     , CABECALHO.CALCCREDICMS
     , CABECALHO.CALCCREDICMCUSTOCONT
     , CABECALHO.CALCCREDPISCOFINS
     , CABECALHO.CALCCREDPISCUSTOCONT
     , CABECALHO.REBAIXACUSTOCOMDESCFIN
     , CABECALHO.NUMTRANSORIGEM 
     , PCCONSUM.NUMREGIAOPADRAO 
     , CABECALHO.VERSAOROTINA 
     , CABECALHO.IMPORTADOXML
     , CABECALHO.CONSPOLITICATRIBUTNOTAH
     , NVL(CABECALHO.DEDUZIRICMSBASEPISCOFINS, 'N')
     , CABECALHO.RESTRINGIRCREDICMSTV10
     , NVL(CABECALHO.REMESSACOMBENEFIC,'N')
     , CABECALHO.ORIGEMCUSTOTRANSF     
ORDER BY CABECALHO.DTEMISSAO