SELECT 
INV.NUMINVENT AS NUMEROINVENTARIO,
CASE INV.TIPO 
     WHEN 'R' THEN 'ROTATIVO'
     WHEN 'G' THEN 'GERAL'
END AS TIPOINVENTARIO,
CASE 
    WHEN INV.DTCANCEL IS NULL THEN 'CONCLUÍDO'
    ELSE 'CANCELADO'
END AS STATUS
FROM  PCINVENTENDERECO INV
WHERE TO_CHAR(INV.DATA, 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -24), 'YYYY')
GROUP BY INV.NUMINVENT, INV.TIPO, INV.DTCANCEL