SELECT 
MOV.NUMOS AS NUMEROOS,
CASE WHEN MOV.CODOPER = 'S' THEN 'SAÍDA'
WHEN MOV.CODOPER = 'E' THEN 'ENTRADA'
WHEN MOV.CODOPER = 'EV' THEN 'ENTRADA AVARIA'
WHEN MOV.CODOPER = 'SV' THEN 'SAÍDA AVARIA'
WHEN MOV.CODOPER = 'EA' THEN 'ENTRADA DE AJUSTE'
WHEN MOV.CODOPER = 'SA' THEN 'SAÍDA DE AJUSTE'
ELSE 'NÃO IDENTIFICADO' END AS CODIGOOPERACIONAL, 
MOV.NUMTRANSWMS AS NUMEROTRANSWMS,
CASE WHEN MOV.DTESTORNO IS NULL THEN 'SEM ESTORNO' ELSE 'COM ESTORNO' END AS ESTORNO, 
CASE WHEN MOV.POSICAO = 'C' THEN 'CONCLUÍDO'
WHEN MOV.POSICAO = 'P' THEN 'PENDENTE'
WHEN MOV.POSICAO = 'A' THEN 'AGUARDANDO'
ELSE 'NÃO IDENTIFICADO' END AS POSICAO,
MOV.HORA,
MOV.MINUTO,
TOS.DESCRICAO AS TIPOOS,
TOS.CODIGO AS CODIGOTIPOOS,
TOS.APLICACAO
FROM PCMOVENDPEND MOV
INNER JOIN PCTIPOOS TOS ON TOS.CODIGO = MOV.TIPOOS
WHERE TO_CHAR(MOV.DATA, 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -96), 'YYYY')
GROUP BY MOV.NUMOS, MOV.CODOPER, MOV.NUMTRANSWMS, MOV.DTESTORNO, 
MOV.POSICAO, MOV.HORA, MOV.MINUTO, TOS.CODIGO, TOS.DESCRICAO, 
TOS.APLICACAO