
SELECT 
  PCNFENT.NUMNOTA, PCNFENT.CODFUNCLANC,
  PCNFENT.DTENT,
  PCNFENT.DTSAIDA,
  PCNFSAID.NUMCAR,
  DECODE(PCNFENT.VLTOTAL,0,PCESTCOM.VLDEVOLUCAO,PCNFENT.VLTOTAL) AS VLTOTAL,
  PCNFENT.CODDEVOL,
  PCNFENT.OBS,
  PCTABDEV.MOTIVO,
  PCNFENT.NUMTRANSENT,
  NVL(PCNFENT.TOTPESO,0) TOTPESO,
  PCNFSAID.CODFILIALNF,
  PCCLIENT.CODCLI,
  NVL(PCDEVCONSUM.CLIENTE, PCCLIENT.CLIENTE) CLIENTE,
  NVL(PCDEVCONSUM.CIDADE, PCCLIENT.MUNICENT) MUNICENT,
  NVL(PCDEVCONSUM.ENDERECO, PCCLIENT.ENDERENT) ENDERENT,
  NVL(PCDEVCONSUM.TELEFONE, PCCLIENT.TELENT) TELENT,
  PCNFENT.CODUSURDEVOL CODUSURDEVOL,
  PCNFENT.ROTINALANC,
  PCNFENT.CODMOTORISTADEVOL,
  PCEMPR.NOME,
  PCUSUARI.NOME NOMERCA,
  PCUSUARI.CODSUPERVISOR,
  PCSUPERV.NOME SUPERVISOR,
  FUNC.NOME NOMEFUNC,
  (SELECT   
    SUM(NVL(PCMOV.QTAVARIA,0))
    FROM PCMOV
    WHERE PCMOV.NUMTRANSENT = PCNFENT.numtransent 
    AND PCMOV.CODFILIAL = PCNFENT.CODFILIAL 
    AND PCMOV.CODOPER IN ('ED','EN') 
    AND PCMOV.DTCANCEL IS NULL
    GROUP BY PCMOV.NUMTRANSENT) QTAVARIA,
  (SELECT   
    SUM (PCMOV.qtavaria * PCMOV.PUNIT)
    FROM PCMOV
    WHERE PCMOV.NUMTRANSENT = PCNFENT.NUMTRANSENT
    AND PCMOV.CODFILIAL = PCNFENT.CODFILIAL 
    AND PCMOV.CODOPER IN ('ED','EN') 
    AND PCMOV.DTCANCEL IS NULL
    GROUP BY PCMOV.NUMTRANSENT) VLAVARIA,
    0 AS CONF_MATRICULA,
    '*' AS CONF_NOME,
    PCNFENT.VLFRETE,
    PCNFENT.VLOUTRAS,
    DECODE(PCNFENT.VLTOTAL,0,PCESTCOM.VLDEVOLUCAO,PCNFENT.VLTOTAL) - NVL(PCNFENT.VLOUTRAS,0)  - NVL(PCNFENT.VLFRETE,0)AS VLTOTNF 
FROM PCNFENT, PCESTCOM, PCTABDEV, PCCLIENT, PCEMPR, PCUSUARI, PCSUPERV, PCEMPR FUNC, PCNFSAID, PCDEVCONSUM
WHERE  ( PCNFENT.CODDEVOL = PCTABDEV.CODDEVOL(+) )
AND PCNFENT.NUMTRANSENT = PCESTCOM.NUMTRANSENT (+)
AND   ( PCNFENT.CODFORNEC  = PCCLIENT.CODCLI )
AND ( PCNFENT.NUMTRANSENT = PCDEVCONSUM.NUMTRANSENT(+) )
AND NVL(PCNFENT.CODFILIALNF, PCNFENT.CODFILIAL) = :CODFILIAL
AND   ( PCNFENT.CODFUNCLANC       = FUNC.MATRICULA(+))
AND   ( PCNFENT.CODMOTORISTADEVOL = PCEMPR.MATRICULA(+))
AND   (  PCNFENT.CODUSURDEVOL  = PCUSUARI.CODUSUR )
AND   ( PCUSUARI.CODSUPERVISOR    = PCSUPERV.CODSUPERVISOR(+))
AND   ( PCNFENT.DTENT BETWEEN :DATAINI AND :DATAFIM )
AND   ( PCNFENT.TIPODESCARGA IN ('6','7','T') ) 
AND   ( NVL(PCNFENT.OBS, 'X') <> 'NF CANCELADA')
AND   ( PCNFENT.CODFISCAL IN ('131','132','231','232','199','299') )
AND EXISTS (SELECT PCPRODUT.CODPROD FROM PCPRODUT, PCMOV
             WHERE PCMOV.CODPROD = PCPRODUT.CODPROD
             AND PCMOV.NUMTRANSENT = PCNFENT.NUMTRANSENT
             AND PCMOV.NUMNOTA = PCNFENT.NUMNOTA
             AND PCMOV.DTCANCEL IS NULL
 AND ( EXISTS (
 SELECT CODEPTO FROM PCDEPTO 
  WHERE PCPRODUT.CODEPTO = PCDEPTO.CODEPTO 
    AND PCDEPTO.CODEPTO NOT IN (9999, 999999) 
    AND ((SELECT COUNT(1) 
            FROM PCLIB 
           WHERE CODTABELA = 2 
            AND PCLIB.CODFUNC = :CODFUNCX 
            AND ((PCLIB.CODIGON = 9999) OR (PCLIB.CODIGON = 999999))) > 0 OR 
        (SELECT COUNT(1) 
            FROM PCLIB 
           WHERE CODTABELA = 2 
             AND PCLIB.CODFUNC = :CODFUNCX 
             AND PCLIB.CODIGON = PCDEPTO.CODEPTO 
             AND PCLIB.CODIGON IS NOT NULL) > 0))) 
 AND (EXISTS (
 SELECT CODFORNEC FROM PCFORNEC 
  WHERE PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC 
    AND PCFORNEC.CODFORNEC NOT IN (9999, 999999) 
    AND ((SELECT COUNT(1) 
            FROM PCLIB 
           WHERE CODTABELA = 3 
            AND PCLIB.CODFUNC = :CODFUNCX 
            AND ((PCLIB.CODIGON = 9999) OR (PCLIB.CODIGON = 999999))) > 0 OR 
        (SELECT COUNT(1) 
            FROM PCLIB 
           WHERE CODTABELA = 3 
             AND PCLIB.CODFUNC = :CODFUNCX 
             AND PCLIB.CODIGON = PCFORNEC.CODFORNEC 
             AND PCLIB.CODIGON IS NOT NULL) > 0))) 
             AND PCMOV.CODFILIAL = PCNFENT.CODFILIAL)
 AND (EXISTS (
 SELECT CODSUPERVISOR FROM PCUSUARI 
  WHERE PCUSUARI.CODSUPERVISOR = PCUSUARI.CODSUPERVISOR 
    AND PCUSUARI.CODSUPERVISOR NOT IN (9999, 999999) 
    AND ((SELECT COUNT(1) 
            FROM PCLIB 
           WHERE CODTABELA = 7 
             AND PCLIB.CODFUNC = :CODFUNCX 
             AND ((PCLIB.CODIGON = 9999) OR (PCLIB.CODIGON = 999999))) > 0 OR 
         (SELECT COUNT(1) 
            FROM PCLIB 
           WHERE CODTABELA = 7 
             AND PCLIB.CODFUNC = :CODFUNCX 
             AND PCLIB.CODIGON = PCUSUARI.CODSUPERVISOR 
             AND PCLIB.CODIGON IS NOT NULL) > 0))) 
AND PCESTCOM.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA(+) 
  AND NVl(PCNFSAID.CONDVENDA,0) NOT IN (4, 8, 10, 13, 20, 98, 99)
AND PCESTCOM.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA(+) 
  GROUP BY PCNFENT.NUMNOTA,PCNFENT.CODFUNCLANC,PCNFENT.DTENT,PCNFENT.DTSAIDA,                                           
    PCNFENT.CODDEVOL,PCNFENT.OBS,PCTABDEV.MOTIVO,PCNFENT.NUMTRANSENT,                                            
    NVL(PCNFENT.TOTPESO,0),PCNFSAID.CODFILIALNF,PCCLIENT.CODCLI,                                                 
    NVL(PCDEVCONSUM.CLIENTE, PCCLIENT.CLIENTE) ,NVL(PCDEVCONSUM.CIDADE, PCCLIENT.MUNICENT),                        
    NVL(PCDEVCONSUM.ENDERECO, PCCLIENT.ENDERENT),NVL(PCDEVCONSUM.TELEFONE, PCCLIENT.TELENT),                       
    PCNFENT.CODUSURDEVOL  ,PCNFENT.ROTINALANC,PCNFENT.CODMOTORISTADEVOL,                                            
    PCEMPR.NOME,PCUSUARI.NOME ,PCUSUARI.CODSUPERVISOR,PCSUPERV.NOME ,FUNC.NOME, PCNFENT.CODFILIAL,PCNFENT.VLFRETE, 
    PCNFENT.VLOUTRAS,PCNFENT.VLTOTAL,PCESTCOM.VLDEVOLUCAO,PCNFENT.CODFORNEC, PCNFSAID.NUMCAR                       
  ORDER BY SUPERVISOR, NOMERCA