SELECT APU.CODFILIAL AS CODIGOFILIAL,
APU.CODUSUR AS CODIGORCA,
APU.TIPOMETA,
APU.CODIGO AS CODIGOENTIDADE,
TO_CHAR(APU.DTINICIO, 'YYYYMM')  AS REFERENCIA,
APU.COLUNA AS METRICA,
APU.DTINICIO AS DATA,
APU.PREVISTO AS PREVISTO,
APU.REALIZADO AS REALIZADO,
APU.PREMIO AS PREMIO
FROM PCAPURACAMPANHA APU
WHERE TO_CHAR(APU.DTINICIO, 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -24), 'YYYY')