SELECT 
CLI.CODCLI AS CODIGOCLIENTE,
CLI.CLIENTE AS CLIENTE,
CLI.CGCENT AS CPJCNPJ,
CLI.TIPOFJ AS TIPOCLIENTE,
CASE WHEN CID.CODIBGE IS NULL THEN 999 
ELSE CID.CODIBGE END AS CODIGOIBGE,
CLI.BAIRROENT AS BAIRRO,
CLI.CEPENT AS CEP,
CLI.ENDERENT AS ENDERECO,
CLI.FANTASIA AS NOMEFANTASIA,
CLI.CLASSEVENDA AS CLASSE,
CLI.VIP AS CLASSIFICACAO,
CLI.EMAIL AS EMAILCLIENTE,
ATI.CODATIV AS CODIGORAMOATIVIDADE,
ATI.RAMO AS RAMOATIVIDADE,
RED.DESCRICAO AS GRUPO,
PRA.PRACA AS PRACA,
ROT.CODROTA AS CODIGOROTA,
ROT.DESCRICAO AS ROTA,
RED.CODREDE AS CODIGOREDE, 
RED.DESCRICAO AS REDE,
REG.REGIAO AS REGIAO,
REG.UF AS UFREGIAO,
(SELECT CLI2.FANTASIA FROM PCCLIENT CLI2 WHERE CLI2.CODCLI = CLI.CODCLIPRINC)
AS NOMEFANTASIACLIENTEPRINCIPAL,
(SELECT CLI3.CLIENTE FROM PCCLIENT CLI3 WHERE CLI3.CODCLI = CLI.CODCLIPRINC)
AS CLIENTEPRINCIPAL,
CASE WHEN CLI.DTEXCLUSAO IS NOT NULL THEN 'EXCLUÍDO'
WHEN (cli.DTEXCLUSAO IS NULL AND (TRUNC(SYSDATE) - TRUNC(NVL(cli.DTULTCOMP,cli.DTCADASTRO))) >= (SELECT NUMDIASCLIINATIV FROM PCCONSUM)) THEN 'INATIVO'
WHEN (cli.DTEXCLUSAO IS NULL AND (TRUNC(SYSDATE) - TRUNC(NVL(cli.DTULTCOMP,cli.DTCADASTRO))) < (SELECT NUMDIASCLIINATIV FROM PCCONSUM)) THEN 'ATIVO'
END STATUS,
CASE WHEN CLI.DTEXCLUSAO IS NOT NULL THEN 'EXCLUÍDO'
WHEN CLI.DTPRIMCOMPRA IS NULL THEN 'SEM COMPRA'
WHEN CAST (ROUND(SYSDATE - CLI.DTULTCOMP, 0) AS NUMERIC(8,0)) <= 30 THEN 'ATÉ 30 DIAS'
WHEN CAST (ROUND(SYSDATE - CLI.DTULTCOMP, 0) AS NUMERIC(8,0)) > 30 AND CAST (ROUND(SYSDATE - CLI.DTULTCOMP, 0) AS NUMERIC(8,0)) <= 45 THEN 'DE 31 A 45 DIAS'
WHEN CAST (ROUND(SYSDATE - CLI.DTULTCOMP, 0) AS NUMERIC(8,0)) > 45 AND CAST (ROUND(SYSDATE - CLI.DTULTCOMP, 0) AS NUMERIC(8,0)) <= 60 THEN 'DE 46 A 60 DIAS'
WHEN CAST (ROUND(SYSDATE - CLI.DTULTCOMP, 0) AS NUMERIC(8,0)) > 60 AND CAST (ROUND(SYSDATE - CLI.DTULTCOMP, 0) AS NUMERIC(8,0)) <= 90 THEN 'DE 60 A 90 DIAS'
WHEN CAST (ROUND(SYSDATE - CLI.DTULTCOMP, 0) AS NUMERIC(8,0)) > 90 AND CAST (ROUND(SYSDATE - CLI.DTULTCOMP, 0) AS NUMERIC(8,0)) <= 120 THEN 'DE 91 A 120 DIAS'
WHEN CAST (ROUND(SYSDATE - CLI.DTULTCOMP, 0) AS NUMERIC(8,0)) > 120 THEN 'MAIS DE 120 DIAS'
ELSE 'SEM DEFINIÇÃO' END DIASINATIVOS
FROM PCCLIENT CLI
LEFT JOIN PCPRACA PRA ON PRA.CODPRACA = CLI.CODPRACA
LEFT JOIN PCROTAEXP ROT ON ROT.CODROTA = PRA.ROTA
LEFT JOIN PCREGIAO REG ON REG.NUMREGIAO = PRA.NUMREGIAO
LEFT JOIN PCREDECLIENTE RED ON RED.CODREDE = CLI.CODREDE
LEFT JOIN PCATIVI ATI ON ATI.CODATIV = CLI.CODATV1
LEFT JOIN PCCIDADE CID ON CID.CODCIDADE = CLI.CODCIDADE