SELECT
PF.CODPROD AS CODIGOPRODUTO,
PF.CODFILIAL AS CODIGOFILIAL,
PF.CODCOMPRADOR AS CODIGOCOMPRADOR,
PF.PROIBIDAVENDA AS PROIBIDAVENDA,
PF.FORALINHA AS FORALINHA,
PF.REVENDA AS REVENDA,
EMP.NOME AS COMPRADOR
FROM PCPRODFILIAL PF
INNER JOIN PCPRODUT PRO ON PRO.CODPROD = PF.CODPROD
INNER JOIN PCEMPR EMP ON EMP.MATRICULA = PF.CODCOMPRADOR