SELECT 
--PCMOV.NUMPED AS NUMEROPEDIDO,
--PCMOV.NUMTRANSVENDA AS NUMEROTRANSACAOVENDA,
TO_CHAR(PCNFSAID.DTSAIDA, 'YYYY-MM-DD') AS DATAFATURAMENTO,
PCNFSAID.numnota,
PCMOV.CODPROD AS CODIGOPRODUTO,
pcprodut.descricao,
PCMOV.CODUSUR AS CODIGORCA,
PCMOV.CODCLI AS CODIGOCLIENTE,
pcclient.cliente,
pcclient.cgcent,
--PCMOV.CODFILIAL AS CODIGOFILIAL,
--CAST(NVL(PCMOV.CODAUXILIAR, PCPRODUT.CODAUXILIAR) AS NUMERIC(20,0)) AS CODIGOAUXILIAR,
PCNFSAID.CODCOB AS CODIGOCOBRANCA,
--PCNFSAID.CODPLPAG AS CODIGOPLANOPAGAMENTO,
--PCNFSAID.NUMCAR AS NUMEROCARREGAMENTO,

 ------------------------------------------------------

        ---------------                                                       
 
  NVL(
    DECODE(PCNFSAID.CONDVENDA,
    5,
    DECODE(NVL(PCMOV.PBONIFIC, 0),
    0,
    PCMOV.PTABELA + NVL(PCMOV.VLDESCONTO, 0),
    PCMOV.PBONIFIC + NVL(PCMOV.VLDESCONTO, 0)),
    6,
    DECODE(NVL(PCMOV.PBONIFIC, 0),
    0,
    PCMOV.PTABELA + NVL(PCMOV.VLDESCONTO, 0),
    PCMOV.PBONIFIC + NVL(PCMOV.VLDESCONTO, 0)),
    11,
    DECODE(NVL(PCMOV.PBONIFIC, 0),
    0,
    PCMOV.PTABELA + NVL(PCMOV.VLDESCONTO, 0),
    PCMOV.PBONIFIC + NVL(PCMOV.VLDESCONTO, 0)),
    12,
    DECODE(NVL(PCMOV.PBONIFIC, 0),
    0,
    PCMOV.PTABELA + NVL(PCMOV.VLDESCONTO, 0),
    PCMOV.PBONIFIC + NVL(PCMOV.VLDESCONTO, 0)),
    0),
0) as VALORUNITARIOBONIFICADO,


 NVL((NVL(PCMOV.QT, 0) *
           DECODE(PCNFSAID.CONDVENDA, 5, 1, 6, 1, 11, 1, 12, 1, 0)),
           0) as QUANTIDADEBONIFICADA,

 NVL((NVL(PCMOV.QT, 0) *
           DECODE(PCNFSAID.CONDVENDA, 5, 1, 6, 1, 11, 1, 12, 1, 0)),
           0) *   NVL(
    DECODE(PCNFSAID.CONDVENDA,
    5,
    DECODE(NVL(PCMOV.PBONIFIC, 0),
    0,
    PCMOV.PTABELA + NVL(PCMOV.VLDESCONTO, 0),
    PCMOV.PBONIFIC + NVL(PCMOV.VLDESCONTO, 0)),
    6,
    DECODE(NVL(PCMOV.PBONIFIC, 0),
    0,
    PCMOV.PTABELA + NVL(PCMOV.VLDESCONTO, 0),
    PCMOV.PBONIFIC + NVL(PCMOV.VLDESCONTO, 0)),
    11,
    DECODE(NVL(PCMOV.PBONIFIC, 0),
    0,
    PCMOV.PTABELA + NVL(PCMOV.VLDESCONTO, 0),
    PCMOV.PBONIFIC + NVL(PCMOV.VLDESCONTO, 0)),
    12,
    DECODE(NVL(PCMOV.PBONIFIC, 0),
    0,
    PCMOV.PTABELA + NVL(PCMOV.VLDESCONTO, 0),
    PCMOV.PBONIFIC + NVL(PCMOV.VLDESCONTO, 0)),
    0),
0) as "VAlor Total"



FROM PCNFSAID, PCPLPAG
      , PCCLIENT
      , PCPRACA
      , PCMOV
      , PCPRODUT
      , PCMOVCOMPLE
  WHERE PCNFSAID.NUMTRANSVENDA = PCMOV.NUMTRANSVENDA
    AND PCNFSAID.NUMNOTA = PCMOV.NUMNOTA
    AND PCMOV.CODPROD = PCPRODUT.CODPROD
    ANd PCMOV.codfornec in (1203,4)
    AND PCCLIENT.CODPRACA = PCPRACA.CODPRACA
    AND PCNFSAID.CODCLI = PCCLIENT.CODCLI
    AND NVL(PCNFSAID.TIPOVENDA, 'X') NOT IN ('SR', 'DF')
    AND PCNFSAID.DTCANCEL IS NULL
    AND PCMOV.NUMTRANSITEM = PCMOVCOMPLE.NUMTRANSITEM(+)
    AND NVL(PCMOV.TIPOITEM, 'C') IN ('C', 'N')
    AND PCNFSAID.CODFISCAL <> 0
    AND PCNFSAID.DTSAIDA >= (SELECT MIN(DTSAIDA) FROM PCNFSAID)
    AND PCNFSAID.NUMTRANSVENDA >= (SELECT MIN(NUMTRANSVENDA) FROM PCNFSAID)
    AND PCMOVCOMPLE.NUMTRANSITEM >= (SELECT MIN(NUMTRANSITEM) FROM PCMOVCOMPLE)
    AND PCMOV.NUMTRANSVENDA >= (SELECT MIN(NUMTRANSVENDA) FROM PCMOV)
   --AND PCNFSAID.CODFISCAL NOT IN (722, 532, 632, 732)
   AND PCNFSAID.CONDVENDA IN (11)
and PCPLPAG.CODPLPAG = PCNFSAID.CODPLPAG

   --AND TO_CHAR(PCNFSAID.DTSAIDA, 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -1), 'YYYY')
   --AND TO_CHAR(PCNFSAID.DTSAIDA, 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -1), 'YYYY')
   --AND PCNFSAID.DTSAIDA >= to_date('01/10/2023','dd/mm/yyyy') AND PCNFSAID.DTSAIDA <= to_date('31/10/2023','dd/mm/yyyy')
   AND PCNFSAID.DTSAIDA >= to_date(:Data_init,'dd/mm/yyyy') AND PCNFSAID.DTSAIDA <= to_date(:Data_final,'dd/mm/yyyy')