SELECT 0 SELECIONADO,
       PCUSURFORNEC.CODUSUR,
       PCUSUARI.NOME RCA,
       PCUSURFORNEC.CODFORNEC,
       PCFORNEC.FORNECEDOR
  FROM PCUSURFORNEC, PCUSUARI, PCFORNEC
 WHERE PCUSURFORNEC.CODUSUR = PCUSUARI.CODUSUR
   AND PCUSURFORNEC.CODFORNEC = PCFORNEC.CODFORNEC
   AND NVL(PCFORNEC.BLOQUEIO,'N') <> 'S'
 AND PCUSUARI.CODSUPERVISOR IN (55)
 AND PCUSUARI.DTTERMINO IS NULL