SELECT  
BON.NUMBONUS AS NUMEROBONUS,
CASE WHEN BON.DTCANCEL IS NOT NULL THEN 'CANCELADO' ELSE 'PROCESSADO' END AS PROCESSAMENTO,
CASE WHEN BON.DTFECHAMENTO IS NOT NULL THEN 'FECHADO' ELSE 'ABERTO' END AS FECHAMENTO,
CASE WHEN SUM(BONI.QTNF) <> SUM(BONI.QTENTRADA) THEN 'COM FALTA' ELSE 'SEM FALTA' END AS FALTA,
CASE WHEN SUM(BONI.QTAVARIA) <> 0 THEN 'COM AVARIA' ELSE 'SEM AVARIA' END AS AVARIA

FROM PCBONUSC BON
LEFT JOIN PCBONUSI BONI ON BONI.NUMBONUS = BON.NUMBONUS
AND TO_CHAR(BON.DATABONUS, 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -96), 'YYYY')
GROUP BY BON.NUMBONUS, BON.DTCANCEL, BON.DTFECHAMENTO