SELECT 
ENDE.CODENDERECO AS CODIGOENDERECO,
ENDE.CODFILIAL AS CODIGOFILIAL,
ENDE.DEPOSITO,
ENDE.RUA,
ENDE.PREDIO,
ENDE.NIVEL,
ENDE.APTO AS APARTAMENTO, 
ENDE.ESTACAO,
CASE ENDE.TIPOENDER
     WHEN 'AE' THEN 'AÉREO'
     WHEN 'AP' THEN 'PICKING'
     ELSE 'NÃO IDENTIFICADO'
END AS TIPOENDERECO,

CASE ENDE.SITUACAO
     WHEN 'L' THEN 'LIVRE'
     WHEN 'O' THEN 'OCUPADO'
      ELSE 'NÃO IDENTIFICADO'
END AS SITUACAO,

CASE ENDE.BLOQUEIO
     WHEN 'S' THEN 'BLOQUEADO'
     WHEN 'N' THEN 'DISPONÍVEL'
     ELSE 'NÃO IDENTIFICADO'
END AS BLOQUEIO,

CASE ENDE.STATUS
     WHEN 'N' THEN 'NORMAL'
     WHEN 'F' THEN 'FALTA'
     WHEN 'C' THEN 'CROSSDOCKING'
     WHEN 'A' THEN 'AVARIA'
     WHEN 'E' THEN 'EXCESSO'
     WHEN 'S' THEN 'STAGE'
     ELSE 'NÃO IDENTIFICADO'
END AS STATUS,
TIPPAL.DESCRICAO AS TAMANHOENDERECO,
TIPEST.DESCRICAO AS TIPOESTRUTURA,
CASE WHEN (SELECT PARWMS.VALOR FROM PCPARAMETROWMS PARWMS WHERE PARWMS.CODFILIAL = ENDE.CODFILIAL AND PARWMS.NOME='DEPOSITOVIRTUAL')
=  ENDE.DEPOSITO
THEN 'SIM' ELSE 'NÃO' END AS DEPOSITOVIRTUAL
FROM PCENDERECO ENDE
INNER JOIN PCTIPOPAL TIPPAL ON ENDE.TIPOPAL = TIPPAL.CODIGO
INNER JOIN PCTIPOESTRUTURA TIPEST ON ENDE.CODESTRUTURA = TIPEST.CODIGO