SELECT 'E'  AS CODIGOOPERACAO, 'ENTRADA DE MERCADORIA (NORMAL)' AS TIPOOPERACAO, 'ENTRADA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'EA' AS CODIGOOPERACAO, 'ENRADA DE AJUSTE DE MERCADORIA' AS TIPOOPERACAO, 'ENTRADA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'EB' AS CODIGOOPERACAO, 'ENTRADA DE BONIFICAÇÃO DE MERCADORIA' AS TIPOOPERACAO, 'ENTRADA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'EC' AS CODIGOOPERACAO, 'ENTRADA DE CONSIGNAÇÃO DE MERCADORIA' AS TIPOOPERACAO, 'ENTRADA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'ED' AS CODIGOOPERACAO, 'ENTRADA DE DEVOLUÇÃO DE CLIENTE' AS TIPOOPERACAO, 'ENTRADA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'EF' AS CODIGOOPERACAO, 'ENTRADA DE COMODATA' AS TIPOOPERACAO, 'ENTRADA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'EG' AS CODIGOOPERACAO, 'ENTRADA DE BENEFICIAMENTO' AS TIPOOPERACAO, 'ENTRADA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'EI' AS CODIGOOPERACAO, 'ENTRADA DE INVENTÁRIO' AS TIPOOPERACAO, 'ENTRADA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'EL' AS CODIGOOPERACAO, 'ENTRADA DE PERDA DE MERCADORIA' AS TIPOOPERACAO, 'ENTRADA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'EM' AS CODIGOOPERACAO, 'ENTRADA DE MATERIAIS DE CONSUMO' AS TIPOOPERACAO, 'ENTRADA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'EN' AS CODIGOOPERACAO, 'ENTRADA DE DEV. DA VENDA CONSIGNADA' AS TIPOOPERACAO, 'ENTRADA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'EO' AS CODIGOOPERACAO, 'ENTRADA DE DEV. DE COMODATO' AS TIPOOPERACAO, 'ENTRADA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'EP' AS CODIGOOPERACAO, 'ENTRADA/ESTORNO DE PRODUÇÃO DE MERCADORIA' AS TIPOOPERACAO, 'ENTRADA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'ER' AS CODIGOOPERACAO, 'ENTRADA DE SIMPLES REMESSA' AS TIPOOPERACAO, 'ENTRADA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'ES' AS CODIGOOPERACAO, 'ENTRADA DE SOBRA DE MERCADORIA' AS TIPOOPERACAO, 'ENTRADA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'ET' AS CODIGOOPERACAO, 'ENTRADA DE TRANSFERÊNCIA DE MERCADORIA' AS TIPOOPERACAO, 'ENTRADA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'EV' AS CODIGOOPERACAO, 'ENTRADA DE DEV. DE REMESSA DE BENEFICIAMENTO' AS TIPOOPERACAO, 'ENTRADA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'E1' AS CODIGOOPERACAO, 'ENTRADA DE AVARIA' AS TIPOOPERACAO, 'ENTRADA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'EX' AS CODIGOOPERACAO, 'DEVOLUÇÃO AVULSA' AS TIPOOPERACAO, 'ENTRADA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'S'  AS CODIGOOPERACAO, 'SAÍDA DE MERCADORIA (NORMAL)' AS TIPOOPERACAO, 'SAÍDA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'SA' AS CODIGOOPERACAO, 'SAÍDA DE AJUSTE DE MERCADORIA' AS TIPOOPERACAO, 'SAÍDA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'SB' AS CODIGOOPERACAO, 'SAÍDA DE BONIFICAÇÃO DE MERCADORIA' AS TIPOOPERACAO, 'SAÍDA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'SC' AS CODIGOOPERACAO, 'SAÍDA DE CONSIGNAÇÃO DE MERCADORIA' AS TIPOOPERACAO, 'SAÍDA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'SD' AS CODIGOOPERACAO, 'SAÍDA DE DEVOLUÇÃO DE FORNECEDOR' AS TIPOOPERACAO, 'SAÍDA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'SF' AS CODIGOOPERACAO, 'SAÍDA DE DEVOLUÇÃO DE COMODATA' AS TIPOOPERACAO, 'SAÍDA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'SG' AS CODIGOOPERACAO, 'SAÍDA DE BENEFICIAMENTO' AS TIPOOPERACAO, 'SAÍDA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'SI' AS CODIGOOPERACAO, 'SAÍDA DE INVENTÁRIO' AS TIPOOPERACAO, 'SAÍDA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'SL' AS CODIGOOPERACAO, 'SAÍDA DE PERDA DE MERCADORIA' AS TIPOOPERACAO, 'SAÍDA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'SM' AS CODIGOOPERACAO, 'SAÍDA DE MATERIAIS DE CONSUMO' AS TIPOOPERACAO, 'SAÍDA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'SN' AS CODIGOOPERACAO, 'SAÍDA DE BENEFICIAMENTO' AS TIPOOPERACAO, 'SAÍDA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'SO' AS CODIGOOPERACAO, 'SAÍDA DE COMODATO' AS TIPOOPERACAO, 'SAÍDA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'SP' AS CODIGOOPERACAO, 'SAÍDA/ESTORNO DE PRODUÇÃO (REQ. MAT. PRIMA)' AS TIPOOPERACAO, 'SAÍDA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'SR' AS CODIGOOPERACAO, 'SAÍDA DE SIMPLES REMESSA' AS TIPOOPERACAO, 'SAÍDA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'SS' AS CODIGOOPERACAO, 'SAÍDA DE SOBRA DE MERCADORIA' AS TIPOOPERACAO, 'SAÍDA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'ST' AS CODIGOOPERACAO, 'SAÍDA DE TRANSFERÊNCIA DE MERCADORIA' AS TIPOOPERACAO, 'SAÍDA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'SV' AS CODIGOOPERACAO, 'SAÍDA DE AVARIA' AS TIPOOPERACAO, 'SAÍDA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'S1' AS CODIGOOPERACAO, 'SAÍDA DE REAPROVEITAMENTO' AS TIPOOPERACAO, 'SAÍDA' AS NATUREZAOPERACAO FROM DUAL UNION ALL
SELECT 'RA' AS CODIGOOPERACAO, 'REQUISIÇÃO AVULSA' AS TIPOOPERACAO, 'SAÍDA' AS NATUREZAOPERACAO FROM DUAL