----------------------------------
Timestamp: 08:24:57.612
--grid 
WITH PARAMETROS AS 
 (SELECT CODIGO, 
         NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('BLOQUEIAVENDAESTPENDENTE', 
                                           PCFILIAL.CODIGO), 
             PCCONSUM.BLOQUEIAVENDAESTPENDENTE) BLOQUEIAVENDAESTPENDENTE, 
         NVL(PCFILIAL.PRECOPOREMBALAGEM, PCCONSUM.PRECOPOREMBALAGEM) PRECOPOREMBALAGEM, 
         NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('USAPOLITICACOMERCIALPRODFILIAL'), 
                 'P') USAPOLITICACOMERCIALPRODFILIAL, 
         NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('CON_USANEGFORNEC'), 'N') USANEGFORNEC 
    FROM PCFILIAL, 
         PCCONSUM 
   WHERE CODIGO <> '99' 
   AND CODIGO IN('2')
     AND DTEXCLUSAO IS NULL), 
 PCEST2 AS ( 
    SELECT PCEST.DTULTFAT, PCEST.QTESTGER, PCEST.QTRESERV, PCEST.QTBLOQUEADA,PCEST.QTPENDENTE, PCEST.CUSTOULTENT, 
           PCEST.CODFILIAL, PCEST.CODPROD, PCEST.DTULTENT, PCEST.DTULTSAIDA, PCEST.CUSTOFIN, PCEST.CUSTOREP, 
           PCEST.CUSTOREAL, PCEST.CUSTOPROXIMACOMPRA, PCEST.VALORULTENT, PCEST.CUSTOULTPEDCOMPRA, 
           PCEST.CUSTOULTENTFIN, PCEST.CUSTOFORNEC, PCEST.QTULTENT 
    FROM PCEST, PARAMETROS 
    WHERE PCEST.CODFILIAL = PARAMETROS.CODIGO 
    AND PCEST.CODFILIAL IN('2')
) 
 select DISTINCT A.* from (  
SELECT DISTINCT 
       PCPRODUT.CODPROD,
       NVL(PCPRODUT.DESCRICAO,'') DESCRICAO, 
       NVL(PCPRODUT.QTUNITCX,0) QTUNITCX, 
       NVL(PCMARCA.MARCA,'') MARCA, 
       NVL(PCLINHAPROD.DESCRICAO,'') LINHAPROD, 
       PCPRODUT.CODMARCA, 
       NVL(PCPRODUT.CODLINHAPROD,0) CODLINHA, 
       NVL(PCPRODUT.EMBALAGEM, '') EMBALAGEM, 
       NVL(PCPRODUT.CLASSE, '') CLASSE, 
       MAX(PCEST2.DTULTFAT)DTULTFAT, 
       NVL(PCPRODUT.CLASSEVENDA, '') CLASSEVENDA,
       PCPRODUT.NUMORIGINAL, 
       PARAMETROS.PRECOPOREMBALAGEM, 
       SUM(PCEST2.QTULTENT) QTULTENT, 
       SUM(PCEST2.QTESTGER / DECODE(NVL(PCPRODUT.QTUNITCX,0), 0, 1, PCPRODUT.QTUNITCX)) QTESTOQUECX,
       SUM(PCEST2.QTESTGER) QTESTOQUE, 
       SUM(PCEST2.CUSTOULTENT * PCEST2.QTESTGER) CUSTOULTENT2,
       SUM(((PCEST2.QTESTGER) * (PCPRODUT.PESOLIQ))) PESOLIQ, 
       SUM(NVL(PCEST2.QTESTGER,0) * NVL(PCEST2.CUSTOREP,0)) VLCUSTOREP, 
       SUM(NVL(PCEST2.QTESTGER,0) * DECODE(PARAMETROS.USANEGFORNEC, 
                                          'S', 
                                          NVL(PCPRODUT.CUSTOPROXIMACOMPRA, 0), 
                                          NVL(PCPRODUT.CUSTOREP, 0))) VLCUSTOPROX, 
       SUM(NVL(PCEST2.QTESTGER, 0) * DECODE(PARAMETROS.USAPOLITICACOMERCIALPRODFILIAL, 
                                           'P', 
                                           DECODE(PARAMETROS.USANEGFORNEC, 
                                                  'S', 
                                                  NVL(PCPRODUT.CUSTOPROXIMACOMPRA, 0), 
                                                  NVL(PCPRODUT.CUSTOREP, 0)), 
                                           DECODE(PARAMETROS.USANEGFORNEC, 
                                                  'S', 
                                                  NVL(PCEST2.CUSTOPROXIMACOMPRA, 0), 
                                                  NVL(PCEST2.CUSTOREP, 0)))) VLCUSTOPROXPARAM, 
       SUM(NVL(PCEST2.QTESTGER,0) * NVL(PCEST2.CUSTOFIN,0)) VLCUSTOFIN, 
       SUM(NVL(PCEST2.QTESTGER,0) * NVL(PCEST2.CUSTOULTENT,0)) CUSTOULTENT, 
       SUM(NVL(PCEST2.QTESTGER,0) * NVL(PCEST2.VALORULTENT,0)) VALORULTENT, 
       SUM(NVL(PCEST2.QTESTGER,0) * NVL(PCEST2.CUSTOREAL,0)) VLCUSTOREAL, 
       SUM(NVL(PCEST2.QTESTGER, 0) * NVL(PCEST2.CUSTOULTPEDCOMPRA, 0)) CUSTOULTPEDCOMPRA, 
       SUM(NVL(PCEST2.QTESTGER, 0) * NVL(PCEST2.CUSTOULTENTFIN, 0)) CUSTOULTENTFIN, 
       SUM(NVL(PCEST2.QTESTGER, 0) * DECODE(PARAMETROS.USANEGFORNEC, 
                                           'S', 
                                           NVL(PCEST2.CUSTOPROXIMACOMPRA, 0), 
                                           NVL(PCEST2.CUSTOREP, 0))) CUSTOPROXIMACOMPRA, 
       SUM(NVL(PCEST2.QTESTGER, 0) * NVL(PCPRODUT.CUSTOFORNEC, 0)) CUSTOFORNEC, 
       (CASE 
         WHEN PARAMETROS.PRECOPOREMBALAGEM = 'S' THEN 
          (SUM(NVL(PCEST2.QTESTGER, 0) * 
               NVL((SELECT NVL(PCEMBALAGEM.PVENDA, 0) 
                FROM PCEMBALAGEM 
                WHERE PCEMBALAGEM.CODFILIAL = PCEST2.CODFILIAL 
                AND (PCEMBALAGEM.CODPROD = PCEST2.CODPROD) 
                AND PCEMBALAGEM.QTUNIT = 1 
                AND ROWNUM = 1), 0))) 
         ELSE 
          (SUM(NVL(PCEST2.QTESTGER, 0) * 
               NVL((SELECT NVL(PCTABPR.PVENDA, 0) 
                FROM PCTABPR 
                WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
                AND (PCTABPR.NUMREGIAO = 2)), 0))) 
       END) VLPVENDA, 
       (CASE 
         WHEN PARAMETROS.PRECOPOREMBALAGEM = 'S' THEN 
          (SUM(NVL(PCEST2.QTESTGER, 0) * 
               NVL((SELECT NVL(PCEMBALAGEM.PTABELA, 0) 
                  FROM PCEMBALAGEM 
                 WHERE PCEMBALAGEM.CODFILIAL = PCEST2.CODFILIAL 
                   AND (PCEMBALAGEM.CODPROD = PCEST2.CODPROD) 
                   AND PCEMBALAGEM.QTUNIT = 1 
                   AND ROWNUM = 1), 0))) 
         ELSE 
          (SUM(NVL(PCEST2.QTESTGER, 0) * 
               NVL((SELECT NVL(PCTABPR.PTABELA, 0) 
                  FROM PCTABPR 
                 WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
                   AND (PCTABPR.NUMREGIAO = 2)), 0))) 
       END) PTABELA, 
       MAX(PCEST2.DTULTENT) DTULTENT, 
       MAX(PCEST2.DTULTSAIDA) DTULTSAIDA, 
       MAX(NVL(PCEST2.CUSTOFIN ,0)) AS CUSTOFIN_2, 
       MAX(NVL(PCEST2.CUSTOREP ,0)) AS CUSTOREP_2, 
       MAX(NVL(PCEST2.CUSTOREAL,0)) AS CUSTOREAL_2, 
       MAX(NVL(PCEST2.CUSTOULTENT,0)) AS CUSTOULTENT_2, 
       MAX(DECODE(PARAMETROS.USANEGFORNEC, 
                  'S', 
                  NVL(PCPRODUT.CUSTOPROXIMACOMPRA, 0), 
                  NVL(PCPRODUT.CUSTOREP, 0))) AS CUSTOPROX_2, 
       MAX(DECODE(PARAMETROS.USAPOLITICACOMERCIALPRODFILIAL, 
                  'P', 
                  DECODE(PARAMETROS.USANEGFORNEC, 
                         'S', 
                         NVL(PCPRODUT.CUSTOPROXIMACOMPRA, 0), 
                         NVL(PCPRODUT.CUSTOREP, 0)), 
                  DECODE(PARAMETROS.USANEGFORNEC, 
                         'S', 
                         NVL(PCEST2.CUSTOPROXIMACOMPRA, 0), 
                         NVL(PCEST2.CUSTOREP, 0)))) AS CUSTOPROXPARAM_2, 
       MAX(NVL(PCEST2.VALORULTENT,0)) AS VALORULTENT_2, 
       MAX(NVL(PCEST2.CUSTOULTPEDCOMPRA, 0)) CUSTOULTPEDCOMPRA_2, 
       MAX(NVL(PCEST2.CUSTOULTENTFIN, 0)) CUSTOULTENTFIN_2, 
       MAX(DECODE(PARAMETROS.USANEGFORNEC, 
                  'S', 
                  NVL(PCEST2.CUSTOPROXIMACOMPRA, 0), 
                  NVL(PCEST2.CUSTOREP, 0))) CUSTOPROXIMACOMPRA_2, 
       MAX(NVL(PCPRODUT.CUSTOFORNEC, 0)) CUSTOFORNEC_2, 
       (CASE 
         WHEN PARAMETROS.PRECOPOREMBALAGEM = 'S' THEN 
           MAX(NVL((SELECT NVL(PCEMBALAGEM.PVENDA, 0) 
                  FROM PCEMBALAGEM 
       	        WHERE PCEMBALAGEM.CODFILIAL = PCEST2.CODFILIAL 
                   AND PCEMBALAGEM.CODPROD = PCEST2.CODPROD 
                   AND PCEMBALAGEM.QTUNIT = 1 AND ROWNUM = 1), 0)) 
         ELSE 
           MAX(NVL((SELECT NVL(PCTABPR.PVENDA,0) 
                  FROM PCTABPR 
       	        WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
                   AND PCTABPR.NUMREGIAO = 2), 0)) 
       END) AS PVENDA_2, 
       PCPRODUT.CODEPTO, 
       PCDEPTO.DESCRICAO DEPARTAMENTO, 
       PCPRODUT.CODSEC, 
       PCPRODUT.OBS2, 
       PCSECAO.DESCRICAO SECAO, 
       PCPRODUT.CODFORNEC, 
       PCFORNEC.CODFORNECPRINC, 
       PCFORNEC.FANTASIA, 
       PCFORNEC.FORNECEDOR, 
       PCPRODUT.CODFAB, 
       PCPRODUT.NBM, 
       MAX((CASE 
             WHEN (NVL(PCPRODUT.SUGVENDA, 0) <= 0) THEN 
              NVL(PCCONSUM.SUGVENDA, 3) 
            ELSE 
              NVL(PCPRODUT.SUGVENDA, 0) 
            END)) SUGVENDA, 
       AVG(NVL((SELECT NVL(PCREGIAO.PERFRETEESPECIAL, 0) 
              FROM PCTABPR, 
                   PCREGIAO 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO 
               AND PCTABPR.NUMREGIAO = 2 ), 0)) PERFRETEESPECIAL, 
       AVG(NVL((SELECT NVL(PCREGIAO.PERFRETETERCEIROS, 0) 
              FROM PCTABPR, 
                   PCREGIAO 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO  
               AND PCTABPR.NUMREGIAO = 2 ), 0)) PERFRETETERCEIROS, 
       MAX(NVL((SELECT NVL(PCTRIBUT.TIPOCALCULOGNRETAB, 'P') 
              FROM PCTABPR, 
                   PCTRIBUT 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.CODST    = PCTRIBUT.CODST 
               AND PCTABPR.NUMREGIAO = 2 ), 'P')) TIPOCALCULOGNRETAB, 
       MAX(NVL((SELECT NVL(PCTRIBUT.USAPMCBASEST, 'N') 
              FROM PCTABPR, 
                   PCTRIBUT 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.CODST    = PCTRIBUT.CODST 
               AND PCTABPR.NUMREGIAO = 2 ), 'N')) USAPMCBASEST, 
       MAX(NVL((SELECT NVL(PCTRIBUT.USAVALORULTENTBASEST, 'N') 
              FROM PCTABPR, 
                   PCTRIBUT 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.CODST    = PCTRIBUT.CODST 
               AND PCTABPR.NUMREGIAO = 2 ), 'N')) USAVALORULTENTBASEST, 
       MAX(NVL((SELECT NVL(PCTRIBUT.USAVALORULTENTBASEST2, 'N') 
              FROM PCTABPR, 
                   PCTRIBUT 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.CODST    = PCTRIBUT.CODST 
               AND PCTABPR.NUMREGIAO = 2 ), 'N')) USAVALORULTENTBASEST2, 
       MAX(NVL(PCPRODUT.FRETEESPECIAL,'N')) FRETEESPECIAL, 
       AVG(NVL(PCPRODUT.PCOMREP1, 0)) PCOMREP1, 
       SUM(NVL((SELECT NVL(PCTABPR.PVENDA, 0) 
              FROM PCTABPR, 
                   PCREGIAO 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO 
               AND PCTABPR.NUMREGIAO = 2 ), 0)) PVENDA2, 
       AVG(NVL((SELECT NVL(PCREGIAO.VLFRETEKG, 0) 
              FROM PCTABPR, 
                   PCREGIAO 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO 
               AND PCTABPR.NUMREGIAO = 2 ), 0)) VLFRETEKG, 
       AVG(NVL((SELECT NVL(PCTRIBUT.CODICMTAB, 0) 
              FROM PCTABPR, 
                   PCTRIBUT 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.CODST    = PCTRIBUT.CODST 
               AND PCTABPR.NUMREGIAO = 2 ), 0)) CODICMTAB, 
       AVG(NVL((SELECT NVL(PCTABPR.MARGEM, 0) 
            FROM PCTABPR, PCREGIAO 
           WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
             AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO 
             AND PCTABPR.NUMREGIAO = 2 ), 0)) MARGEM, 
       MAX(NVL(PCPRODUT.PRECOFIXO, 'N')) PRECOFIXO, 
       SUM(NVL(PCEST2.CUSTOREAL, 0)) CUSTOREAL2, 
       SUM(NVL(PCEST2.CUSTOFIN, 0)) CUSTOFIN2, 
       SUM(NVL(PCEST2.CUSTOULTENT, 0)) CUSTOULTENT3, 
       SUM(NVL(PCEST2.CUSTOULTPEDCOMPRA, 0)) CUSTOULTPEDCOMPRA3, 
       SUM(NVL(PCEST2.CUSTOULTENTFIN, 0)) CUSTOULTENTFIN3, 
       SUM(DECODE(PARAMETROS.USAPOLITICACOMERCIALPRODFILIAL, 
                  'P', 
                  DECODE(PARAMETROS.USANEGFORNEC, 
                         'S', 
                         NVL(PCPRODUT.CUSTOPROXIMACOMPRA, 0), 
                         NVL(PCPRODUT.CUSTOPROXIMACOMPRA, 0)), 
                  DECODE(PARAMETROS.USANEGFORNEC, 
                         'S', 
                         NVL(PCEST2.CUSTOPROXIMACOMPRA, 0), 
                         NVL(PCEST2.CUSTOPROXIMACOMPRA, 0)))) CUSTOPROXIMACOMPRA3, 
       SUM(DECODE(PARAMETROS.USAPOLITICACOMERCIALPRODFILIAL, 
                  'P', 
                  NVL(PCPRODUT.CUSTOFORNEC, 0), 
                  NVL(PCEST2.CUSTOFORNEC, 0))) CUSTOFORNEC3, 
       SUM(NVL((SELECT NVL(PCTRIBUT.PERDESCCUSTO, 0) 
            FROM PCTABPR, PCTRIBUT 
           WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
             AND PCTABPR.CODST    = PCTRIBUT.CODST 
             AND PCTABPR.NUMREGIAO = 2 ), 0)) PERDESCCUSTO, 
       MAX(NVL((SELECT NVL(PCTABPR.DESCONTAFRETE, 'N') 
            FROM PCTABPR, PCREGIAO 
           WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
             AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO 
             AND PCTABPR.NUMREGIAO = 2 ), 'N')) DESCONTAFRETE, 
       SUM(NVL((SELECT NVL(PCTABPR.PFRETE, 0) 
            FROM PCTABPR, PCREGIAO 
           WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
             AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO 
             AND PCTABPR.NUMREGIAO = 2 ), 0)) PFRETE, 
       0 VLRMZEROUNIT 
, sum(PCEST2.QTPENDENTE) QTPENDENTE 
, sum(PCEST2.QTBLOQUEADA) QTBLOQUEADA 
, sum(PCEST2.QTRESERV) QTRESERV 
, sum(PCEST2.QTESTGER) QTESTGER 
  FROM PCPRODUT, 
       PCEST2, 
       PCFORNEC, 
       PCMARCA, 
       PCLINHAPROD, 
       PCDEPTO, 
       PCSECAO, 
       PCCONSUM, 
       PARAMETROS 
 WHERE PCPRODUT.CODPROD  = PCEST2.CODPROD 
   AND PCPRODUT.CODMARCA = PCMARCA.CODMARCA(+) 
   AND PCPRODUT.CODLINHAPROD = PCLINHAPROD.CODLINHA(+) 
   AND PARAMETROS.CODIGO = PCEST2.CODFILIAL 
 AND PCPRODUT.DTEXCLUSAO IS NULL 
   AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO                                                       
   AND PCPRODUT.CODSEC = PCSECAO.CODSEC(+)                                                      
   AND NVL(PCDEPTO.TIPOMERC, 'XX') NOT IN ('IM','CI')                                     
   AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC                                                  
 GROUP BY --ADDGROUPFILIAL 
          PARAMETROS.USAPOLITICACOMERCIALPRODFILIAL, 
          PARAMETROS.PRECOPOREMBALAGEM, 
          PCPRODUT.CODPROD, 
          NVL(PCPRODUT.DESCRICAO,''), 
          PCPRODUT.NUMORIGINAL, 
          NVL(PCPRODUT.EMBALAGEM, ''), 
          PCPRODUT.CODEPTO, 
          PCDEPTO.DESCRICAO, 
          PCPRODUT.CODSEC, 
          PCPRODUT.OBS2, 
          PCSECAO.DESCRICAO, 
          PCPRODUT.CODFORNEC, 
          PCFORNEC.FORNECEDOR, 
          PCFORNEC.FANTASIA, 
          PCFORNEC.CODFORNECPRINC, 
          PCPRODUT.CODFAB, 
          PCPRODUT.QTUNITCX, 
          NVL(PCMARCA.MARCA,''), 
          PCLINHAPROD.DESCRICAO, 
          PCPRODUT.CODMARCA, 
          PCPRODUT.CODLINHAPROD, 
          PCPRODUT.CLASSE, 
          PCPRODUT.CLASSEVENDA, 
          PCPRODUT.NBM 
 ) A 
ORDER BY
CODPROD
----------------------------------
Timestamp: 08:24:58.347
--grid 
WITH PARAMETROS AS 
 (SELECT CODIGO, 
         NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('BLOQUEIAVENDAESTPENDENTE', 
                                           PCFILIAL.CODIGO), 
             PCCONSUM.BLOQUEIAVENDAESTPENDENTE) BLOQUEIAVENDAESTPENDENTE, 
         NVL(PCFILIAL.PRECOPOREMBALAGEM, PCCONSUM.PRECOPOREMBALAGEM) PRECOPOREMBALAGEM, 
         NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('USAPOLITICACOMERCIALPRODFILIAL'), 
                 'P') USAPOLITICACOMERCIALPRODFILIAL, 
         NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('CON_USANEGFORNEC'), 'N') USANEGFORNEC 
    FROM PCFILIAL, 
         PCCONSUM 
   WHERE CODIGO <> '99' 
   AND CODIGO IN('2')
     AND DTEXCLUSAO IS NULL), 
 PCEST2 AS ( 
    SELECT PCEST.DTULTFAT, PCEST.QTESTGER, PCEST.QTRESERV, PCEST.QTBLOQUEADA,PCEST.QTPENDENTE, PCEST.CUSTOULTENT, 
           PCEST.CODFILIAL, PCEST.CODPROD, PCEST.DTULTENT, PCEST.DTULTSAIDA, PCEST.CUSTOFIN, PCEST.CUSTOREP, 
           PCEST.CUSTOREAL, PCEST.CUSTOPROXIMACOMPRA, PCEST.VALORULTENT, PCEST.CUSTOULTPEDCOMPRA, 
           PCEST.CUSTOULTENTFIN, PCEST.CUSTOFORNEC, PCEST.QTULTENT 
    FROM PCEST, PARAMETROS 
    WHERE PCEST.CODFILIAL = PARAMETROS.CODIGO 
 AND PCEST.CODFILIAL IN ('2')
) 
 select DISTINCT A.* from (  
SELECT DISTINCT 
       PCPRODUT.CODPROD,
       NVL(PCPRODUT.DESCRICAO,'') DESCRICAO, 
       NVL(PCPRODUT.QTUNITCX,0) QTUNITCX, 
       NVL(PCMARCA.MARCA,'') MARCA, 
       NVL(PCLINHAPROD.DESCRICAO,'') LINHAPROD, 
       PCPRODUT.CODMARCA, 
       NVL(PCPRODUT.CODLINHAPROD,0) CODLINHA, 
       NVL(PCPRODUT.EMBALAGEM, '') EMBALAGEM, 
       NVL(PCPRODUT.CLASSE, '') CLASSE, 
       MAX(PCEST2.DTULTFAT)DTULTFAT, 
       NVL(PCPRODUT.CLASSEVENDA, '') CLASSEVENDA,
       PCPRODUT.NUMORIGINAL, 
       PARAMETROS.PRECOPOREMBALAGEM, 
       SUM(PCEST2.QTULTENT) QTULTENT, 
       SUM(PCEST2.QTESTGER / DECODE(NVL(PCPRODUT.QTUNITCX,0), 0, 1, PCPRODUT.QTUNITCX)) QTESTOQUECX,
       SUM(PCEST2.QTESTGER) QTESTOQUE, 
       SUM(PCEST2.CUSTOULTENT * PCEST2.QTESTGER) CUSTOULTENT2,
       SUM(((PCEST2.QTESTGER) * (PCPRODUT.PESOLIQ))) PESOLIQ, 
       SUM(NVL(PCEST2.QTESTGER,0) * NVL(PCEST2.CUSTOREP,0)) VLCUSTOREP, 
       SUM(NVL(PCEST2.QTESTGER,0) * DECODE(PARAMETROS.USANEGFORNEC, 
                                          'S', 
                                          NVL(PCPRODUT.CUSTOPROXIMACOMPRA, 0), 
                                          NVL(PCPRODUT.CUSTOREP, 0))) VLCUSTOPROX, 
       SUM(NVL(PCEST2.QTESTGER, 0) * DECODE(PARAMETROS.USAPOLITICACOMERCIALPRODFILIAL, 
                                           'P', 
                                           DECODE(PARAMETROS.USANEGFORNEC, 
                                                  'S', 
                                                  NVL(PCPRODUT.CUSTOPROXIMACOMPRA, 0), 
                                                  NVL(PCPRODUT.CUSTOREP, 0)), 
                                           DECODE(PARAMETROS.USANEGFORNEC, 
                                                  'S', 
                                                  NVL(PCEST2.CUSTOPROXIMACOMPRA, 0), 
                                                  NVL(PCEST2.CUSTOREP, 0)))) VLCUSTOPROXPARAM, 
       SUM(NVL(PCEST2.QTESTGER,0) * NVL(PCEST2.CUSTOFIN,0)) VLCUSTOFIN, 
       SUM(NVL(PCEST2.QTESTGER,0) * NVL(PCEST2.CUSTOULTENT,0)) CUSTOULTENT, 
       SUM(NVL(PCEST2.QTESTGER,0) * NVL(PCEST2.VALORULTENT,0)) VALORULTENT, 
       SUM(NVL(PCEST2.QTESTGER,0) * NVL(PCEST2.CUSTOREAL,0)) VLCUSTOREAL, 
       SUM(NVL(PCEST2.QTESTGER, 0) * NVL(PCEST2.CUSTOULTPEDCOMPRA, 0)) CUSTOULTPEDCOMPRA, 
       SUM(NVL(PCEST2.QTESTGER, 0) * NVL(PCEST2.CUSTOULTENTFIN, 0)) CUSTOULTENTFIN, 
       SUM(NVL(PCEST2.QTESTGER, 0) * DECODE(PARAMETROS.USANEGFORNEC, 
                                           'S', 
                                           NVL(PCEST2.CUSTOPROXIMACOMPRA, 0), 
                                           NVL(PCEST2.CUSTOREP, 0))) CUSTOPROXIMACOMPRA, 
       SUM(NVL(PCEST2.QTESTGER, 0) * NVL(PCPRODUT.CUSTOFORNEC, 0)) CUSTOFORNEC, 
       (CASE 
         WHEN PARAMETROS.PRECOPOREMBALAGEM = 'S' THEN 
          (SUM(NVL(PCEST2.QTESTGER, 0) * 
               NVL((SELECT NVL(PCEMBALAGEM.PVENDA, 0) 
                FROM PCEMBALAGEM 
                WHERE PCEMBALAGEM.CODFILIAL = PCEST2.CODFILIAL 
                AND (PCEMBALAGEM.CODPROD = PCEST2.CODPROD) 
                AND PCEMBALAGEM.QTUNIT = 1 
                AND ROWNUM = 1), 0))) 
         ELSE 
          (SUM(NVL(PCEST2.QTESTGER, 0) * 
               NVL((SELECT NVL(PCTABPR.PVENDA, 0) 
                FROM PCTABPR 
                WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
                AND (PCTABPR.NUMREGIAO = 2)), 0))) 
       END) VLPVENDA, 
       (CASE 
         WHEN PARAMETROS.PRECOPOREMBALAGEM = 'S' THEN 
          (SUM(NVL(PCEST2.QTESTGER, 0) * 
               NVL((SELECT NVL(PCEMBALAGEM.PTABELA, 0) 
                  FROM PCEMBALAGEM 
                 WHERE PCEMBALAGEM.CODFILIAL = PCEST2.CODFILIAL 
                   AND (PCEMBALAGEM.CODPROD = PCEST2.CODPROD) 
                   AND PCEMBALAGEM.QTUNIT = 1 
                   AND ROWNUM = 1), 0))) 
         ELSE 
          (SUM(NVL(PCEST2.QTESTGER, 0) * 
               NVL((SELECT NVL(PCTABPR.PTABELA, 0) 
                  FROM PCTABPR 
                 WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
                   AND (PCTABPR.NUMREGIAO = 2)), 0))) 
       END) PTABELA, 
       MAX(PCEST2.DTULTENT) DTULTENT, 
       MAX(PCEST2.DTULTSAIDA) DTULTSAIDA, 
       MAX(NVL(PCEST2.CUSTOFIN ,0)) AS CUSTOFIN_2, 
       MAX(NVL(PCEST2.CUSTOREP ,0)) AS CUSTOREP_2, 
       MAX(NVL(PCEST2.CUSTOREAL,0)) AS CUSTOREAL_2, 
       MAX(NVL(PCEST2.CUSTOULTENT,0)) AS CUSTOULTENT_2, 
       MAX(DECODE(PARAMETROS.USANEGFORNEC, 
                  'S', 
                  NVL(PCPRODUT.CUSTOPROXIMACOMPRA, 0), 
                  NVL(PCPRODUT.CUSTOREP, 0))) AS CUSTOPROX_2, 
       MAX(DECODE(PARAMETROS.USAPOLITICACOMERCIALPRODFILIAL, 
                  'P', 
                  DECODE(PARAMETROS.USANEGFORNEC, 
                         'S', 
                         NVL(PCPRODUT.CUSTOPROXIMACOMPRA, 0), 
                         NVL(PCPRODUT.CUSTOREP, 0)), 
                  DECODE(PARAMETROS.USANEGFORNEC, 
                         'S', 
                         NVL(PCEST2.CUSTOPROXIMACOMPRA, 0), 
                         NVL(PCEST2.CUSTOREP, 0)))) AS CUSTOPROXPARAM_2, 
       MAX(NVL(PCEST2.VALORULTENT,0)) AS VALORULTENT_2, 
       MAX(NVL(PCEST2.CUSTOULTPEDCOMPRA, 0)) CUSTOULTPEDCOMPRA_2, 
       MAX(NVL(PCEST2.CUSTOULTENTFIN, 0)) CUSTOULTENTFIN_2, 
       MAX(DECODE(PARAMETROS.USANEGFORNEC, 
                  'S', 
                  NVL(PCEST2.CUSTOPROXIMACOMPRA, 0), 
                  NVL(PCEST2.CUSTOREP, 0))) CUSTOPROXIMACOMPRA_2, 
       MAX(NVL(PCPRODUT.CUSTOFORNEC, 0)) CUSTOFORNEC_2, 
       (CASE 
         WHEN PARAMETROS.PRECOPOREMBALAGEM = 'S' THEN 
           MAX(NVL((SELECT NVL(PCEMBALAGEM.PVENDA, 0) 
                  FROM PCEMBALAGEM 
       	        WHERE PCEMBALAGEM.CODFILIAL = PCEST2.CODFILIAL 
                   AND PCEMBALAGEM.CODPROD = PCEST2.CODPROD 
                   AND PCEMBALAGEM.QTUNIT = 1 AND ROWNUM = 1), 0)) 
         ELSE 
           MAX(NVL((SELECT NVL(PCTABPR.PVENDA,0) 
                  FROM PCTABPR 
       	        WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
                   AND PCTABPR.NUMREGIAO = 2), 0)) 
       END) AS PVENDA_2, 
       PCPRODUT.CODEPTO, 
       PCDEPTO.DESCRICAO DEPARTAMENTO, 
       PCPRODUT.CODSEC, 
       PCPRODUT.OBS2, 
       PCSECAO.DESCRICAO SECAO, 
       PCPRODUT.CODFORNEC, 
       PCFORNEC.CODFORNECPRINC, 
       PCFORNEC.FANTASIA, 
       PCFORNEC.FORNECEDOR, 
       PCPRODUT.CODFAB, 
       PCPRODUT.NBM, 
       MAX((CASE 
             WHEN (NVL(PCPRODUT.SUGVENDA, 0) <= 0) THEN 
              NVL(PCCONSUM.SUGVENDA, 3) 
            ELSE 
              NVL(PCPRODUT.SUGVENDA, 0) 
            END)) SUGVENDA, 
       AVG(NVL((SELECT NVL(PCREGIAO.PERFRETEESPECIAL, 0) 
              FROM PCTABPR, 
                   PCREGIAO 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO 
               AND PCTABPR.NUMREGIAO = 2 ), 0)) PERFRETEESPECIAL, 
       AVG(NVL((SELECT NVL(PCREGIAO.PERFRETETERCEIROS, 0) 
              FROM PCTABPR, 
                   PCREGIAO 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO  
               AND PCTABPR.NUMREGIAO = 2 ), 0)) PERFRETETERCEIROS, 
       MAX(NVL((SELECT NVL(PCTRIBUT.TIPOCALCULOGNRETAB, 'P') 
              FROM PCTABPR, 
                   PCTRIBUT 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.CODST    = PCTRIBUT.CODST 
               AND PCTABPR.NUMREGIAO = 2 ), 'P')) TIPOCALCULOGNRETAB, 
       MAX(NVL((SELECT NVL(PCTRIBUT.USAPMCBASEST, 'N') 
              FROM PCTABPR, 
                   PCTRIBUT 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.CODST    = PCTRIBUT.CODST 
               AND PCTABPR.NUMREGIAO = 2 ), 'N')) USAPMCBASEST, 
       MAX(NVL((SELECT NVL(PCTRIBUT.USAVALORULTENTBASEST, 'N') 
              FROM PCTABPR, 
                   PCTRIBUT 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.CODST    = PCTRIBUT.CODST 
               AND PCTABPR.NUMREGIAO = 2 ), 'N')) USAVALORULTENTBASEST, 
       MAX(NVL((SELECT NVL(PCTRIBUT.USAVALORULTENTBASEST2, 'N') 
              FROM PCTABPR, 
                   PCTRIBUT 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.CODST    = PCTRIBUT.CODST 
               AND PCTABPR.NUMREGIAO = 2 ), 'N')) USAVALORULTENTBASEST2, 
       MAX(NVL(PCPRODUT.FRETEESPECIAL,'N')) FRETEESPECIAL, 
       AVG(NVL(PCPRODUT.PCOMREP1, 0)) PCOMREP1, 
       SUM(NVL((SELECT NVL(PCTABPR.PVENDA, 0) 
              FROM PCTABPR, 
                   PCREGIAO 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO 
               AND PCTABPR.NUMREGIAO = 2 ), 0)) PVENDA2, 
       AVG(NVL((SELECT NVL(PCREGIAO.VLFRETEKG, 0) 
              FROM PCTABPR, 
                   PCREGIAO 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO 
               AND PCTABPR.NUMREGIAO = 2 ), 0)) VLFRETEKG, 
       AVG(NVL((SELECT NVL(PCTRIBUT.CODICMTAB, 0) 
              FROM PCTABPR, 
                   PCTRIBUT 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.CODST    = PCTRIBUT.CODST 
               AND PCTABPR.NUMREGIAO = 2 ), 0)) CODICMTAB, 
       AVG(NVL((SELECT NVL(PCTABPR.MARGEM, 0) 
            FROM PCTABPR, PCREGIAO 
           WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
             AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO 
             AND PCTABPR.NUMREGIAO = 2 ), 0)) MARGEM, 
       MAX(NVL(PCPRODUT.PRECOFIXO, 'N')) PRECOFIXO, 
       SUM(NVL(PCEST2.CUSTOREAL, 0)) CUSTOREAL2, 
       SUM(NVL(PCEST2.CUSTOFIN, 0)) CUSTOFIN2, 
       SUM(NVL(PCEST2.CUSTOULTENT, 0)) CUSTOULTENT3, 
       SUM(NVL(PCEST2.CUSTOULTPEDCOMPRA, 0)) CUSTOULTPEDCOMPRA3, 
       SUM(NVL(PCEST2.CUSTOULTENTFIN, 0)) CUSTOULTENTFIN3, 
       SUM(DECODE(PARAMETROS.USAPOLITICACOMERCIALPRODFILIAL, 
                  'P', 
                  DECODE(PARAMETROS.USANEGFORNEC, 
                         'S', 
                         NVL(PCPRODUT.CUSTOPROXIMACOMPRA, 0), 
                         NVL(PCPRODUT.CUSTOPROXIMACOMPRA, 0)), 
                  DECODE(PARAMETROS.USANEGFORNEC, 
                         'S', 
                         NVL(PCEST2.CUSTOPROXIMACOMPRA, 0), 
                         NVL(PCEST2.CUSTOPROXIMACOMPRA, 0)))) CUSTOPROXIMACOMPRA3, 
       SUM(DECODE(PARAMETROS.USAPOLITICACOMERCIALPRODFILIAL, 
                  'P', 
                  NVL(PCPRODUT.CUSTOFORNEC, 0), 
                  NVL(PCEST2.CUSTOFORNEC, 0))) CUSTOFORNEC3, 
       SUM(NVL((SELECT NVL(PCTRIBUT.PERDESCCUSTO, 0) 
            FROM PCTABPR, PCTRIBUT 
           WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
             AND PCTABPR.CODST    = PCTRIBUT.CODST 
             AND PCTABPR.NUMREGIAO = 2 ), 0)) PERDESCCUSTO, 
       MAX(NVL((SELECT NVL(PCTABPR.DESCONTAFRETE, 'N') 
            FROM PCTABPR, PCREGIAO 
           WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
             AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO 
             AND PCTABPR.NUMREGIAO = 2 ), 'N')) DESCONTAFRETE, 
       SUM(NVL((SELECT NVL(PCTABPR.PFRETE, 0) 
            FROM PCTABPR, PCREGIAO 
           WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
             AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO 
             AND PCTABPR.NUMREGIAO = 2 ), 0)) PFRETE, 
       0 VLRMZEROUNIT 
, sum(PCEST2.QTPENDENTE) QTPENDENTE 
, sum(PCEST2.QTBLOQUEADA) QTBLOQUEADA 
, sum(PCEST2.QTRESERV) QTRESERV 
, sum(PCEST2.QTESTGER) QTESTGER 
  FROM PCPRODUT, 
       PCEST2, 
       PCFORNEC, 
       PCMARCA, 
       PCLINHAPROD, 
       PCDEPTO, 
       PCSECAO, 
       PCCONSUM, 
       PARAMETROS 
 WHERE PCPRODUT.CODPROD  = PCEST2.CODPROD 
   AND PCPRODUT.CODMARCA = PCMARCA.CODMARCA(+) 
   AND PCPRODUT.CODLINHAPROD = PCLINHAPROD.CODLINHA(+) 
   AND PARAMETROS.CODIGO = PCEST2.CODFILIAL 
 AND PCPRODUT.DTEXCLUSAO IS NULL 
   AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO                                                       
   AND PCPRODUT.CODSEC = PCSECAO.CODSEC(+)                                                      
   AND NVL(PCDEPTO.TIPOMERC, 'XX') NOT IN ('IM','CI')                                     
   AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC                                                  
 GROUP BY PCEST2.CODFILIAL, 
          PARAMETROS.USAPOLITICACOMERCIALPRODFILIAL, 
          PARAMETROS.PRECOPOREMBALAGEM, 
          PCPRODUT.CODPROD, 
          NVL(PCPRODUT.DESCRICAO,''), 
          PCPRODUT.NUMORIGINAL, 
          NVL(PCPRODUT.EMBALAGEM, ''), 
          PCPRODUT.CODEPTO, 
          PCDEPTO.DESCRICAO, 
          PCPRODUT.CODSEC, 
          PCPRODUT.OBS2, 
          PCSECAO.DESCRICAO, 
          PCPRODUT.CODFORNEC, 
          PCFORNEC.FORNECEDOR, 
          PCFORNEC.FANTASIA, 
          PCFORNEC.CODFORNECPRINC, 
          PCPRODUT.CODFAB, 
          PCPRODUT.QTUNITCX, 
          NVL(PCMARCA.MARCA,''), 
          PCLINHAPROD.DESCRICAO, 
          PCPRODUT.CODMARCA, 
          PCPRODUT.CODLINHAPROD, 
          PCPRODUT.CLASSE, 
          PCPRODUT.CLASSEVENDA, 
          PCPRODUT.NBM 
 ) A
WHERE A.CODPROD = :CODPROD  
ORDER BY
CODPROD
CODPROD = -1
----------------------------------
Timestamp: 08:25:09.283
SELECT PCTABPR.CODPROD                                     
    , PCTABPR.NUMREGIAO                                    
    , PCTABPR.ROWID RID                                    
    , PCTABPR.ROWID                                        
    , NVL(PCTABPR.VLIPI, 0) VLIPI                          
    , NVL(PCTABPR.VLIPITAB, 0) VLIPITAB                    
    , PCREGIAO.REGIAO                                      
    , 0                 PRCONCORRENTE                      
    , 'N'             ALTERADO                           
    , SYSDATE           DATASERVIDOR                       
    , NVL(PCTABPR.PVENDA,   0) PVENDA                      
    , NVL(PCTABPR.PVENDA1,  0) PVENDA1                     
    , NVL(PCTABPR.PVENDA2,  0) PVENDA2                     
    , NVL(PCTABPR.PVENDA3,  0) PVENDA3                     
    , NVL(PCTABPR.PVENDA4,  0) PVENDA4                     
    , NVL(PCTABPR.PVENDA5,  0) PVENDA5                     
    , NVL(PCTABPR.PVENDA6,  0) PVENDA6                     
    , NVL(PCTABPR.PVENDA7,  0) PVENDA7                     
    , NVL(PCTABPR.PVENDASEMIMPOSTO1,  0) PVENDASEMIMPOSTO1 
    , NVL(PCTABPR.PVENDASEMIMPOSTO2,  0) PVENDASEMIMPOSTO2 
    , NVL(PCTABPR.PVENDASEMIMPOSTO3,  0) PVENDASEMIMPOSTO3 
    , NVL(PCTABPR.PVENDASEMIMPOSTO4,  0) PVENDASEMIMPOSTO4 
    , NVL(PCTABPR.PVENDASEMIMPOSTO5,  0) PVENDASEMIMPOSTO5 
    , NVL(PCTABPR.PVENDASEMIMPOSTO6,  0) PVENDASEMIMPOSTO6 
    , NVL(PCTABPR.PVENDASEMIMPOSTO7,  0) PVENDASEMIMPOSTO7 
    , PCTABPR.FORMULA                                      
    , (CASE WHEN (NVL(PCPRODUT.SUGVENDA, 0) <= 0) THEN 1 ELSE NVL(PCPRODUT.SUGVENDA, 0) END) SUGVENDA 
    , NVL(PCTABPR.VLST,  0) VLST                                    
    , NVL(PCTABPR.VLSTTAB,  0) VLSTTAB                              
    , NVL(PCTABPR.VLFCPST,  0) VLFCPST                
    , NVL(PCTABPR.VLFCPSTTAB,  0) VLFCPSTTAB          
    , NVL(PCTABPR.PTABELA,  0) PTABELA                              
    , NVL(PCTABPR.PTABELA1, 0) PTABELA1                             
    , NVL(PCTABPR.PTABELA2, 0) PTABELA2                             
    , NVL(PCTABPR.PTABELA3, 0) PTABELA3                             
    , NVL(PCTABPR.PTABELA4, 0) PTABELA4                             
    , NVL(PCTABPR.PTABELA5, 0) PTABELA5                             
    , NVL(PCTABPR.PTABELA6, 0) PTABELA6                             
    , NVL(PCTABPR.PTABELA7, 0) PTABELA7                             
    , NVL(PCTABPR.PTABELASEMIMPOSTO1, 0) PTABELASEMIMPOSTO1         
    , NVL(PCTABPR.PTABELASEMIMPOSTO2, 0) PTABELASEMIMPOSTO2         
    , NVL(PCTABPR.PTABELASEMIMPOSTO3, 0) PTABELASEMIMPOSTO3         
    , NVL(PCTABPR.PTABELASEMIMPOSTO4, 0) PTABELASEMIMPOSTO4         
    , NVL(PCTABPR.PTABELASEMIMPOSTO5, 0) PTABELASEMIMPOSTO5         
    , NVL(PCTABPR.PTABELASEMIMPOSTO6, 0) PTABELASEMIMPOSTO6         
    , NVL(PCTABPR.PTABELASEMIMPOSTO7, 0) PTABELASEMIMPOSTO7         
    , NVL(PCTABPR.COTAITEM, 0) COTAITEM                             
    , NVL(PCTABPR.PVENDAATAC,   0) PVENDAATAC                       
    , NVL(PCTABPR.PVENDAATAC1,  0) PVENDAATAC1                      
    , NVL(PCTABPR.PVENDAATAC2,  0) PVENDAATAC2                      
    , NVL(PCTABPR.PVENDAATAC3,  0) PVENDAATAC3                      
    , NVL(PCTABPR.PVENDAATAC4,  0) PVENDAATAC4                      
    , NVL(PCTABPR.PVENDAATAC5,  0) PVENDAATAC5                      
    , NVL(PCTABPR.PVENDAATAC6,  0) PVENDAATAC6                      
    , NVL(PCTABPR.PVENDAATAC7,  0) PVENDAATAC7                      
    , NVL(PCTABPR.PVENDAATACSEMIMPOSTO1,  0) PVENDAATACSEMIMPOSTO1  
    , NVL(PCTABPR.PVENDAATACSEMIMPOSTO2,  0) PVENDAATACSEMIMPOSTO2  
    , NVL(PCTABPR.PVENDAATACSEMIMPOSTO3,  0) PVENDAATACSEMIMPOSTO3  
    , NVL(PCTABPR.PVENDAATACSEMIMPOSTO4,  0) PVENDAATACSEMIMPOSTO4  
    , NVL(PCTABPR.PVENDAATACSEMIMPOSTO5,  0) PVENDAATACSEMIMPOSTO5  
    , NVL(PCTABPR.PVENDAATACSEMIMPOSTO6,  0) PVENDAATACSEMIMPOSTO6  
    , NVL(PCTABPR.PVENDAATACSEMIMPOSTO7,  0) PVENDAATACSEMIMPOSTO7  
    , NVL(PCTABPR.PTABELAATAC,  0) PTABELAATAC                      
    , NVL(PCTABPR.PTABELAATAC1, 0) PTABELAATAC1                     
    , NVL(PCTABPR.PTABELAATAC2, 0) PTABELAATAC2                     
    , NVL(PCTABPR.PTABELAATAC3, 0) PTABELAATAC3                     
    , NVL(PCTABPR.PTABELAATAC4, 0) PTABELAATAC4                     
    , NVL(PCTABPR.PTABELAATAC5, 0) PTABELAATAC5                     
    , NVL(PCTABPR.PTABELAATAC6, 0) PTABELAATAC6                     
    , NVL(PCTABPR.PTABELAATAC7, 0) PTABELAATAC7                     
    , NVL(PCTABPR.PTABELAATACSEMIMPOSTO1, 0) PTABELAATACSEMIMPOSTO1 
    , NVL(PCTABPR.PTABELAATACSEMIMPOSTO2, 0) PTABELAATACSEMIMPOSTO2 
    , NVL(PCTABPR.PTABELAATACSEMIMPOSTO3, 0) PTABELAATACSEMIMPOSTO3 
    , NVL(PCTABPR.PTABELAATACSEMIMPOSTO4, 0) PTABELAATACSEMIMPOSTO4 
    , NVL(PCTABPR.PTABELAATACSEMIMPOSTO5, 0) PTABELAATACSEMIMPOSTO5 
    , NVL(PCTABPR.PTABELAATACSEMIMPOSTO6, 0) PTABELAATACSEMIMPOSTO6 
    , NVL(PCTABPR.PTABELAATACSEMIMPOSTO7, 0) PTABELAATACSEMIMPOSTO7 
    , NVL(PCEST.VALORULTENT       , 0) VALORULTENT                  
    , FUNCOESCOMPRAS.VALORULTENTMEDIO(PCEST.CODPROD, PCEST.CODFILIAL,
NVL(GREATEST(NVL(PCEST.VLULTENTCONTSEMST,0),0), 0), NVL(PCTRIBUT.USAVLULTENTMEDIOBASEST, 'N')) VALORULTENTMEDIO     
    , NVL(PCEST.VLULTENTCONTSEMST, 0) VLULTENTCONTSEMST    
    , NVL(PCEST.CUSTONFSEMST, PCEST.VALORULTENT) CUSTONFSEMST                                                                                                      
    , NVL(PCEST.BASEICMSULTENT    , 0) BASEICMSULTENT                                                                                                              
  , NVL(PCEST.CUSTOREAL, 0) CUSTOREAL                                                                                                                                                                   
  , NVL(PCEST.CUSTOFIN, 0) CUSTOFIN                                                                                                                                                                     
  , NVL(PCEST.CUSTOULTENT, 0) CUSTOULTENT                                                                                                                                                               
  , NVL(PCEST.CUSTOULTPEDCOMPRA, 0) CUSTOULTPEDCOMPRA                                                                                                                                                   
  , NVL(PCEST.CUSTOULTENTFIN, 0) CUSTOULTENTFIN                                                                                                                                                         
  , DECODE(NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('USAPOLITICACOMERCIALPRODFILIAL'), 'P'), 'P', NVL(PCPRODUT.CUSTOPROXIMACOMPRA, 0), 
NVL(PCEST.CUSTOPROXIMACOMPRA, 0)) CUSTOPROXIMACOMPRA                          
  , DECODE(NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('USAPOLITICACOMERCIALPRODFILIAL'), 'P'), 'P', NVL(PCPRODUT.CUSTOFORNEC, 0), 
NVL(PCEST.CUSTOFORNEC, 0)) CUSTOFORNEC                                               
    , NVL(PCREGIAO.UF, PCFILIALREGIAO.UF) UF_REGICAO  
    , PCFILIALREGIAO.UF UF_FILIAL 
    , NVL(PCPRODUT.FRETEESPECIAL,'N') FRETEESPECIAL                                     
    , NVL(PCTABPR.PERDESCMAX, 0) PERDESCMAX                                               
    , NVL(PCTABPR.PERDESCMAXTAB, 0) PERDESCMAXTAB                                         
    , NVL(PCTABPR.POFERTA, 0) POFERTA                                                     
    , NVL(PCTABPR.POFERTATAB, 0) POFERTATAB                                               
    , NVL(PCTABPR.MARGEM, 0) MARGEM                                                       
    , NVL(PCTRIBUT.PERCDIFALIQUOTASTAB, 0) PERCDIFALIQUOTASTAB                            
    , NVL(PCTRIBUT.USAVALORULTENTBASEST2, 'N') USAVALORULTENTBASEST2                    
    , NVL(PCTRIBUT.USAVALORULTENTBASEST, 'N')  USAVALORULTENTBASEST                     
    , NVL(PCTRIBUT.USAVLULTENTMEDIOBASEST, 'N') USAVLULTENTMEDIOBASEST                  
    , NVL(PCTRIBUT.COMPARARPAUTACOMST, 'N') COMPARARPAUTACOMST                          
    , NVL(PCTABPR.PRECOANTERIORATAC, 0) PRECOANTERIORATAC                                 
    , PCTABPR.DESCONTAFRETE                                                               
    , PCTABPR.DTULTALTPVENDA                                                              
    , NVL(PCPRODUT.QTMINIMAATACADO,0) QTMINIMAATACADO                                     
     , NVL(PCPRODUT.PCOMEXT1, 0) PCOMEXT1 
     , NVL(PCPRODUT.PCOMINT1, 0) PCOMINT1 
     , NVL(PCPRODUT.PCOMREP1, 0) PCOMREP1 
    , NVL(PCTABPR.EXCLUIDO,'N') EXCLUIDO                                                
    , NVL(PCTRIBUT.CODICMANTECIPADO, 0) CODICMANTECIPADO                                  
    , NVL(PCTRIBUT.CODICMTAB, 0) CODICMTAB                                                
    , NVL(PCTRIBUT.PERDESCCUSTO, 0) PERDESCCUSTO                                          
    , NVL(PCTABPR.PFRETE, 0) PFRETE                                                       
    , NVL(PCTRIBUT.PERDESTAB, 0) PERDESTAB                                                
    , DECODE( NVL(PCTRIBUT.UTILIZARSTFONTEPRECIFIC,'N'), 'S', NVL(PCTRIBUT.IVAFONTE,0), NVL(PCTRIBUT.IVATAB, 0) ) IVATAB                         
    , DECODE( NVL(PCTRIBUT.UTILIZARSTFONTEPRECIFIC,'N'), 'S', NVL(PCTRIBUT.ALIQICMS1FONTE,0), NVL(PCTRIBUT.ALIQICMS1TAB, 0) ) 
ALIQICMS1TAB       
    , DECODE( NVL(PCTRIBUT.UTILIZARSTFONTEPRECIFIC,'N'), 'S', NVL(PCTRIBUT.ALIQICMS2FONTE,0), NVL(PCTRIBUT.ALIQICMS2TAB, 0) ) 
ALIQICMS2TAB       
    , DECODE( NVL(PCTRIBUT.UTILIZARSTFONTEPRECIFIC,'N'), 'S', NVL(PCTRIBUT.PERCBASEREDSTFONTE,0), NVL(PCTRIBUT.PERCBASEREDST, 
0) ) PERCBASEREDST 
    , DECODE( NVL(PCTRIBUT.UTILIZARSTFONTEPRECIFIC,'N'), 'S', NVL(PCTRIBUT.PAUTAFONTE,0), NVL(PCTRIBUT.PAUTATAB, 0) )  PAUTATAB                  
    , NVL(PCTRIBUT.TIPOCALCULOGNRETAB, 'P') TIPOCALCULOGNRETAB                          
    , NVL(PCTABPR.INDICEPRECO, 1) INDICEPRECO                                             
    , PCTRIBUT.CODST                                                                      
    , NVL(PCPRODUT.PRECOFIXO, 'N') PRECOFIXO                                           
    , NVL(PCPRODUT.PESOBRUTO, 0) PESOBRUTO                                               
    , NVL(PCPRODUT.PERCIPIVENDA,0) PERCIPIVENDA                                          
    , NVL(PCTABPR.MARGEM_ESP, 0) MARGEM_ESP                                               
    , NVL(PCREGIAO.VLFRETEKG, 0) VLFRETEKG                                                
    , NVL(PCREGIAO.PERFRETE, 0) PERFRETE                                                  
    , NVL(PCREGIAO.PERFRETEESPECIAL, 0) PERFRETEESPECIAL                                  
    , NVL(PCREGIAO.PERFRETETERCEIROS, 0) PERFRETETERCEIROS                                
    , PCREGIAO.REGIAO                                                                     
    , PCTABPR.COTAITEMTAB                                                                 
    , PCTABPR.PERDESCMAXTABBALCAO                                                         
    , PCTABPR.PERDESCMAXBALCAO                                                            
    , PCTABPR.PRECOMINIMOTABELA                                                           
    , 0 MPRECOMINTABELA                                                                   
    , PCTABPR.PRECOMINIMOVENDA                                                            
    , DECODE(PCTRIBUT.USABASEICMSREDUZIDA, 'S', NVL(PCTRIBUT.PERCBASERED,0), 0) PERCBASERED 
    , NVL(PCTRIBUT.PERCBASERED,0) PERCBASEREDFECP 
    , NVL(PCTABPR.PERCACRESCIMOFRETE,0) PERCACRESCIMOFRETE                                
    , NVL(PCTABPR.PERDESCFOB,0) PERDESCFOB                                                
    , PCTABPR.DTEMISSAOETIQ                                                               
    , NVL(PCREGIAO.ATUALIZAF11,'S') ATUALIZAF11                                         
    , NVL(PCTABPR.VLACRESFRETEKG,0) VLACRESFRETEKG                                        
    , NVL(PCPRODUT.PERCIPIVENDATAB,0) PERCIPIVENDATAB
    , NVL(PCPRODUT.VLPAUTAIPIVENDATAB,0) VLPAUTAIPIVENDATAB
    , NVL(PCPRODUT.VLIPIPORKGVENDATAB,0) VLIPIPORKGVENDATAB
    , NVL(PCTRIBUT.USAPMCBASEST, 'N') USAPMCBASEST                                      
    , NVL(PCPRODUT.PRECOMAXCONSUMTAB, 0) PRECOMAXCONSUMTAB                                
    , NVL(PCPRODUT.PRECOMAXCONSUM, 0) PRECOMAXCONSUM                                      
             , 0 TAXA0             
             , 0 TAXA7             
             , 0 TAXA14            
             , 0 TAXA21            
             , 0 TAXA28            
             , 0 TAXA35            
             , 0 TAXA42            
    , NVL(PCTABPR.CUSTOPRECIFICTAB, 0) CUSTOPRECIFICTAB 
    , TO_CHAR(105) ROTINA                                                                          
    , 105 MATRICULA  
    , NVL(PCPRODFILIAL.INDESCALARELEVANTE, 'S') INDESCALARELEVANTE 
    , NVL(PCTRIBUT.INDICECOMPBASESTMG, 0) INDICECOMPBASESTMG 
    , NVL(PCTRIBUT.PERCBASESTRJ, 0)PERCBASESTRJ       
    , NVL(PCTABPR.UTILIZARIOLOG, 'N') UTILIZARIOLOG 
    , NVL(PCTRIBUT.ALIQICMSFECP, 0) ALIQICMSFECP      
    , NVL(PCTRIBUT.PERACRESCIMOFUNCEP, 0) PERACRESCIMOFUNCEP 
    , PCTRIBUT.FORMULAPVENDA CODFORMULA 
    , NVL(PCTRIBUT.UTILIZAMOTORCALCULO, 'N') UTILIZAMOTORCALCULO 
    , NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('CALCULARFECPSTVENDA', PCEST.CODFILIAL), 'N') CALCULARFECPSTVENDA 
    , DECODE(PCFILIALREGIAO.UF, NVL(PCREGIAO.UF, PCFILIALREGIAO.UF), PCTRIBUT.VLPAUTAICMSEST, PCTRIBUT.VLPAUTAICMSINTEREST) 
PAUTAICMS 
   FROM PCTABPR                                                                                
      , PCREGIAO                                                                               
      , PCTRIBUT                                                                               
      , PCPRODUT                                                                               
      , PCEST                                                                                  
      , PCPRODFILIAL                                                                           
      , PCFILIAL PCFILIALREGIAO                                                                
  WHERE PCTABPR.CODST    = PCTRIBUT.CODST                                                     
  AND PCTABPR.CODPROD    = PCPRODUT.CODPROD                                                   
    AND PCTABPR.CODPROD      = PCEST.CODPROD                                                    
    AND PCEST.CODFILIAL     = PCFILIALREGIAO.CODIGO                                             
    AND PCEST.CODFILIAL   = PCPRODFILIAL.CODFILIAL                                              
    AND PCEST.CODPROD      = PCPRODFILIAL.CODPROD                                               
    AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO                                                 
    AND PCPRODUT.DTEXCLUSAO IS NULL                                                             
    AND ((PCREGIAO.STATUS NOT IN ('I')) OR (PCREGIAO.STATUS IS NULL))                         
    AND ((PCREGIAO.CODFILIAL = PCEST.CODFILIAL) OR (NVL(PCREGIAO.CODFILIAL, '99') = '99')) 
    AND PCTABPR.NUMREGIAO IN (2)                                             
    AND PCEST.CODFILIAL IN ('2')
 ORDER BY PCTABPR.NUMREGIAO