
--grid 
WITH PARAMETROS AS 
 (SELECT CODIGO, 
         NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('BLOQUEIAVENDAESTPENDENTE', 
                                           PCFILIAL.CODIGO), 
             PCCONSUM.BLOQUEIAVENDAESTPENDENTE) BLOQUEIAVENDAESTPENDENTE, 
         NVL(PCFILIAL.PRECOPOREMBALAGEM, PCCONSUM.PRECOPOREMBALAGEM) PRECOPOREMBALAGEM, 
         NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('USAPOLITICACOMERCIALPRODFILIAL'), 
                 'P') USAPOLITICACOMERCIALPRODFILIAL, 
         NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('CON_USANEGFORNEC'), 'N') USANEGFORNEC 
    FROM PCFILIAL, 
         PCCONSUM 
   WHERE CODIGO <> '99' 
   AND CODIGO IN('2')
     AND DTEXCLUSAO IS NULL), 
 PCEST2 AS ( 
    SELECT PCEST.DTULTFAT, PCEST.QTESTGER, PCEST.QTRESERV, PCEST.QTBLOQUEADA,PCEST.QTPENDENTE, PCEST.CUSTOULTENT, 
           PCEST.CODFILIAL, PCEST.CODPROD, PCEST.DTULTENT, PCEST.DTULTSAIDA, PCEST.CUSTOFIN, PCEST.CUSTOREP, 
           PCEST.CUSTOREAL, PCEST.CUSTOPROXIMACOMPRA, PCEST.VALORULTENT, PCEST.CUSTOULTPEDCOMPRA, 
           PCEST.CUSTOULTENTFIN, PCEST.CUSTOFORNEC, PCEST.QTULTENT 
    FROM PCEST, PARAMETROS 
    WHERE PCEST.CODFILIAL = PARAMETROS.CODIGO 
 AND PCEST.CODFILIAL IN ('2')
) 
 select DISTINCT A.* from (  
SELECT DISTINCT
       PCPRODUT.CODFORNEC,
       PCFORNEC.FORNECEDOR, 
       PCPRODUT.CODPROD,
       NVL(PCPRODUT.DESCRICAO,'') DESCRICAO, 

/*
       NVL(PCPRODUT.QTUNITCX,0) QTUNITCX, 
       NVL(PCMARCA.MARCA,'') MARCA, 
       NVL(PCLINHAPROD.DESCRICAO,'') LINHAPROD, 
       PCPRODUT.CODMARCA, 
       NVL(PCPRODUT.CODLINHAPROD,0) CODLINHA, 
       NVL(PCPRODUT.EMBALAGEM, '') EMBALAGEM, 
       NVL(PCPRODUT.CLASSE, '') CLASSE, 
       MAX(PCEST2.DTULTFAT)DTULTFAT, 
       NVL(PCPRODUT.CLASSEVENDA, '') CLASSEVENDA,
       PCPRODUT.NUMORIGINAL, 
       PARAMETROS.PRECOPOREMBALAGEM, 
       SUM(PCEST2.QTULTENT) QTULTENT, 
       SUM(PCEST2.QTESTGER / DECODE(NVL(PCPRODUT.QTUNITCX,0), 0, 1, PCPRODUT.QTUNITCX)) QTESTOQUECX,
       SUM(PCEST2.QTESTGER) QTESTOQUE, 
       SUM(PCEST2.CUSTOULTENT * PCEST2.QTESTGER) CUSTOULTENT2,
       SUM(((PCEST2.QTESTGER) * (PCPRODUT.PESOLIQ))) PESOLIQ, 
       SUM(NVL(PCEST2.QTESTGER,0) * NVL(PCEST2.CUSTOREP,0)) VLCUSTOREP, 
       SUM(NVL(PCEST2.QTESTGER,0) * DECODE(PARAMETROS.USANEGFORNEC, 
                                          'S', 
                                          NVL(PCPRODUT.CUSTOPROXIMACOMPRA, 0), 
                                          NVL(PCPRODUT.CUSTOREP, 0))) VLCUSTOPROX, 
       SUM(NVL(PCEST2.QTESTGER, 0) * DECODE(PARAMETROS.USAPOLITICACOMERCIALPRODFILIAL, 
                                           'P', 
                                           DECODE(PARAMETROS.USANEGFORNEC, 
                                                  'S', 
                                                  NVL(PCPRODUT.CUSTOPROXIMACOMPRA, 0), 
                                                  NVL(PCPRODUT.CUSTOREP, 0)), 
                                           DECODE(PARAMETROS.USANEGFORNEC, 
                                                  'S', 
                                                  NVL(PCEST2.CUSTOPROXIMACOMPRA, 0), 
                                                  NVL(PCEST2.CUSTOREP, 0)))) VLCUSTOPROXPARAM, 
       SUM(NVL(PCEST2.QTESTGER,0) * NVL(PCEST2.CUSTOFIN,0)) VLCUSTOFIN, 
       SUM(NVL(PCEST2.QTESTGER,0) * NVL(PCEST2.CUSTOULTENT,0)) CUSTOULTENT, 
       SUM(NVL(PCEST2.QTESTGER,0) * NVL(PCEST2.VALORULTENT,0)) VALORULTENT, 
       SUM(NVL(PCEST2.QTESTGER,0) * NVL(PCEST2.CUSTOREAL,0)) VLCUSTOREAL, 
       SUM(NVL(PCEST2.QTESTGER, 0) * NVL(PCEST2.CUSTOULTPEDCOMPRA, 0)) CUSTOULTPEDCOMPRA, 
       SUM(NVL(PCEST2.QTESTGER, 0) * NVL(PCEST2.CUSTOULTENTFIN, 0)) CUSTOULTENTFIN, 
       SUM(NVL(PCEST2.QTESTGER, 0) * DECODE(PARAMETROS.USANEGFORNEC, 
                                           'S', 
                                           NVL(PCEST2.CUSTOPROXIMACOMPRA, 0), 
                                           NVL(PCEST2.CUSTOREP, 0))) CUSTOPROXIMACOMPRA, 
       SUM(NVL(PCEST2.QTESTGER, 0) * NVL(PCPRODUT.CUSTOFORNEC, 0)) CUSTOFORNEC, 
*/

       (CASE 
         WHEN PARAMETROS.PRECOPOREMBALAGEM = 'S' THEN 
          (SUM(NVL(PCEST2.QTESTGER, 0) * 
               NVL((SELECT NVL(PCEMBALAGEM.PVENDA, 0) 
                FROM PCEMBALAGEM 
                WHERE PCEMBALAGEM.CODFILIAL = PCEST2.CODFILIAL 
                AND (PCEMBALAGEM.CODPROD = PCEST2.CODPROD) 
                AND PCEMBALAGEM.QTUNIT = 1 
                AND ROWNUM = 1), 0))) 
         ELSE 
          (SUM(NVL(PCEST2.QTESTGER, 0) * 
               NVL((SELECT NVL(PCTABPR.PVENDA, 0) 
                FROM PCTABPR 
                WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
                AND (PCTABPR.NUMREGIAO = 2)), 0))) 
       END) VLPVENDA,

SUM(NVL(PCEST2.QTESTGER,0) * NVL(PCEST2.CUSTOREAL,0)) VLCUSTOREAL,

/*
       (CASE 
         WHEN PARAMETROS.PRECOPOREMBALAGEM = 'S' THEN 
          (SUM(NVL(PCEST2.QTESTGER, 0) * 
               NVL((SELECT NVL(PCEMBALAGEM.PTABELA, 0) 
                  FROM PCEMBALAGEM 
                 WHERE PCEMBALAGEM.CODFILIAL = PCEST2.CODFILIAL 
                   AND (PCEMBALAGEM.CODPROD = PCEST2.CODPROD) 
                   AND PCEMBALAGEM.QTUNIT = 1 
                   AND ROWNUM = 1), 0))) 
         ELSE 
          (SUM(NVL(PCEST2.QTESTGER, 0) * 
               NVL((SELECT NVL(PCTABPR.PTABELA, 0) 
                  FROM PCTABPR 
                 WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
                   AND (PCTABPR.NUMREGIAO = 2)), 0))) 
       END) PTABELA, 
       MAX(PCEST2.DTULTENT) DTULTENT, 
       MAX(PCEST2.DTULTSAIDA) DTULTSAIDA, 
       MAX(NVL(PCEST2.CUSTOFIN ,0)) AS CUSTOFIN_2, 
       MAX(NVL(PCEST2.CUSTOREP ,0)) AS CUSTOREP_2, 
       MAX(NVL(PCEST2.CUSTOREAL,0)) AS CUSTOREAL_2, 
       MAX(NVL(PCEST2.CUSTOULTENT,0)) AS CUSTOULTENT_2, 
*/

       MAX(DECODE(PARAMETROS.USANEGFORNEC, 
                  'S', 
                  NVL(PCPRODUT.CUSTOPROXIMACOMPRA, 0), 
                  NVL(PCPRODUT.CUSTOREP, 0))) AS CUSTOPROX_2, 
       MAX(DECODE(PARAMETROS.USAPOLITICACOMERCIALPRODFILIAL, 
                  'P', 
                  DECODE(PARAMETROS.USANEGFORNEC, 
                         'S', 
                         NVL(PCPRODUT.CUSTOPROXIMACOMPRA, 0), 
                         NVL(PCPRODUT.CUSTOREP, 0)), 
                  DECODE(PARAMETROS.USANEGFORNEC, 
                         'S', 
                         NVL(PCEST2.CUSTOPROXIMACOMPRA, 0), 
                         NVL(PCEST2.CUSTOREP, 0)))) AS CUSTOPROXPARAM_2, 
       MAX(NVL(PCEST2.VALORULTENT,0)) AS VALORULTENT_2, 
       MAX(NVL(PCEST2.CUSTOULTPEDCOMPRA, 0)) CUSTOULTPEDCOMPRA_2, 
       MAX(NVL(PCEST2.CUSTOULTENTFIN, 0)) CUSTOULTENTFIN_2, 
       MAX(DECODE(PARAMETROS.USANEGFORNEC, 
                  'S', 
                  NVL(PCEST2.CUSTOPROXIMACOMPRA, 0), 
                  NVL(PCEST2.CUSTOREP, 0))) CUSTOPROXIMACOMPRA_2, 
       MAX(NVL(PCPRODUT.CUSTOFORNEC, 0)) CUSTOFORNEC_2, 
       (CASE 
         WHEN PARAMETROS.PRECOPOREMBALAGEM = 'S' THEN 
           MAX(NVL((SELECT NVL(PCEMBALAGEM.PVENDA, 0) 
                  FROM PCEMBALAGEM 
       	        WHERE PCEMBALAGEM.CODFILIAL = PCEST2.CODFILIAL 
                   AND PCEMBALAGEM.CODPROD = PCEST2.CODPROD 
                   AND PCEMBALAGEM.QTUNIT = 1 AND ROWNUM = 1), 0)) 
         ELSE 
           MAX(NVL((SELECT NVL(PCTABPR.PVENDA,0) 
                  FROM PCTABPR 
       	        WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
                   AND PCTABPR.NUMREGIAO = 2), 0)) 
       END) AS PVENDA_2,
       /* 
       PCPRODUT.CODEPTO, 
       PCDEPTO.DESCRICAO DEPARTAMENTO, 
       PCPRODUT.CODSEC, 
       PCPRODUT.OBS2, 
       PCSECAO.DESCRICAO SECAO, 
       --PCPRODUT.CODFORNEC, 
       PCFORNEC.CODFORNECPRINC, 
       PCFORNEC.FANTASIA, 
       --PCFORNEC.FORNECEDOR, 
       PCPRODUT.CODFAB, 
       PCPRODUT.NBM, 
       MAX((CASE 
             WHEN (NVL(PCPRODUT.SUGVENDA, 0) <= 0) THEN 
              NVL(PCCONSUM.SUGVENDA, 3) 
            ELSE 
              NVL(PCPRODUT.SUGVENDA, 0) 
            END)) SUGVENDA, 
       AVG(NVL((SELECT NVL(PCREGIAO.PERFRETEESPECIAL, 0) 
              FROM PCTABPR, 
                   PCREGIAO 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO 
               AND PCTABPR.NUMREGIAO = 2 ), 0)) PERFRETEESPECIAL, 
       AVG(NVL((SELECT NVL(PCREGIAO.PERFRETETERCEIROS, 0) 
              FROM PCTABPR, 
                   PCREGIAO 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO  
               AND PCTABPR.NUMREGIAO = 2 ), 0)) PERFRETETERCEIROS, 
       MAX(NVL((SELECT NVL(PCTRIBUT.TIPOCALCULOGNRETAB, 'P') 
              FROM PCTABPR, 
                   PCTRIBUT 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.CODST    = PCTRIBUT.CODST 
               AND PCTABPR.NUMREGIAO = 2 ), 'P')) TIPOCALCULOGNRETAB, 
       MAX(NVL((SELECT NVL(PCTRIBUT.USAPMCBASEST, 'N') 
              FROM PCTABPR, 
                   PCTRIBUT 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.CODST    = PCTRIBUT.CODST 
               AND PCTABPR.NUMREGIAO = 2 ), 'N')) USAPMCBASEST, 
       MAX(NVL((SELECT NVL(PCTRIBUT.USAVALORULTENTBASEST, 'N') 
              FROM PCTABPR, 
                   PCTRIBUT 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.CODST    = PCTRIBUT.CODST 
               AND PCTABPR.NUMREGIAO = 2 ), 'N')) USAVALORULTENTBASEST, 
       MAX(NVL((SELECT NVL(PCTRIBUT.USAVALORULTENTBASEST2, 'N') 
              FROM PCTABPR, 
                   PCTRIBUT 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.CODST    = PCTRIBUT.CODST 
               AND PCTABPR.NUMREGIAO = 2 ), 'N')) USAVALORULTENTBASEST2, 
       MAX(NVL(PCPRODUT.FRETEESPECIAL,'N')) FRETEESPECIAL, 
       AVG(NVL(PCPRODUT.PCOMREP1, 0)) PCOMREP1, 
       SUM(NVL((SELECT NVL(PCTABPR.PVENDA, 0) 
              FROM PCTABPR, 
                   PCREGIAO 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO 
               AND PCTABPR.NUMREGIAO = 2 ), 0)) PVENDA2, 
       AVG(NVL((SELECT NVL(PCREGIAO.VLFRETEKG, 0) 
              FROM PCTABPR, 
                   PCREGIAO 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO 
               AND PCTABPR.NUMREGIAO = 2 ), 0)) VLFRETEKG, 
       AVG(NVL((SELECT NVL(PCTRIBUT.CODICMTAB, 0) 
              FROM PCTABPR, 
                   PCTRIBUT 
             WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
               AND PCTABPR.CODST    = PCTRIBUT.CODST 
               AND PCTABPR.NUMREGIAO = 2 ), 0)) CODICMTAB, 
       AVG(NVL((SELECT NVL(PCTABPR.MARGEM, 0) 
            FROM PCTABPR, PCREGIAO 
           WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
             AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO 
             AND PCTABPR.NUMREGIAO = 2 ), 0)) MARGEM, 
       MAX(NVL(PCPRODUT.PRECOFIXO, 'N')) PRECOFIXO, 
       SUM(NVL(PCEST2.CUSTOREAL, 0)) CUSTOREAL2, 
       SUM(NVL(PCEST2.CUSTOFIN, 0)) CUSTOFIN2, 
       SUM(NVL(PCEST2.CUSTOULTENT, 0)) CUSTOULTENT3, 
       SUM(NVL(PCEST2.CUSTOULTPEDCOMPRA, 0)) CUSTOULTPEDCOMPRA3, 
       SUM(NVL(PCEST2.CUSTOULTENTFIN, 0)) CUSTOULTENTFIN3, 
       SUM(DECODE(PARAMETROS.USAPOLITICACOMERCIALPRODFILIAL, 
                  'P', 
                  DECODE(PARAMETROS.USANEGFORNEC, 
                         'S', 
                         NVL(PCPRODUT.CUSTOPROXIMACOMPRA, 0), 
                         NVL(PCPRODUT.CUSTOPROXIMACOMPRA, 0)), 
                  DECODE(PARAMETROS.USANEGFORNEC, 
                         'S', 
                         NVL(PCEST2.CUSTOPROXIMACOMPRA, 0), 
                         NVL(PCEST2.CUSTOPROXIMACOMPRA, 0)))) CUSTOPROXIMACOMPRA3, 
       SUM(DECODE(PARAMETROS.USAPOLITICACOMERCIALPRODFILIAL, 
                  'P', 
                  NVL(PCPRODUT.CUSTOFORNEC, 0), 
                  NVL(PCEST2.CUSTOFORNEC, 0))) CUSTOFORNEC3, 
       SUM(NVL((SELECT NVL(PCTRIBUT.PERDESCCUSTO, 0) 
            FROM PCTABPR, PCTRIBUT 
           WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
             AND PCTABPR.CODST    = PCTRIBUT.CODST 
             AND PCTABPR.NUMREGIAO = 2 ), 0)) PERDESCCUSTO, 
       MAX(NVL((SELECT NVL(PCTABPR.DESCONTAFRETE, 'N') 
            FROM PCTABPR, PCREGIAO 
           WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
             AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO 
             AND PCTABPR.NUMREGIAO = 2 ), 'N')) DESCONTAFRETE, 
       SUM(NVL((SELECT NVL(PCTABPR.PFRETE, 0) 
            FROM PCTABPR, PCREGIAO 
           WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
             AND PCTABPR.NUMREGIAO  = PCREGIAO.NUMREGIAO 
             AND PCTABPR.NUMREGIAO = 2 ), 0)) PFRETE, 
       0 VLRMZEROUNIT 

       */
 sum(PCEST2.QTPENDENTE) QTPENDENTE 
, sum(PCEST2.QTBLOQUEADA) QTBLOQUEADA 
, sum(PCEST2.QTRESERV) QTRESERV 
, sum(PCEST2.QTESTGER) QTESTGER 
  FROM PCPRODUT, 
       PCEST2, 
       PCFORNEC, 
       PCMARCA, 
       PCLINHAPROD, 
       PCDEPTO, 
       PCSECAO, 
       PCCONSUM, 
       PARAMETROS 
 WHERE PCPRODUT.CODPROD  = PCEST2.CODPROD 
   AND PCPRODUT.CODMARCA = PCMARCA.CODMARCA(+) 
   AND PCPRODUT.CODLINHAPROD = PCLINHAPROD.CODLINHA(+) 
   AND PARAMETROS.CODIGO = PCEST2.CODFILIAL 
 AND PCPRODUT.DTEXCLUSAO IS NULL 
   AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO                                                       
   AND PCPRODUT.CODSEC = PCSECAO.CODSEC(+)                                                      
   AND NVL(PCDEPTO.TIPOMERC, 'XX') NOT IN ('IM','CI')                                     
   AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC                                                  
 GROUP BY PCEST2.CODFILIAL, 
          PARAMETROS.USAPOLITICACOMERCIALPRODFILIAL, 
          PARAMETROS.PRECOPOREMBALAGEM, 
          PCPRODUT.CODPROD, 
          NVL(PCPRODUT.DESCRICAO,''), 
          PCPRODUT.NUMORIGINAL, 
          NVL(PCPRODUT.EMBALAGEM, ''), 
          PCPRODUT.CODEPTO, 
          PCDEPTO.DESCRICAO, 
          PCPRODUT.CODSEC, 
          PCPRODUT.OBS2, 
          PCSECAO.DESCRICAO, 
          PCPRODUT.CODFORNEC, 
          PCFORNEC.FORNECEDOR, 
          PCFORNEC.FANTASIA, 
          PCFORNEC.CODFORNECPRINC, 
          PCPRODUT.CODFAB, 
          PCPRODUT.QTUNITCX, 
          NVL(PCMARCA.MARCA,''), 
          PCLINHAPROD.DESCRICAO, 
          PCPRODUT.CODMARCA, 
          PCPRODUT.CODLINHAPROD, 
          PCPRODUT.CLASSE, 
          PCPRODUT.CLASSEVENDA, 
          PCPRODUT.NBM,
          PCPRODUT.CODFORNEC 
 ) A
WHERE 1=1--A.CODPROD = :CODPROD  
ORDER BY
CODPROD
