WITH PARAMETROS AS 
 (SELECT CODIGO, 
         NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('BLOQUEIAVENDAESTPENDENTE', 
                                           PCFILIAL.CODIGO), 
             PCCONSUM.BLOQUEIAVENDAESTPENDENTE) BLOQUEIAVENDAESTPENDENTE, 
         NVL(PCFILIAL.PRECOPOREMBALAGEM, PCCONSUM.PRECOPOREMBALAGEM) PRECOPOREMBALAGEM, 
         NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('USAPOLITICACOMERCIALPRODFILIAL'), 
                 'P') USAPOLITICACOMERCIALPRODFILIAL, 
         NVL(PARAMFILIAL.OBTERCOMOVARCHAR2('CON_USANEGFORNEC'), 'N') USANEGFORNEC 
    FROM PCFILIAL, 
         PCCONSUM 
   WHERE CODIGO <> '99' 
   AND CODIGO IN('2')
     AND DTEXCLUSAO IS NULL), 
 PCEST2 AS ( 
    SELECT PCEST.DTULTFAT, PCEST.QTESTGER, PCEST.QTRESERV, PCEST.QTBLOQUEADA,PCEST.QTPENDENTE, PCEST.CUSTOULTENT, 
           PCEST.CODFILIAL, PCEST.CODPROD, PCEST.DTULTENT, PCEST.DTULTSAIDA, PCEST.CUSTOFIN, PCEST.CUSTOREP, 
           PCEST.CUSTOREAL, PCEST.CUSTOPROXIMACOMPRA, PCEST.VALORULTENT, PCEST.CUSTOULTPEDCOMPRA, 
           PCEST.CUSTOULTENTFIN, PCEST.CUSTOFORNEC, PCEST.QTULTENT 
    FROM PCEST, PARAMETROS 
    WHERE PCEST.CODFILIAL = PARAMETROS.CODIGO 
 AND PCEST.CODFILIAL IN ('2')
) 
 select DISTINCT A.* from (  
SELECT DISTINCT
       PCPRODUT.CODFORNEC,
       PCFORNEC.FORNECEDOR, 
       PCPRODUT.CODPROD,
       NVL(PCPRODUT.DESCRICAO,'') DESCRICAO, 

       (CASE 
         WHEN PARAMETROS.PRECOPOREMBALAGEM = 'S' THEN 
          (SUM(NVL(PCEST2.QTESTGER, 0) * 
               NVL((SELECT NVL(PCEMBALAGEM.PVENDA, 0) 
                FROM PCEMBALAGEM 
                WHERE PCEMBALAGEM.CODFILIAL = PCEST2.CODFILIAL 
                AND (PCEMBALAGEM.CODPROD = PCEST2.CODPROD) 
                AND PCEMBALAGEM.QTUNIT = 1 
                AND ROWNUM = 1), 0))) 
         ELSE 
          (SUM(NVL(PCEST2.QTESTGER, 0) * 
               NVL((SELECT NVL(PCTABPR.PVENDA, 0) 
                FROM PCTABPR 
                WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
                AND (PCTABPR.NUMREGIAO = 2)), 0))) 
       END) VLPVENDA,

SUM(NVL(PCEST2.QTESTGER,0) * NVL(PCEST2.CUSTOREAL,0)) VLCUSTOREAL,


       MAX(DECODE(PARAMETROS.USANEGFORNEC, 
                  'S', 
                  NVL(PCPRODUT.CUSTOPROXIMACOMPRA, 0), 
                  NVL(PCPRODUT.CUSTOREP, 0))) AS CUSTOPROX_2, 
       MAX(DECODE(PARAMETROS.USAPOLITICACOMERCIALPRODFILIAL, 
                  'P', 
                  DECODE(PARAMETROS.USANEGFORNEC, 
                         'S', 
                         NVL(PCPRODUT.CUSTOPROXIMACOMPRA, 0), 
                         NVL(PCPRODUT.CUSTOREP, 0)), 
                  DECODE(PARAMETROS.USANEGFORNEC, 
                         'S', 
                         NVL(PCEST2.CUSTOPROXIMACOMPRA, 0), 
                         NVL(PCEST2.CUSTOREP, 0)))) AS CUSTOPROXPARAM_2, 
       MAX(NVL(PCEST2.VALORULTENT,0)) AS VALORULTENT_2, 
       MAX(NVL(PCEST2.CUSTOULTPEDCOMPRA, 0)) CUSTOULTPEDCOMPRA_2, 
       MAX(NVL(PCEST2.CUSTOULTENTFIN, 0)) CUSTOULTENTFIN_2, 
       MAX(DECODE(PARAMETROS.USANEGFORNEC, 
                  'S', 
                  NVL(PCEST2.CUSTOPROXIMACOMPRA, 0), 
                  NVL(PCEST2.CUSTOREP, 0))) CUSTOPROXIMACOMPRA_2, 
       MAX(NVL(PCPRODUT.CUSTOFORNEC, 0)) CUSTOFORNEC_2, 
       (CASE 
         WHEN PARAMETROS.PRECOPOREMBALAGEM = 'S' THEN 
           MAX(NVL((SELECT NVL(PCEMBALAGEM.PVENDA, 0) 
                  FROM PCEMBALAGEM 
       	        WHERE PCEMBALAGEM.CODFILIAL = PCEST2.CODFILIAL 
                   AND PCEMBALAGEM.CODPROD = PCEST2.CODPROD 
                   AND PCEMBALAGEM.QTUNIT = 1 AND ROWNUM = 1), 0)) 
         ELSE 
           MAX(NVL((SELECT NVL(PCTABPR.PVENDA,0) 
                  FROM PCTABPR 
       	        WHERE PCTABPR.CODPROD = PCEST2.CODPROD 
                   AND PCTABPR.NUMREGIAO = 2), 0)) 
       END) AS PVENDA_2,

 sum(PCEST2.QTPENDENTE) QTPENDENTE 
, sum(PCEST2.QTBLOQUEADA) QTBLOQUEADA 
, sum(PCEST2.QTRESERV) QTRESERV 
, sum(PCEST2.QTESTGER) QTESTGER 
  FROM PCPRODUT, 
       PCEST2, 
       PCFORNEC, 
       PCMARCA, 
       PCLINHAPROD, 
       PCDEPTO, 
       PCSECAO, 
       PCCONSUM, 
       PARAMETROS 
 WHERE PCPRODUT.CODPROD  = PCEST2.CODPROD 
   AND PCPRODUT.CODMARCA = PCMARCA.CODMARCA(+) 
   AND PCPRODUT.CODLINHAPROD = PCLINHAPROD.CODLINHA(+) 
   AND PARAMETROS.CODIGO = PCEST2.CODFILIAL 
 AND PCPRODUT.DTEXCLUSAO IS NULL 
   AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO                                                       
   AND PCPRODUT.CODSEC = PCSECAO.CODSEC(+)                                                      
   AND NVL(PCDEPTO.TIPOMERC, 'XX') NOT IN ('IM','CI')                                     
   AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC                                                  
 GROUP BY PCEST2.CODFILIAL, 
          PARAMETROS.USAPOLITICACOMERCIALPRODFILIAL, 
          PARAMETROS.PRECOPOREMBALAGEM, 
          PCPRODUT.CODPROD, 
          NVL(PCPRODUT.DESCRICAO,''), 
          PCPRODUT.NUMORIGINAL, 
          NVL(PCPRODUT.EMBALAGEM, ''), 
          PCPRODUT.CODEPTO, 
          PCDEPTO.DESCRICAO, 
          PCPRODUT.CODSEC, 
          PCPRODUT.OBS2, 
          PCSECAO.DESCRICAO, 
          PCPRODUT.CODFORNEC, 
          PCFORNEC.FORNECEDOR, 
          PCFORNEC.FANTASIA, 
          PCFORNEC.CODFORNECPRINC, 
          PCPRODUT.CODFAB, 
          PCPRODUT.QTUNITCX, 
          NVL(PCMARCA.MARCA,''), 
          PCLINHAPROD.DESCRICAO, 
          PCPRODUT.CODMARCA, 
          PCPRODUT.CODLINHAPROD, 
          PCPRODUT.CLASSE, 
          PCPRODUT.CLASSEVENDA, 
          PCPRODUT.NBM,
          PCPRODUT.CODFORNEC 
 ) A
WHERE 1=1
ORDER BY
CODPROD
