SELECT  
BON.NUMBONUS AS NUMEROBONUS,
BON.CODFILIAL AS CODIGOFILIAL,
BON.CODFUNCRM AS CODIGOFUNCIONARIOCMR,
BON.CODFUNCFECHA AS CODIGOFUNCIONARIOFECHAMENTO,
BON.CODFUNCBONUS AS CODIGOFUNCIONARIOBONUS, 
BON.CODFUNCCANCEL AS CODIGOFUNCIONARIOCANCELAMENTO, 
BONI.CODPROD AS CODIGOPRODUTO,
BONI.CODMOTIVO AS CODIGOMOTIVODEVOLUACAO,
BON.DATABONUS,
BONI.QTNF AS QUANTIDADENOTA,
BONI.QTENTRADA AS QUANTIDADEENTRADA,
BONI.QTAVARIA AS QUANTIDADEAVARIA,
BON.DTCANCEL AS DATACANCELAMENTO,
BON.DTFECHAMENTO AS DATAFECHAMENTO, 
CASE WHEN BONI.QTNF <> BONI.QTENTRADA THEN 1 ELSE 0 END AS FALTA,
CASE WHEN BONI.QTAVARIA <> 0 THEN 1 ELSE 0 END AS AVARIA,
PRO.PESOBRUTO AS PESOBRUTOUNITARIO,
PRO.PESOLIQ AS PESOLIQUIDOUNITARIO,
PRO.VOLUME AS VOLUMEUNITARIO
FROM PCBONUSC BON
INNER JOIN PCBONUSI BONI ON BONI.NUMBONUS = BON.NUMBONUS
INNER JOIN PCPRODUT PRO ON PRO.CODPROD = BONI.CODPROD
WHERE TO_CHAR(BON.DATABONUS, 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -24), 'YYYY')