SELECT
ENT.CODFILIAL AS CODIGOFILIAL,
BON.NUMBONUS AS NUMEROBONUS,
BONI.CODMOTIVO AS CODIGOMOTIVODEVOLUACAO,
TRUNC(DEVFOR.DTDEVOL) AS DATADEVOLUCAO
FROM PCDEVFORNEC DEVFOR
INNER JOIN PCNFENT ENT ON ENT.NUMTRANSENT = DEVFOR.NUMTRANSENT
INNER JOIN PCBONUSC BON ON BON.NUMBONUS = ENT.NUMBONUS
INNER JOIN PCBONUSI BONI ON BONI.NUMBONUS = BON.NUMBONUS
WHERE  TO_CHAR(BON.DATABONUS, 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -24), 'YYYY')