SELECT  
  
  PCFINANC.CODFILIAL AS CODIGOFILIAL,
  DATA+1 AS DATAINICIAL,
  DATA AS DATAFINAL,
  PCFINANC.SALDOBCO AS SALDOBANCARIO,
  PCFINANC.SALDOCR AS SALDOCONTASRECEBER,
  PCFINANC.SALDOESTFIN AS SALDOESTOQUE,
  PCFINANC.SALDOCP AS SALDOCONTASPAGAR,
  PCFINANC.SALDOCX AS SALDOCAIXA,
  PCFINANC.SALDOVALE AS SALDOVALE,
  PCFINANC.SALDOEMPRESTATIVO AS SALDOEMPRESTIMORECEBER,
  PCFINANC.SALDOEMPRESTPASSIVO AS SALDOEMPRESTIMOPAGAR,
  PCFINANC.SALDOCTRANS AS SALDOCONTATRANSITORIA,
  PCFINANC.SALDOCRFOR AS SALDOCONTASRECEBERFORNECEDOR,
  PCFINANC.SALDOINVESTATIVO AS SALDOINVESTIMENTOATIVO,
  PCFINANC.SALDOINVESTPASSIVO AS SALDOINVESTIMENTOPASSIVO,
  PCFINANC.SALDOADIANTFOR AS SALDOADIANTAMENTOFORNECEDOR,
  PCFINANC.SALDOCREDCLI AS SALDOCREDITO,
  PCFINANC.SALDOTITULOVENDOR AS SALDOTITULODESCONTO
FROM PCFINANC
WHERE TO_CHAR(PCFINANC.DATA, 'YYYY') >= TO_CHAR(SYSDATE, 'YYYY') - 8