SELECT 
EST.CODPROD AS CODIGOPRODUTO, 
EST.CODFILIAL AS CODIGOFILIAL,
CASE WHEN EST.QTGIRODIA = 0 THEN 'SEM GIRO'
WHEN EST.QTGIRODIA > 0 AND EST.QTGIRODIA <= 20 THEN 'GIRO BAIXO'
WHEN EST.QTGIRODIA > 20 AND EST.QTGIRODIA <= 100 THEN 'GIRO MÉDIO'
WHEN EST.QTGIRODIA > 100 THEN 'ALTO GIRO'
END AS NIVELGIRODIA,
CASE WHEN EST.QTGIRODIA <= 0 THEN 'IGUAL A 0'
WHEN EST.QTGIRODIA > 0 AND EST.QTGIRODIA <= 5 THEN 'DE 0 A 5'
WHEN EST.QTGIRODIA > 5 AND EST.QTGIRODIA <= 10 THEN 'DE 5 A 10'
WHEN EST.QTGIRODIA > 10 AND EST.QTGIRODIA <= 20 THEN 'DE 10 A 20'
WHEN EST.QTGIRODIA > 20 AND EST.QTGIRODIA <= 50 THEN 'DE 20 A 50'
WHEN EST.QTGIRODIA > 50 AND EST.QTGIRODIA <= 100 THEN 'DE 50 A 100'
WHEN EST.QTGIRODIA > 100 THEN 'ACIMA DE 100'
END AS ESCALAGIRODIA,
CASE WHEN (EST.QTESTGER /  DECODE(EST.QTGIRODIA, 0, 1, EST.QTGIRODIA)) = 0 THEN 'IGUAL A 0'
WHEN (EST.QTESTGER /  DECODE(EST.QTGIRODIA, 0, 1, EST.QTGIRODIA)) BETWEEN 0 AND 5 THEN 'DE 0 A 5'
WHEN (EST.QTESTGER /  DECODE(EST.QTGIRODIA, 0, 1, EST.QTGIRODIA)) BETWEEN  5 AND 10 THEN 'DE 5 A 10'
WHEN (EST.QTESTGER /  DECODE(EST.QTGIRODIA, 0, 1, EST.QTGIRODIA)) BETWEEN  10 AND 20 THEN 'DE 10 A 20'
WHEN (EST.QTESTGER /  DECODE(EST.QTGIRODIA, 0, 1, EST.QTGIRODIA)) BETWEEN  20 AND 30 THEN 'DE 20 A 30'
WHEN (EST.QTESTGER /  DECODE(EST.QTGIRODIA, 0, 1, EST.QTGIRODIA)) BETWEEN  30 AND 60 THEN 'DE 30 A 60'
WHEN (EST.QTESTGER /  DECODE(EST.QTGIRODIA, 0, 1, EST.QTGIRODIA)) > 60 THEN 'ACIMA DE 60'
END AS ESCALADIASESTOQUE, 
CASE WHEN PRO.OBS2  = 'FL' THEN 'FORA DE LINHA' ELSE 'EM LINHA'
END AS FORALINHA,
CASE WHEN PRO.DTEXCLUSAO IS NULL THEN 'ATIVO' ELSE 'INATIVO' END AS SITUACAO


FROM PCEST EST
INNER JOIN PCPRODUT PRO ON PRO.CODPROD = EST.CODPROD