SELECT 
PCNFENT.NUMNOTA AS NUMERONOTADEVOLUCAO,
PCNFENT.TIPODESCARGA,
PCNFENT.CODFISCAL AS CODIGOFISCAL,
CASE WHEN  PCESTCOM.NUMTRANSVENDA IS NULL THEN 'DEVOLUÇÃO AVULSA' 
     WHEN NVL(PCNFSAID.CONDVENDA,0) IN (5, 6) THEN 'DEVOLUÇÃO BONIFICADA' 
     ELSE 'DEVOLUÇÃO NORMAL' END AS TIPODEVOLUCAO
FROM PCNFENT, PCESTCOM, PCNFSAID
WHERE PCNFENT.NUMTRANSENT = PCESTCOM.NUMTRANSENT
AND PCESTCOM.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA(+)
AND TO_CHAR(PCNFENT.DTENT, 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -96), 'YYYY')