SELECT 
SAI.NUMNOTA AS NUMERONOTAVENDA,
SAI.NUMTRANSVENDA AS NUMEROTRANSACAOVENDA,
SAI.TIPOVENDA AS TIPOVENDA,
SAI.CONDVENDA AS CONDICAOVENDA,


       CASE
WHEN SAI.CONDVENDA IN (1, 9) THEN 'VENDA NORMAL' 
WHEN SAI.CONDVENDA IN (4) THEN 'SIMPLES FATURA'
WHEN SAI.CONDVENDA IN (5,6) THEN 'BONIFICAÇÃO'
WHEN SAI.CONDVENDA IN (7) THEN 'VENDA ENTREGA FUTURA'
WHEN SAI.CONDVENDA IN (8) THEN 'SIMPLES ENTERGA'
WHEN SAI.CONDVENDA IN (9) THEN 'VENDA NORMAL' 
WHEN SAI.CONDVENDA IN (10) THEN 'TRANSFERÊNCIA'
WHEN SAI.CONDVENDA IN (11) THEN 'VENDA COM TROCA'
WHEN SAI.CONDVENDA IN (13) THEN 'MANIFESTO'  
WHEN SAI.CONDVENDA IN (13) THEN 'VENDA COM MANIFESTO'
WHEN SAI.CONDVENDA IN (20) THEN 'VENDA CONSIGNAÇÃO'
ELSE 'NÃO IDENTIFICADO'  END AS DESCRICAOCONDICAOVENDA,


CASE WHEN SAI.DTCANCEL IS NULL THEN 'NÃO CANCELADO'
     ELSE 'CANCELADO' END AS CANCELADO,
SAI.ESPECIE,
SAI.SERIE,

SAI.NUMITENS AS QUANTIDADEITENS
FROM PCNFSAID SAI
WHERE  TO_CHAR(SAI.DTSAIDA, 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -96), 'YYYY')