SELECT 
LOGINV.NUMINVENT AS NUMEROINVENTARIO,
LOGINV.CODFILIAL AS CODIGOFILIAL,
LOGINV.CODPROD AS CODIGOPRODUTO,
LOGINV.NUMLOTE NUMEROLOTE,
LOGINV.CODENDERECO AS CODIGOENDERECO,
LOGINV.QTANT AS QUANTIDADEANTERIOR,
LOGINV.QTINVENT AS QUANTIDADEINVENTARIO,
CASE WHEN LOGINV.QTANT = LOGINV.QTINVENT THEN 'SEM DIVERGÊNCIA'
ELSE 'DIVERGÊNCIA' END STATUSDIVERGENCIA,
CASE WHEN LOGINV.QTANT = LOGINV.QTINVENT THEN 0
ELSE 1 END CONTAGEMDIVERGENTE,
CASE WHEN LOGINV.QTANT = LOGINV.QTINVENT THEN LOGINV.CODPROD
END PRODUTOSEMDIVERGENCIA,
TRUNC(INV.DATA) AS DATAGERACAO,
TRUNC(INV.DTATUALIZACAO) AS DATAATUALIZACAO
FROM PCLOGINVENTARIOWMS LOGINV
INNER JOIN PCINVENTENDERECO INV ON INV.NUMINVENT = LOGINV.NUMINVENT AND INV.CODENDERECO = LOGINV.CODENDERECO
WHERE TO_CHAR(INV.DATA, 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -24), 'YYYY')