SELECT
'3-Devolução de Cliente' AS INDICADOR,
DEVOL.VLDEVOLUCAO AS VALOR,
DEVOL.CODFILIAL AS CODIGOFILIAL,
DEVOL.DTENT AS DATA           
FROM VIEW_DEVOL_RESUMO_FATURAMENTO DEVOL 
WHERE DEVOL.CONDVENDA NOT IN (4, 8, 10, 13, 20, 98, 99)
AND TO_CHAR(DEVOL.DTENT, 'YYYY') >= TO_CHAR(SYSDATE, 'YYYY') - 10