SELECT CODFILIAL, CODCONTA, TO_DATE('01/01/'||ANO, 'DD/MM/YYYY') DATA, vlorcmes01 VALOR FROM PCORCLAN
UNION
SELECT CODFILIAL, CODCONTA, TO_DATE('01/02/'||ANO, 'DD/MM/YYYY') DATA, vlorcmes02 VALOR FROM PCORCLAN 
UNION
SELECT CODFILIAL, CODCONTA, TO_DATE('01/03/'||ANO, 'DD/MM/YYYY') DATA, vlorcmes03 VALOR FROM PCORCLAN 
UNION
SELECT CODFILIAL, CODCONTA, TO_DATE('01/04/'||ANO, 'DD/MM/YYYY') DATA, vlorcmes04 VALOR FROM PCORCLAN 
UNION
SELECT CODFILIAL, CODCONTA, TO_DATE('01/05/'||ANO, 'DD/MM/YYYY') DATA, vlorcmes05 VALOR FROM PCORCLAN 
UNION
SELECT CODFILIAL, CODCONTA, TO_DATE('01/06/'||ANO, 'DD/MM/YYYY') DATA, vlorcmes06 VALOR FROM PCORCLAN 
UNION
SELECT CODFILIAL, CODCONTA, TO_DATE('01/07/'||ANO, 'DD/MM/YYYY') DATA, vlorcmes07 VALOR  FROM PCORCLAN
UNION
SELECT CODFILIAL, CODCONTA, TO_DATE('01/08/'||ANO, 'DD/MM/YYYY') DATA, vlorcmes08 VALOR  FROM PCORCLAN
UNION
SELECT CODFILIAL, CODCONTA, TO_DATE('01/09/'||ANO, 'DD/MM/YYYY') DATA, vlorcmes09 VALOR  FROM PCORCLAN
UNION
SELECT CODFILIAL, CODCONTA, TO_DATE('01/10/'||ANO, 'DD/MM/YYYY') DATA, vlorcmes10 VALOR  FROM PCORCLAN 
UNION
SELECT CODFILIAL, CODCONTA, TO_DATE('01/11/'||ANO, 'DD/MM/YYYY') DATA, vlorcmes11 VALOR FROM PCORCLAN
UNION
SELECT CODFILIAL, CODCONTA, TO_DATE('01/12/'||ANO, 'DD/MM/YYYY') DATA, vlorcmes12 VALOR  FROM PCORCLAN