SELECT 
ORC.CODFILIAL AS CODIGOFILIAL,
ORC.CODCONTA AS CODIGOCONTA,
ORC.CODIGOCENTROCUSTO,
TO_DATE('01/'||ORC.MES||'/'||ORC.ANO, 'DD/MM/YYYY') AS  DATA,
ORC.VALOR,
ORC.PERCRATEIO AS PERCENTUALRATEIO
FROM PCORCLANCENTROCUSTO ORC
WHERE    ORC.ANO >= TO_CHAR(ADD_MONTHS(SYSDATE, -36), 'YYYY')