SELECT
PCPREST.PREST AS PRESTACAO, 
PCPREST.NUMTRANSVENDA AS NUMEROTRANSACAOVENDA,
PCPREST.CODFILIAL AS CODIGOFILIAL,
PCPREST.CODCLI AS CODIGOCLIENTE, 
PCPREST.CODCOB AS CODIGOCOBRANCA, 
PCPREST.CODBANCO AS CODIGOBANCO,
PCPREST.CODUSUR AS CODIGORCA, 
PCPREST.VALOR AS VALORTITULO, 
PCPREST.VPAGO AS VALORPAGO,
PCPREST.TXPERM AS VALORJUROS, 
PCPREST.VALORDESC AS VALORDESCONTO, 
PCPREST.DTVENC AS DATAVENCIMENTO, 
PCPREST.DTPAG AS DATAPAGAMENTO, 
PCPREST.DTEMISSAO AS DATAEMISSAO,
PCPREST.DTBAIXA AS DATABAIXA, 
DECODE(PCPREST.DTPAG, NULL, PCPREST.DTVENC, PCPREST.DTPAG) AS DATATITULO, 
PCPREST.NUMCAR AS NUMEROCARREGAMENTO,

CASE WHEN ( PCPREST.DTPAG IS NOT NULL AND PCPREST.DTPAG > PCPREST.DTVENC ) THEN PCPREST.DTPAG - PCPREST.DTVENC
     WHEN ( PCPREST.DTPAG IS NULL AND PCPREST.DTVENC < SYSDATE) THEN CAST(SYSDATE - PCPREST.DTVENC AS INT)
     END AS DIASATRASO,
     
CASE WHEN PCPREST.DTPAG IS NULL AND PCPREST.DTVENC < TRUNC(SYSDATE) THEN 1 END AS INADIMPLENCIA,
CASE WHEN (PCPREST.DTPAG IS NOT NULL AND PCPREST.DTPAG > PCPREST.DTVENC) OR  
          (PCPREST.DTPAG IS NULL AND PCPREST.DTVENC < TRUNC(SYSDATE)) THEN 1 END AS ATRASO     
     
FROM PCPREST
WHERE (PCPREST.CODCOB NOT IN ('DEVP', 'DEVT', 'BNF', 'BNFT', 'BNFR', 'BNTR', 'BNRP', 'CRED', 'DESD'))
   AND TO_CHAR(PCPREST.DTVENC , 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -132), 'YYYY')