SELECT 
PCLANC.RECNUM AS NUMEROLANCAMENTO,
CASE 
     WHEN PCLANC.TIPOPARCEIRO = 'F' THEN ('F'||TRIM(TO_CHAR(PCLANC.CODFORNEC,'000000000'))) 
     WHEN PCLANC.TIPOPARCEIRO = 'C' THEN ('C'||TRIM(TO_CHAR(PCLANC.CODFORNEC,'000000000')))
     WHEN PCLANC.TIPOPARCEIRO = 'R' THEN ('R'||TRIM(TO_CHAR(PCLANC.CODFORNEC,'000000000')))
     ELSE '0'
END AS CODIGOPARCEIRO, 
PCLANC.CODFILIAL AS CODIGOFILIAL, 
PCLANC.CODCONTA AS CODIGOCONTA,
PCLANC.CODFORNEC AS CODIGOFORNECEDOR,
PCLANC.VALOR AS VALORLANCAMENTO,
PCLANC.VPAGO AS VALORPAGAMENTO, 
PCLANC.VALORDEV AS VALORDEVOLUCAO, 
PCLANC.DESCONTOFIN AS VALORDESCONTO, 
PCLANC.TXPERM AS VALORJUROS,
PCLANC.DTPAGTO AS DATAPAGAMENTO,
PCLANC.DTLANC AS DATATITULO,
PCLANC.DTVENC AS DATAVENCIMENTO,
PCLANC.NUMNOTA AS NUMERONOTA,
PCLANC.NUMNOTADEV AS NUMERONOTADEVOLUCAO,
PCLANC.NUMBANCO AS CODIGOBANCO
FROM PCLANC, PCCONTA, PCGRUPO, PCFORNEC
WHERE PCLANC.CODCONTA = PCCONTA.CODCONTA(+)
AND PCLANC.CODFORNEC = PCFORNEC.CODFORNEC(+)
AND PCCONTA.GRUPOCONTA = PCGRUPO.CODGRUPO(+)   
AND TO_CHAR(PCLANC.DTVENC , 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -132), 'YYYY')