SELECT PCCIDADE.CODCIDADE, PCCIDADE.NOMECIDADE,
       SUM(PCPEDI.QT) AS QT,
       COUNT(DISTINCT(PCPEDC.CODCLI)) QTCLIPOS,
       SUM(ROUND(NVL(PCPEDI.QT,0)*(NVL(PCPEDI.PVENDA, 0) + NVL(PCPEDI.VLOUTRASDESP, 0) + NVL(PCPEDI.VLFRETE, 0)),2)) AS PVENDA,
       SUM(ROUND(NVL(PCPRODUT.PESOBRUTO,0)*NVL(PCPEDI.QT,0),2)) AS TOTPESO,
       SUM(ROUND(NVL(PCPRODUT.VOLUME,0)*NVL(PCPEDI.QT,0),2)) Volume,
       ROUND(SUM(NVL(PCPRODUT.LITRAGEM, 0)*NVL(PCPEDI.QT,0)) ,2) LITRAGEM,
       SUM(NVL(PCPEDI.QT,0) / DECODE(NVL(PCPRODUT.QTUNIT,0),0,1,NVL(PCPRODUT.QTUNIT,1))) TOTQTUNIT,
       SUM(NVL(PCPEDI.QT,0) / DECODE(NVL(PCPRODUT.QTUNITCX,0),0,1,NVL(PCPRODUT.QTUNITCX,1))) TOTQTUNITCX
FROM PCPEDI, PCPEDC, PCPRODUT, PCFORNEC, PCDEPTO, PCUSUARI, PCCLIENT, PCATIVI, PCPRACA, PCCIDADE
WHERE PCPEDI.NUMPED = PCPEDC.NUMPED
AND PCUSUARI.CODSUPERVISOR NOT IN ('9999')
AND PCPEDC.DATA BETWEEN :DATAI AND :DATAF
AND PCPEDC.CODFILIAL IN ('2')
AND PCPEDC.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
 AND NVL(PCPEDI.BONIFIC, 'N') =  'N' 
AND PCPEDC.CODCLI      = PCCLIENT.CODCLI
AND PCCLIENT.CODATV1   = PCATIVI.CODATIV(+)
AND PCPEDC.DTCANCEL IS NULL
AND PCPEDI.CODPROD     = PCPRODUT.CODPROD(+)
AND PCPRODUT.CODEPTO   = PCDEPTO.CODEPTO(+)
AND PCPRACA.CODPRACA   = PCCLIENT.CODPRACA(+)
AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC(+)
AND PCPEDC.CODUSUR     = PCUSUARI.CODUSUR(+)
AND PCCLIENT.CODCIDADE = PCCIDADE.CODCIDADE(+)
GROUP BY PCCIDADE.CODCIDADE, PCCIDADE.NOMECIDADE
ORDER BY PVENDA DESC