SELECT 
VIS.CODVISITA AS CODIGOVISITA,
VIS.CODCLI AS CODIGOCLIENTE,
VIS.CODUSUR AS CODIGORCA,
--VIS.DATA,
TO_CHAR(TO_CHAR(TRUNC(VIS.DATA), 'YYYY-MM-DD')||' 00:00:00.000') AS DATA,
NFS.NUMPED AS NUMEROPEDIDO
FROM PCVISITA VIS
LEFT JOIN PCNFSAID NFS ON ( NFS.CODCLI = VIS.CODCLI AND NFS.CODUSUR = VIS.CODUSUR AND TRUNC(NFS.DTSAIDA) = TRUNC(VIS.DATA))
WHERE TO_CHAR(VIS.DATA , 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -36), 'YYYY')