SELECT RCA.CODUSUR AS CODIGORCA,
RCA.NOME AS RCA,
RCA.EMAIL AS EMAILRCA,
SUP.CODSUPERVISOR AS CODIGOSUPERVISOR,
SUP.NOME AS SUPERVISOR,
SUP.EMAIL AS EMAILSUPERVISOR,
GER.CODGERENTE AS CODIGOGERENTE,
GER.NOMEGERENTE AS GERENTE ,
NULL AS EMAILGERENTE,
CASE 
WHEN RCA.DTTERMINO IS NULL THEN 'ATIVO'
ELSE 'INATIVO' 
END AS SITUACAO,
CASE RCA.TIPOVEND
    WHEN   'R' THEN 'REPRESENTANTE' 
    WHEN 'P' THEN 'PROFISSIONAL' 
    WHEN 'I' THEN 'INTERNO' 
    WHEN 'E' THEN 'EXTERNO' 
  ELSE 'NÃO DEFINIDO'  END TIPO
FROM PCUSUARI RCA
LEFT JOIN PCSUPERV SUP ON SUP.CODSUPERVISOR = RCA.CODSUPERVISOR
LEFT JOIN PCGERENTE GER ON GER.CODGERENTE = SUP.CODGERENTE