   SELECT 
     PCUSUARI.CODUSUR, 
     PCMETA.CODIGO,
       SUM(NVL(PCMETA.VLVENDAPREV,0)) VLMETA,
       SUM(NVL(PCMETA.CLIPOSPREV,0)) CLIPOSPREV
  FROM PCMETA, PCUSUARI 
         ,PCFORNEC 
WHERE PCMETA.CODUSUR = PCUSUARI.CODUSUR
AND PCUSUARI.CODSUPERVISOR NOT IN ('9999')
         AND PCMETA.TIPOMETA = 'F'
         AND PCFORNEC.CODFORNEC = PCMETA.CODIGO
 --AND PCMETA.DATA BETWEEN P_DATA_INI AND P_DATA_FIM
 AND PCMETA.DATA>= to_date('01/01/2024','dd/mm/yyyy') 
 AND PCMETA.CODFILIAL IN (2)
--AND PCUSUARI.CODUSUR IN(P_RCA)
 
GROUP BY 
PCUSUARI.CODUSUR, 
PCMETA.CODIGO
