SELECT
  PCMOV.CODPROD AS CODIGOPRODUTO,
  PCMOV.CODFILIAL AS CODIGOFILIAL,
  PCMOV.CODFORNEC AS CODIGOFORNECEDOR,
  PCMOV.DTMOV AS DATAMOVIMENTACAO,
  NVL(PCMOV.QT, 0) AS QUANTIDADE,
  NVL(PCMOV.PUNIT, 0) AS VALORUNITARIO,
  NVL(PCMOV.CUSTOFIN, 0) AS VALORUNITARIOCUSTO,
  NVL(PCMOV.QT, 0) * NVL(PCMOV.CUSTOFIN, 0) AS VALORCUSTOTOTAL,
  NVL(PCMOV.PESOLIQ, 0) AS PESOUNITARIOLIQUIDO,
  NVL(PCMOV.PESOBRUTO, 0) AS PESOUNITARIOBRUTO,
  NVL(PCMOV.VOLUME, 0) AS VOLUMEUNITARIO
FROM PCMOV
WHERE
  PCMOV.CODOPER = 'EI'
  AND TO_CHAR(PCMOV.DTMOV, 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -36), 'YYYY')