SELECT 
 to_date(A.DTMOV,'dd/mm/yyyy') As Data
, A.NUMNOTA
, A.CODPROD
, A.CODFISCAL
, A.QT
,A.QTCONT
, A.PUNITCONT
, A.QT * A.PUNITCONT AS TOTAL
, A.RoTinalanc,


/**
        A.CODPROD,
        A.ROWID, 
       A.DESCRICAO,
       --A.EMBALAGEM,
       NVL(A.BASEICMS,0) + NVL(C.VLBASEFRETE,0) +
        NVL(C.VLBASEOUTROS,0) AS BASEICMS,
       A.CODINTERNO,
**/
       -----------------------------------------------------
      --(CASE WHEN ((:SERIE IN ('CF','CP','SF')) OR (SUBSTR(SA.CHAVENFE,21,2) = '65')) THEN 
      (CASE WHEN (('1' IN ('CF','CP','SF')) OR (SUBSTR(SA.CHAVENFE,21,2) = '65')) THEN 
        ROUND(NVL(C.VLSUBTOTITEM,0),2) 
      WHEN (SA.TIPOVENDA = 'DF' OR A.CODOPER = 'SD') THEN 
        CASE WHEN SA.ROTINACAD NOT LIKE '%1302%' THEN 
          ROUND(A.QTCONT * (NVL(A.PUNITCONT, 0) - NVL(A.VLFRETE, 0)), 2)
        ELSE
          ROUND(A.QTCONT *  NVL(A.PTABELA,0),2)
          - ROUND(A.QTCONT * NVL(A.VLDESCONTO,0), 2) 
          - ROUND(A.QTCONT * NVL(A.VLSUFRAMA,0), 2) 
          - ROUND(A.QTCONT * NVL(C.VLICMSDESONERACAO,0), 2) 
          + ROUND(A.QTCONT * NVL(A.VLFRETE,0), 2) 
          + ROUND(A.QTCONT * NVL(A.VLDESPDENTRONF,0), 2) 
          + ROUND(A.QTCONT * NVL(A.VLSEGURO,0), 2) 
          + ROUND(A.QTCONT * NVL(C.VLFECP,0), 2) 
          + ROUND(A.QTCONT * DECODE(NVL(C.VLIPIDEVFORNEC,0),0,NVL (A.VLIPI, 0),NVL(C.VLIPIDEVFORNEC,0)), 2) 
          + ROUND(A.QTCONT * DECODE(NVL(C.VLSTDEVFORNEC,0),0,NVL (A.ST, 0),NVL(C.VLSTDEVFORNEC,0)), 2) 
        END 
      ELSE 
        ROUND(A.QTCONT * (NVL(A.PUNITCONT,0) - NVL(A.ST,0) - NVL(A.VLIPI,0) - NVL(C.VLIPIDEVFORNEC,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(A.ST,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(A.VLIPI,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(A.VLOUTROS,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(C.VLIPIDEVFORNEC,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(A.VLFRETE,0)), 2) 
      END)
VLTOTAL,

/**
A.PUNITCONT,
       A.QTCONT,
       A.DTMOV,
        A.NUMNOTA,
        A.CODFISCAL,
         A.ROTINALANC,
                A.PESOLIQ,
       A.VOLUME,
       A.QTUNIT,
       A.QTUNITCX,
       A.RUA
**/
/**
       -----------------------------------------------------
       A.PUNITCONT,
       A.QTCONT,
       A.ST,
       NVL(C.VLSUBTOTDESCONTO, A.VLDESCONTO) AS VLDESCONTO,
       A.VLFRETE,
       A.VLIPI,
       A.VLOUTRASDESP,
       A.VLOUTROS,
       A.DTMOV,
       A.STATUS,
       A.PERCICM,
       A.PERCIPI,
       A.NUMTRANSVENDA,
       A.CODEPTO,
       A.CODSEC,
       A.NUMNOTA,
       A.CODOPER,
       A.CODFILIAL,
       A.CODCLI,
       A.CODFORNEC,
       A.CODUSUR,
       A.CUSTOFIN,
       A.CUSTOCONT,
       A.CUSTOREAL,
       A.VALORULTENT,
       A.BASEICST,
       A.VLBASEIPI,
       A.PERCDESC,
       A.SITTRIBUT,
       A.CODST,
       A.CODFISCAL,
       A.CODFILIALNF,
       A.NUMFORMULARIO,
       A.NUMFORMULARIO2,
       A.CLASSIFICFISCAL,
       A.VLREPASSE,       
       A.NUMIDF,
       A.BASEICMSBCR,
       A.VLICMSBCR,
       A.BASEBCR,
       A.STBCR,
       A.CODFISCALOUTRASDESPENT,
       A.ALIQICMOUTRASDESPENT,
       A.CODFISCALFRETEENT,
       A.ALIQICMFRETEENT,
       A.ROTINALANC,
       A.PERICMSANTECIPADO,
       A.VLCREDPRESUMIDO,
       A.PERCCREDICMPRESUMIDO,
       A.ALIQICMS1,
       A.ALIQICMS2,
       A.PERCIVA,
       A.BASEDIFALIQUOTAS,
       A.PERCDIFALIQUOTAS,
       A.VLDIFALIQUOTAS,
       A.VLBASESTFORANF,
       A.VLDESPADICIONAL,
       A.VLBASEGNRE,
       A.STCLIENTEGNRE,
       A.BASEACRESCIMOPF,
       A.PERACRESCIMOPF,
       A.VLACRESCIMOPF,
       A.PISCOFINSRETIDO,
       A.VLBASEPISCOFINS,
       A.PERPIS,
       A.PERCOFINS,
       A.VLCREDPIS,
       A.VLCREDCOFINS,
       A.VLPIS,
       A.VLCOFINS,
       NVL(A.TRUNCARITEM, 0) TRUNCARITEM,
       NVL(A.GERAICMSLIVROFISCAL,'S') GERAICMSLIVROFISCAL,
       A.UNIDADE,
       A.DESCRICAO1,
       A.TIPOMERCDEPTO,
       A.TIPOMERC,
       A.CODFORNECPROD,
       A.TIPOFORNEC,
       A.NBM,
       A.CODPRODSINTEGRA,
       A.IMPORTADO,
       A.CODPASSEFISCAL,
       A.CODGENEROFISCAL,
       A.PASSELIVRE,
       to_char(A.CODAUXILIAR) CODAUXILIAR,
       A.CODECF,
       A.PESOLIQ,
       A.VOLUME,
       A.QTUNIT,
       A.QTUNITCX,
       A.RUA,
       A.IVARESSARC,
       A.ICMSRESSARC,
       A.ALIQAVULSADARE,
       A.PERCIVAICMANTECIP,
       A.PERCALIQINTICMANTECIP,
       A.PERCALIQEXTICMANTECIP,
       A.TRIBFEDERAL,
       A.TIPOTRIBUTMEDIC,
       A.VLPAUTAICMSANTEC,
       A.CALCCREDIPI,
       A.NUMTRANSITEM,
       A.CODSITTRIBPISCOFINS,
       ROUND(NVL(C.VLICMS,(NVL(A.BASEICMS,0) + NVL(C.VLBASEFRETE,0)+
        NVL(C.VLBASEOUTROS,0))*(NVL(A.PERCICM,0)/100)),2) AS VLICMS,
       C.CODTRIBPISCOFINS,
       C.CODSITTRIBIPI,
       A.DTCANCEL,
       C.VLBASEFRETE,
       C.VLBASEOUTROS,
       A.BCISS,
       A.PERCISS,
       A.VLISS,
       A.ISSRETIDO,
       C.CSLLRETIDO,
       C.VLCSLLRETIDO,
       NVL(C.REGIMEESPECIAL, 'N') REGIMEESPECIAL,
       NVL(C.VLSUBTOTITEM,0) VLSUBTOTITEM,
       C.ORIGMERCTRIB, 
       C.CODMOTIVOICMSDESONERADO,
       NVL(C.VLICMSDESONERACAO, 0) VLICMSDESONERACAO,
       NVL(C.VLICMSDIFERIDO, 0) VLICMSDIFERIDO,
       A.PERCDESCICMSDIF, 
       C.PERDIFEREIMENTOICMS,
       C.CODENQIPI,
       A.PERCBASERED,
       C.VLBASEPARTDEST,
       C.ALIQFCP,
       C.ALIQINTERNADEST,
       C.ALIQINTERORIGPART,
       C.PERCPROVPART,
       C.VLFCPPART,
       C.VLICMSPARTDEST, 
       C.VLICMSPARTREM,
       C.CODCEST,
       A.IVA PERCIVAVENDA,
       A.VLDESCICMSDIF,
       C.CODAGREGACAO,
       A.NUMLOTE,
       C.CODBENEFICIOFISCAL,
       C.CODBENEFICIONOTA,
       C.INDESCALARELEVANTE,
       C.CNPJFABRICANTE,
       C.FABRICANTE, 
       C.VLBASEFCPICMS,		
       C.VLBASEFCPST,	    	
       C.VLBCFCPSTRET,		
       C.PERFCPSTRET,	    	
       C.VLFCPSTRET,			
       C.PERFCPSN,			
       C.VLCREDFCPICMSSN,		
       C.VLFECP	,			
       C.VLACRESCIMOFUNCEP,	
       C.PERACRESCIMOFUNCEP,	
       C.ALIQICMSFECP,	
       C.PERCREDBASEEFET, 
       C.VLBASEEFET, 
       C.PERCICMSEFET, 
       C.VLICMSEFET, 
       NVL(C.VLIPIDEVFORNEC, 0) VLIPIDEVFORNEC, 
       C.CODSERVISS, 
       C.PERCREDBASCALPC, 
       C.NITEMXML 
**/


FROM PCMOV A,
     PCNFSAID SA, 
     PCMOVCOMPLE C
WHERE A.NUMTRANSVENDA = 377868
--A.NUMTRANSVENDA = :NUMTRANSVENDA
  AND A.NUMTRANSITEM = C.NUMTRANSITEM(+) 
  AND A.NUMTRANSVENDA = SA.NUMTRANSVENDA 
  AND A.NUMNOTA = 9681
  AND A.NUMTRANSVENDA > 0
  AND A.STATUS <> 'B'
ORDER BY DESCRICAO
/**
SERIE = '1'
NUMTRANSVENDA = 377868
NUMNOTA = 9681
**/