SELECT 
ENT.NUMTRANSENT AS NUMEROTRANSACAOENTRADA,
ENT.NUMNOTA AS NUMERONOTA,
ENT.SERIE AS SERIE,
ENT.ESPECIE

FROM PCNFENT ENT
WHERE ENT.CODCONT = 100001
AND TO_CHAR(ENT.DTENT, 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -96), 'YYYY')