SELECT 'F' AS CODIGOTIPOITEMVENDA, 
'VENDA BONIFICADA' AS DESCRICAO
FROM DUAL
UNION
SELECT 'N' AS CODIGOTIPOITEMVENDA, 
'VENDA NORMAL' AS DESCRICAO
FROM DUAL
UNION
SELECT 'S' AS CODIGOTIPOITEMVENDA, 
'VENDA BRINDE' AS DESCRICAO
FROM DUAL