Select tab2.*, tab1.STATUS from (
SELECT 
CLI.CODCLI AS CODIGOCLIENTE,
CLI.CLIENTE AS CLIENTE,

CASE WHEN CLI.DTEXCLUSAO IS NOT NULL THEN 'EXCLUÍDO'
WHEN (cli.DTEXCLUSAO IS NULL AND (TRUNC(SYSDATE) - TRUNC(NVL(cli.DTULTCOMP,cli.DTCADASTRO))) >= (SELECT NUMDIASCLIINATIV FROM PCCONSUM)) THEN 'INATIVO'
WHEN (cli.DTEXCLUSAO IS NULL AND (TRUNC(SYSDATE) - TRUNC(NVL(cli.DTULTCOMP,cli.DTCADASTRO))) < (SELECT NUMDIASCLIINATIV FROM PCCONSUM)) THEN 'ATIVO'
END STATUS,
CASE WHEN CLI.DTEXCLUSAO IS NOT NULL THEN 'EXCLUÍDO'
WHEN CLI.DTPRIMCOMPRA IS NULL THEN 'SEM COMPRA'
WHEN CAST (ROUND(SYSDATE - CLI.DTULTCOMP, 0) AS NUMERIC(8,0)) <= 30 THEN 'ATÉ 30 DIAS'
WHEN CAST (ROUND(SYSDATE - CLI.DTULTCOMP, 0) AS NUMERIC(8,0)) > 30 AND CAST (ROUND(SYSDATE - CLI.DTULTCOMP, 0) AS NUMERIC(8,0)) <= 45 THEN 'DE 31 A 45 DIAS'
WHEN CAST (ROUND(SYSDATE - CLI.DTULTCOMP, 0) AS NUMERIC(8,0)) > 45 AND CAST (ROUND(SYSDATE - CLI.DTULTCOMP, 0) AS NUMERIC(8,0)) <= 60 THEN 'DE 46 A 60 DIAS'
WHEN CAST (ROUND(SYSDATE - CLI.DTULTCOMP, 0) AS NUMERIC(8,0)) > 60 AND CAST (ROUND(SYSDATE - CLI.DTULTCOMP, 0) AS NUMERIC(8,0)) <= 90 THEN 'DE 60 A 90 DIAS'
WHEN CAST (ROUND(SYSDATE - CLI.DTULTCOMP, 0) AS NUMERIC(8,0)) > 90 AND CAST (ROUND(SYSDATE - CLI.DTULTCOMP, 0) AS NUMERIC(8,0)) <= 120 THEN 'DE 91 A 120 DIAS'
WHEN CAST (ROUND(SYSDATE - CLI.DTULTCOMP, 0) AS NUMERIC(8,0)) > 120 THEN 'MAIS DE 120 DIAS'
ELSE 'SEM DEFINIÇÃO' END DIASINATIVOS
FROM PCCLIENT CLI
LEFT JOIN PCPRACA PRA ON PRA.CODPRACA = CLI.CODPRACA
LEFT JOIN PCROTAEXP ROT ON ROT.CODROTA = PRA.ROTA
LEFT JOIN PCREGIAO REG ON REG.NUMREGIAO = PRA.NUMREGIAO
LEFT JOIN PCREDECLIENTE RED ON RED.CODREDE = CLI.CODREDE
LEFT JOIN PCATIVI ATI ON ATI.CODATIV = CLI.CODATV1
LEFT JOIN PCCIDADE CID ON CID.CODCIDADE = CLI.CODCIDADE

) tab1,
(
SELECT 
U.CODUSUR AS CODIGORCA,
U.NOME AS RCA,
C.CODCLI AS CODIGOCLIENTE,
C.CLIENTE AS CLIENTE,
'RCA 1' AS TIPOVINCULO
FROM PCCLIENT C
LEFT JOIN PCUSUARI U ON U.CODUSUR = C.CODUSUR1
WHERE U.CODUSUR <> 0
AND C.CODCLI <> 0

UNION

SELECT 
U.CODUSUR AS CODIGORCA,
U.NOME AS RCA,
C.CODCLI AS CODIGOCLIENTE,
C.CLIENTE AS CLIENTE,
'RCA 2' AS TIPOVINCULO
FROM PCCLIENT C
LEFT JOIN PCUSUARI U ON U.CODUSUR = C.CODUSUR2
WHERE U.CODUSUR <> 0
AND C.CODCLI <> 0
UNION

SELECT 
U.CODUSUR AS CODIGORCA,
U.NOME AS RCA,
C.CODCLI AS CODIGOCLIENTE,
C.CLIENTE AS CLIENTE,
'RCA 3' AS TIPOVINCULO
FROM PCCLIENT C
LEFT JOIN PCUSUARI U ON U.CODUSUR = C.CODUSUR3
WHERE U.CODUSUR <> 0
AND C.CODCLI <> 0
UNION


SELECT 
U.CODUSUR AS CODIGORCA,
U.NOME AS RCA,
USUCLI.CODCLI AS CODIGOCLIENTE,
C.CLIENTE,
'MÚLTIPLO' AS TIPOVINCULO
FROM PCUSUARI U
LEFT JOIN  PCUSURCLI USUCLI ON USUCLI.CODUSUR = U.CODUSUR
LEFT JOIN PCCLIENT C ON C.CODCLI = USUCLI.CODCLI
WHERE U.CODUSUR <> 0
AND C.CODCLI <> 0
) tab2
where tab1.CODIGOCLIENTE = tab2.CODIGOCLIENTE