USE [powerbi]
GO

SELECT [CODSUPERVISOR]
      ,[CODGERENTE]
      ,[CODUSUR]
      ,[CODFILIAL]
      ,[CODFORNEC]
      ,[CODCLI]
      ,SUM([VLVENDA]) AS TotalVLVENDA
      ,[QTCLIENTE]
      ,COUNT(CASE WHEN SUM([VLVENDA]) >= 50 THEN [CODUSUR] END) OVER (PARTITION BY [CODCLI]) AS QuantidadeVendasVLVENDA
  INTO [NaturalOne]
  FROM [dbo].[fato_Venda324I]
WHERE [CODFORNEC] = 3309
  AND [CODFILIAL] = 2
  AND MONTH([DATA]) = MONTH(GETDATE()) 
  AND YEAR([DATA]) = YEAR(GETDATE())
GROUP BY [CODSUPERVISOR], [CODGERENTE], [CODUSUR], [CODFILIAL], [CODFORNEC], [CODCLI], [QTCLIENTE]
