----------------------------------
Timestamp: 16:03:41.893
SELECT 
  VLTOTAL, 
  VLDESDOBRADO, 
  CODFISCAL, 
  PERCICM,
  VLBASE, 
  VLICMS, 
  VLISENTAS,
  VLOUTRAS,
  NVL(BASEST,0) BASEST,
  NVL(VLST,0) VLST,
  NVL(BASESTFORANF,0) BASESTFORANF,
  NVL(VLSTFORANF,0) VLSTFORANF,
  NVL(VLBASEIPI,0) VLBASEIPI,
  PERCIPI,
  NVL(VLIPI,0) VLIPI,
  NVL(VLISENTASIPI, 0) VLISENTASIPI,
  NVL(VLOUTRASIPI, 0) VLOUTRASIPI,
  NVL(BCIMPESTADUAL,0) BCIMPESTADUAL,
  NVL(VLIMPESTADUAL,0) VLIMPESTADUAL,
  NVL(VLPIS,0) VLPIS,
  NVL(VLCOFINS,0) VLCOFINS,
  NVL(VLBASEOUTRASIPI, 0) VLBASEOUTASIPI,
  NVL(VLBASEFCPICMS, 0) VLBASEFCPICMS,
  NVL(PERACRESCIMOFUNCEP, 0) PERACRESCIMOFUNCEP,
  NVL(VLACRESCIMOFUNCEP, 0) VLACRESCIMOFUNCEP,
  NVL(VLBASEFCPST, 0) VLBASEFCPST,
  NVL(ALIQICMSFECP, 0) ALIQICMSFECP,
  NVL(VLFECP, 0) VLFECP
FROM 
  PCNFBASESAID
WHERE  NUMNOTA = :NUMNOTA 
AND  NUMTRANSVENDA = :NUMTRANSVENDA
AND  CODFILIALNF = :CODFILIALNF
ORDER BY CODFISCAL, PERCICM, PERCIPI
NUMNOTA = 9681
NUMTRANSVENDA = 377868
CODFILIALNF = '2'
----------------------------------
Timestamp: 16:03:42.053
SELECT
  ROWID,
  ALIQUOTA,
  VLCONTABIL,
  VLBASE,
  VLICMS,
  NUMTRANSVENDA ,
  VLISENTAS,
  CODCONT,
  CODFISCAL,
  TIPO,
  NVL(GERAICMSLIVROFISCAL, 'S') GERAICMSLIVROFISCAL,
  DECODE(NVL(TIPO, '1'), '2', SITTRIBUTIPI, SITTRIBUT) SITTRIBUT,
  VLBASEPARTDEST,
  ALIQFCP,
  ALIQINTERNADEST,
  ALIQINTERORIGPART,
  PERCPROVPART,
  VLFCPPART,
  VLICMSPARTREM,
  VLICMSPARTDEST,
  CODBENEFICIOFISCAL, 
  CODPRODAJUSTE, 
  DESCRICAOPRODAJUSTE, 
  NCMPRODAJUSTE, 
  UNIDADEPRODAJUSTE, 
  VLTOTPRODAJUSTE 
FROM PCNFBASE
WHERE NUMTRANSVENDA = :NUMTRANSVENDA 
  AND NUMTRANSVENDA > 0
ORDER BY ALIQUOTA
NUMTRANSVENDA = 377868
----------------------------------
Timestamp: 16:03:42.128
SELECT A.ROWID, 
       A.DESCRICAO,
       A.EMBALAGEM,
       NVL(A.BASEICMS,0) + NVL(C.VLBASEFRETE,0) +
        NVL(C.VLBASEOUTROS,0) AS BASEICMS,
       A.CODPROD,
       A.CODINTERNO,
       -----------------------------------------------------
      (CASE WHEN ((:SERIE IN ('CF','CP','SF')) OR (SUBSTR(SA.CHAVENFE,21,2) = '65')) THEN 
        ROUND(NVL(C.VLSUBTOTITEM,0),2) 
      WHEN (SA.TIPOVENDA = 'DF' OR A.CODOPER = 'SD') THEN 
        CASE WHEN SA.ROTINACAD NOT LIKE '%1302%' THEN 
          ROUND(A.QTCONT * (NVL(A.PUNITCONT, 0) - NVL(A.VLFRETE, 0)), 2)
        ELSE
          ROUND(A.QTCONT *  NVL(A.PTABELA,0),2)
          - ROUND(A.QTCONT * NVL(A.VLDESCONTO,0), 2) 
          - ROUND(A.QTCONT * NVL(A.VLSUFRAMA,0), 2) 
          - ROUND(A.QTCONT * NVL(C.VLICMSDESONERACAO,0), 2) 
          + ROUND(A.QTCONT * NVL(A.VLFRETE,0), 2) 
          + ROUND(A.QTCONT * NVL(A.VLDESPDENTRONF,0), 2) 
          + ROUND(A.QTCONT * NVL(A.VLSEGURO,0), 2) 
          + ROUND(A.QTCONT * NVL(C.VLFECP,0), 2) 
          + ROUND(A.QTCONT * DECODE(NVL(C.VLIPIDEVFORNEC,0),0,NVL (A.VLIPI, 0),NVL(C.VLIPIDEVFORNEC,0)), 2) 
          + ROUND(A.QTCONT * DECODE(NVL(C.VLSTDEVFORNEC,0),0,NVL (A.ST, 0),NVL(C.VLSTDEVFORNEC,0)), 2) 
        END 
      ELSE 
        ROUND(A.QTCONT * (NVL(A.PUNITCONT,0) - NVL(A.ST,0) - NVL(A.VLIPI,0) - NVL(C.VLIPIDEVFORNEC,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(A.ST,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(A.VLIPI,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(A.VLOUTROS,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(C.VLIPIDEVFORNEC,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(A.VLFRETE,0)), 2) 
      END)
VLTOTAL,
       -----------------------------------------------------
       A.PUNITCONT,
       A.QTCONT,
       A.ST,
       NVL(C.VLSUBTOTDESCONTO, A.VLDESCONTO) AS VLDESCONTO,
       A.VLFRETE,
       A.VLIPI,
       A.VLOUTRASDESP,
       A.VLOUTROS,
       A.DTMOV,
       A.STATUS,
       A.PERCICM,
       A.PERCIPI,
       A.NUMTRANSVENDA,
       A.CODEPTO,
       A.CODSEC,
       A.NUMNOTA,
       A.CODOPER,
       A.CODFILIAL,
       A.CODCLI,
       A.CODFORNEC,
       A.CODUSUR,
       A.CUSTOFIN,
       A.CUSTOCONT,
       A.CUSTOREAL,
       A.VALORULTENT,
       A.BASEICST,
       A.VLBASEIPI,
       A.PERCDESC,
       A.SITTRIBUT,
       A.CODST,
       A.CODFISCAL,
       A.CODFILIALNF,
       A.NUMFORMULARIO,
       A.NUMFORMULARIO2,
       A.CLASSIFICFISCAL,
       A.VLREPASSE,       
       A.NUMIDF,
       A.BASEICMSBCR,
       A.VLICMSBCR,
       A.BASEBCR,
       A.STBCR,
       A.CODFISCALOUTRASDESPENT,
       A.ALIQICMOUTRASDESPENT,
       A.CODFISCALFRETEENT,
       A.ALIQICMFRETEENT,
       A.ROTINALANC,
       A.PERICMSANTECIPADO,
       A.VLCREDPRESUMIDO,
       A.PERCCREDICMPRESUMIDO,
       A.ALIQICMS1,
       A.ALIQICMS2,
       A.PERCIVA,
       A.BASEDIFALIQUOTAS,
       A.PERCDIFALIQUOTAS,
       A.VLDIFALIQUOTAS,
       A.VLBASESTFORANF,
       A.VLDESPADICIONAL,
       A.VLBASEGNRE,
       A.STCLIENTEGNRE,
       A.BASEACRESCIMOPF,
       A.PERACRESCIMOPF,
       A.VLACRESCIMOPF,
       A.PISCOFINSRETIDO,
       A.VLBASEPISCOFINS,
       A.PERPIS,
       A.PERCOFINS,
       A.VLCREDPIS,
       A.VLCREDCOFINS,
       A.VLPIS,
       A.VLCOFINS,
       NVL(A.TRUNCARITEM, 0) TRUNCARITEM,
       NVL(A.GERAICMSLIVROFISCAL,'S') GERAICMSLIVROFISCAL,
       A.UNIDADE,
       A.DESCRICAO1,
       A.TIPOMERCDEPTO,
       A.TIPOMERC,
       A.CODFORNECPROD,
       A.TIPOFORNEC,
       A.NBM,
       A.CODPRODSINTEGRA,
       A.IMPORTADO,
       A.CODPASSEFISCAL,
       A.CODGENEROFISCAL,
       A.PASSELIVRE,
       to_char(A.CODAUXILIAR) CODAUXILIAR,
       A.CODECF,
       A.PESOLIQ,
       A.VOLUME,
       A.QTUNIT,
       A.QTUNITCX,
       A.RUA,
       A.IVARESSARC,
       A.ICMSRESSARC,
       A.ALIQAVULSADARE,
       A.PERCIVAICMANTECIP,
       A.PERCALIQINTICMANTECIP,
       A.PERCALIQEXTICMANTECIP,
       A.TRIBFEDERAL,
       A.TIPOTRIBUTMEDIC,
       A.VLPAUTAICMSANTEC,
       A.CALCCREDIPI,
       A.NUMTRANSITEM,
       A.CODSITTRIBPISCOFINS,
       ROUND(NVL(C.VLICMS,(NVL(A.BASEICMS,0) + NVL(C.VLBASEFRETE,0)+
        NVL(C.VLBASEOUTROS,0))*(NVL(A.PERCICM,0)/100)),2) AS VLICMS,
       C.CODTRIBPISCOFINS,
       C.CODSITTRIBIPI,
       A.DTCANCEL,
       C.VLBASEFRETE,
       C.VLBASEOUTROS,
       A.BCISS,
       A.PERCISS,
       A.VLISS,
       A.ISSRETIDO,
       C.CSLLRETIDO,
       C.VLCSLLRETIDO,
       NVL(C.REGIMEESPECIAL, 'N') REGIMEESPECIAL,
       NVL(C.VLSUBTOTITEM,0) VLSUBTOTITEM,
       C.ORIGMERCTRIB, 
       C.CODMOTIVOICMSDESONERADO,
       NVL(C.VLICMSDESONERACAO, 0) VLICMSDESONERACAO,
       NVL(C.VLICMSDIFERIDO, 0) VLICMSDIFERIDO,
       A.PERCDESCICMSDIF, 
       C.PERDIFEREIMENTOICMS,
       C.CODENQIPI,
       A.PERCBASERED,
       C.VLBASEPARTDEST,
       C.ALIQFCP,
       C.ALIQINTERNADEST,
       C.ALIQINTERORIGPART,
       C.PERCPROVPART,
       C.VLFCPPART,
       C.VLICMSPARTDEST, 
       C.VLICMSPARTREM,
       C.CODCEST,
       A.IVA PERCIVAVENDA,
       A.VLDESCICMSDIF,
       C.CODAGREGACAO,
       A.NUMLOTE,
       C.CODBENEFICIOFISCAL,
       C.CODBENEFICIONOTA,
       C.INDESCALARELEVANTE,
       C.CNPJFABRICANTE,
       C.FABRICANTE, 
       C.VLBASEFCPICMS,		
       C.VLBASEFCPST,	    	
       C.VLBCFCPSTRET,		
       C.PERFCPSTRET,	    	
       C.VLFCPSTRET,			
       C.PERFCPSN,			
       C.VLCREDFCPICMSSN,		
       C.VLFECP	,			
       C.VLACRESCIMOFUNCEP,	
       C.PERACRESCIMOFUNCEP,	
       C.ALIQICMSFECP,	
       C.PERCREDBASEEFET, 
       C.VLBASEEFET, 
       C.PERCICMSEFET, 
       C.VLICMSEFET, 
       NVL(C.VLIPIDEVFORNEC, 0) VLIPIDEVFORNEC, 
       C.CODSERVISS, 
       C.PERCREDBASCALPC, 
       C.NITEMXML 
FROM PCMOV A,
     PCNFSAID SA, 
     PCMOVCOMPLE C
WHERE A.NUMTRANSVENDA = :NUMTRANSVENDA
  AND A.NUMTRANSITEM = C.NUMTRANSITEM(+) 
  AND A.NUMTRANSVENDA = SA.NUMTRANSVENDA 
  AND A.NUMNOTA = :NUMNOTA
  AND A.NUMTRANSVENDA > 0
  AND A.STATUS <> 'B'
ORDER BY DESCRICAO
SERIE = '1'
NUMTRANSVENDA = 377868
NUMNOTA = 9681
----------------------------------
Timestamp: 16:03:42.516
SELECT 
  ROWID,
  NUMTRANS,
  COMPLEMENTO1,
  COMPLEMENTO2,  
  COMPLEMENTO3,
  NOMETABELA 
FROM
  PCCOMPLEMENTO
WHERE
  NUMTRANS = :NUMTRANSVENDA
  AND NUMTRANS > 0
  AND NOMETABELA = 'PCNFSAID'
NUMTRANSVENDA = 377868
----------------------------------
Timestamp: 16:03:42.569
--01 - Dinheiro/02 - Cheque/05 - Cr?dito Loja/10 - Vale Alimentação/11 - Vale Refeição/12 - Vale Presente 
--13 - Vale Combustível/99 - Outros 
SELECT P.NUMTRANSVENDA AS NUM_TRANSACAO, 
       NVL(LPAD(P.CODCOBSEFAZ, 2, '0'), '99') AS CODCOBSEFAZ, 
       P.CODCOB, 
       P.DUPLIC, 
       DECODE(P.CODCOB, 
              'VPP', 
              P.DTEMISSAO, 
              P.DTVENC) AS DTVENC, 
       P.VALOR, 
       NULL AS RAZAO_CRED_CARTAO,  
       NULL AS CNPJ_CRED_CARTAO, 
       NULL AS NUMAUTOR_CARTAO, 
       NULL AS BANDEIRA_CARTAO 
FROM   PCPREST P,  
       PCNFSAID NF,  
       PCCOB 
WHERE  1=1 
AND    P.NUMTRANSVENDA = NF.NUMTRANSVENDA 
AND    P.CODCLI = NF.CODCLI 
AND    PCCOB.CODCOB = P.CODCOB 
AND   NVL(PCCOB.CARTAO,'N') = 'N' 
--DEMAIS FORMAS DE PAGAMENTO 
AND NVL(LPAD(P.CODCOBSEFAZ, 2, '0'), '99') IN ('01','02','05','10','11','12','13','99') 
AND NF.NUMTRANSVENDA = :NUMTRANSACAO 
 
UNION 
 
--duplicata mercantil 
SELECT P.NUMTRANSVENDA AS NUM_TRANSACAO, 
       P.CODCOBSEFAZ, 
       P.CODCOB, 
       P.DUPLIC, 
       DECODE(P.CODCOB, 
              'VPP', 
              P.DTEMISSAO, 
              P.DTVENC) AS DTVENC, 
       P.VALOR, 
       NULL AS RAZAO_CRED_CARTAO,  
       NULL AS CNPJ_CRED_CARTAO, 
       NULL AS NUMAUTOR_CARTAO, 
       NULL AS BANDEIRA_CARTAO 
FROM   PCPREST P,  
       PCNFSAID NF,  
       PCCOB 
WHERE  1=1 
AND    P.NUMTRANSVENDA = NF.NUMTRANSVENDA 
AND    P.CODCLI = NF.CODCLI 
AND    PCCOB.CODCOB = P.CODCOB 
AND   NVL(PCCOB.CARTAO,'N') = 'N' 
--duplicata mercantil 
AND NVL(P.CODCOBSEFAZ, '99') IN ('14', '15') 
AND NF.NUMTRANSVENDA = :NUMTRANSACAO 
 
UNION 
 
--Cartão de Crédito/ Cartão de Débito 
SELECT P.NUMTRANSVENDA AS NUM_TRANSACAO, 
       P.CODCOBSEFAZ, 
       P.CODCOB, 
       0 DUPLIC, 
       NULL AS DTVENC, 
       0 VALOR, 
       P.RAZAOCREDENCCARTAO AS RAZAO_CRED_CARTAO, 
       P.CNPJCREDENCCARTAO AS CNPJ_CRED_CARTAO, 
       P.NSUTEF AS NUMAUTOR_CARTAO, 
       P.BANDEIRACARTAO AS BANDEIRA_CARTAO 
FROM   PCPREST P,  
       PCNFSAID NF,  
       PCCOB 
WHERE  1=1 
AND    P.NUMTRANSVENDA = NF.NUMTRANSVENDA 
AND    P.CODCLI = NF.CODCLI 
AND    PCCOB.CODCOB = P.CODCOB 
AND   NVL(PCCOB.CARTAO,'N') = 'S' 
--Cart?o de Cr?dito/ Cart?o de D?bito 
AND NVL(P.CODCOBSEFAZ, '99') IN ('03','04') 
AND NF.NUMTRANSVENDA = :NUMTRANSACAO 
 
UNION 
 
--90 - Sem Pagamento 
SELECT P.NUMTRANSVENDA AS NUM_TRANSACAO, 
       P.CODCOBSEFAZ, 
       P.CODCOB, 
       0 DUPLIC, 
       NULL AS DTVENC, 
       0 VALOR, 
       NULL AS RAZAO_CRED_CARTAO,  
       NULL AS CNPJ_CRED_CARTAO, 
       NULL AS NUMAUTOR_CARTAO, 
       NULL AS BANDEIRA_CARTAO 
FROM   PCPREST P  
      ,PCCOB 
WHERE  1=1 
AND    PCCOB.CODCOB = P.CODCOB 
AND   NVL(PCCOB.CARTAO,'N') = 'N' 
--Sem Pagamento 
AND NVL(P.CODCOBSEFAZ, '99') = '90' 
AND    P.NUMTRANSVENDA = :NUMTRANSACAO 
UNION 
 
-- Cobrança ST
SELECT P.NUMTRANSVENDA AS NUM_TRANSACAO, 
       NVL(LPAD(P.CODCOBSEFAZ, 2, '0'), '99') AS CODCOBSEFAZ, 
       NVL(P.CODCOB,0) CODCOB, 
       NVL(P.DUPLIC,0) DUPLIC, 
       DECODE(P.CODCOB, 
              'VPP', 
              P.DTEMISSAO, 
              P.DTVENC) AS DTVENC, 
       NVL(P.VALOR,0) VALOR, 
       NULL AS RAZAO_CRED_CARTAO,  
       NULL AS CNPJ_CRED_CARTAO, 
       NULL AS NUMAUTOR_CARTAO, 
       NULL AS BANDEIRA_CARTAO 
FROM   PCPREST P  
WHERE  1=1 
AND    P.NUMTRANSVENDAST = :NUMTRANSACAO  
AND    P.NUMTRANSVENDAST IS NOT NULL 
ORDER BY CODCOBSEFAZ, DTVENC
NUMTRANSACAO = 377868
----------------------------------
Timestamp: 16:03:42.768
SELECT CODIGO,
       NUMTRANSACAO,
       TIPO,
       CHAVECTEREF,
       CHAVENFEREF,
       NUMNOTAREF,
       SERIEREF,
       MODELOREF,
       DTEMISSAOREF,
       CNPJEMITREF,
       UFEMITREF,
       NUMSEQECFREF,
       COOECFREF,
       TIPODOCREF,
       IEPRODRURAL,
       CHAVENFCESATREF
 FROM PCDOCREFERENCIADO
WHERE 1=1
  AND NUMTRANSACAO = :NUMTRANSACAO
  AND TIPO = :TIPO
NUMTRANSACAO = 377868
TIPO = 'S'
----------------------------------
Timestamp: 16:03:42.820
SELECT '' TABLE_CATALOG, IC.TABLE_OWNER TABLE_SCHEMA, IC.TABLE_NAME, '' INDEX_CATALOG, IC.INDEX_OWNER INDEX_SCHEMA, 
IC.INDEX_NAME, IC.COLUMN_NAME, IC.COLUMN_POSITION, DECODE(IC.DESCEND, 'ASC', 0, 1) DESCENDING FROM SYS.ALL_IND_COLUMNS IC, 
SYS.ALL_INDEXES I, SYS.ALL_CONSTRAINTS C WHERE IC.TABLE_OWNER = 'FRIOBOM' AND IC.TABLE_NAME = 'PCMOVCIAP' AND I.UNIQUENESS = 
'UNIQUE' AND        I.OWNER = IC.INDEX_OWNER AND I.INDEX_NAME = IC.INDEX_NAME AND       C.TABLE_NAME (+) = IC.TABLE_NAME AND 
C.INDEX_NAME (+) = IC.INDEX_NAME AND C.OWNER (+)= IC.TABLE_OWNER ORDER BY DECODE(IC.INDEX_OWNER, 'FRIOBOM', 0, 'PUBLIC', 1, 2), 
DECODE(C.CONSTRAINT_TYPE, 'P', 1, 'U', 2, 3), IC.INDEX_OWNER, IC.TABLE_OWNER, IC.TABLE_NAME, IC.INDEX_NAME, IC.COLUMN_POSITION
----------------------------------
Timestamp: 16:03:42.834
----------------------------------
Timestamp: 16:03:42.841
----------------------------------
Timestamp: 16:03:42.849
----------------------------------
Timestamp: 16:03:42.862
SELECT A.ROWID, 
       A.DESCRICAO,
       A.EMBALAGEM,
       NVL(A.BASEICMS,0) + NVL(C.VLBASEFRETE,0) +
        NVL(C.VLBASEOUTROS,0) AS BASEICMS,
       A.CODPROD,
       A.CODINTERNO,
       -----------------------------------------------------
      (CASE WHEN ((:SERIE IN ('CF','CP','SF')) OR (SUBSTR(SA.CHAVENFE,21,2) = '65')) THEN 
        ROUND(NVL(C.VLSUBTOTITEM,0),2) 
      WHEN (SA.TIPOVENDA = 'DF' OR A.CODOPER = 'SD') THEN 
        CASE WHEN SA.ROTINACAD NOT LIKE '%1302%' THEN 
          ROUND(A.QTCONT * (NVL(A.PUNITCONT, 0) - NVL(A.VLFRETE, 0)), 2)
        ELSE
          ROUND(A.QTCONT *  NVL(A.PTABELA,0),2)
          - ROUND(A.QTCONT * NVL(A.VLDESCONTO,0), 2) 
          - ROUND(A.QTCONT * NVL(A.VLSUFRAMA,0), 2) 
          - ROUND(A.QTCONT * NVL(C.VLICMSDESONERACAO,0), 2) 
          + ROUND(A.QTCONT * NVL(A.VLFRETE,0), 2) 
          + ROUND(A.QTCONT * NVL(A.VLDESPDENTRONF,0), 2) 
          + ROUND(A.QTCONT * NVL(A.VLSEGURO,0), 2) 
          + ROUND(A.QTCONT * NVL(C.VLFECP,0), 2) 
          + ROUND(A.QTCONT * DECODE(NVL(C.VLIPIDEVFORNEC,0),0,NVL (A.VLIPI, 0),NVL(C.VLIPIDEVFORNEC,0)), 2) 
          + ROUND(A.QTCONT * DECODE(NVL(C.VLSTDEVFORNEC,0),0,NVL (A.ST, 0),NVL(C.VLSTDEVFORNEC,0)), 2) 
        END 
      ELSE 
        ROUND(A.QTCONT * (NVL(A.PUNITCONT,0) - NVL(A.ST,0) - NVL(A.VLIPI,0) - NVL(C.VLIPIDEVFORNEC,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(A.ST,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(A.VLIPI,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(A.VLOUTROS,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(C.VLIPIDEVFORNEC,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(A.VLFRETE,0)), 2) 
      END)
VLTOTAL,
       -----------------------------------------------------
       A.PUNITCONT,
       A.QTCONT,
       A.ST,
       NVL(C.VLSUBTOTDESCONTO, A.VLDESCONTO) AS VLDESCONTO,
       A.VLFRETE,
       A.VLIPI,
       A.VLOUTRASDESP,
       A.VLOUTROS,
       A.DTMOV,
       A.STATUS,
       A.PERCICM,
       A.PERCIPI,
       A.NUMTRANSVENDA,
       A.CODEPTO,
       A.CODSEC,
       A.NUMNOTA,
       A.CODOPER,
       A.CODFILIAL,
       A.CODCLI,
       A.CODFORNEC,
       A.CODUSUR,
       A.CUSTOFIN,
       A.CUSTOCONT,
       A.CUSTOREAL,
       A.VALORULTENT,
       A.BASEICST,
       A.VLBASEIPI,
       A.PERCDESC,
       A.SITTRIBUT,
       A.CODST,
       A.CODFISCAL,
       A.CODFILIALNF,
       A.NUMFORMULARIO,
       A.NUMFORMULARIO2,
       A.CLASSIFICFISCAL,
       A.VLREPASSE,       
       A.NUMIDF,
       A.BASEICMSBCR,
       A.VLICMSBCR,
       A.BASEBCR,
       A.STBCR,
       A.CODFISCALOUTRASDESPENT,
       A.ALIQICMOUTRASDESPENT,
       A.CODFISCALFRETEENT,
       A.ALIQICMFRETEENT,
       A.ROTINALANC,
       A.PERICMSANTECIPADO,
       A.VLCREDPRESUMIDO,
       A.PERCCREDICMPRESUMIDO,
       A.ALIQICMS1,
       A.ALIQICMS2,
       A.PERCIVA,
       A.BASEDIFALIQUOTAS,
       A.PERCDIFALIQUOTAS,
       A.VLDIFALIQUOTAS,
       A.VLBASESTFORANF,
       A.VLDESPADICIONAL,
       A.VLBASEGNRE,
       A.STCLIENTEGNRE,
       A.BASEACRESCIMOPF,
       A.PERACRESCIMOPF,
       A.VLACRESCIMOPF,
       A.PISCOFINSRETIDO,
       A.VLBASEPISCOFINS,
       A.PERPIS,
       A.PERCOFINS,
       A.VLCREDPIS,
       A.VLCREDCOFINS,
       A.VLPIS,
       A.VLCOFINS,
       NVL(A.TRUNCARITEM, 0) TRUNCARITEM,
       NVL(A.GERAICMSLIVROFISCAL,'S') GERAICMSLIVROFISCAL,
       A.UNIDADE,
       A.DESCRICAO1,
       A.TIPOMERCDEPTO,
       A.TIPOMERC,
       A.CODFORNECPROD,
       A.TIPOFORNEC,
       A.NBM,
       A.CODPRODSINTEGRA,
       A.IMPORTADO,
       A.CODPASSEFISCAL,
       A.CODGENEROFISCAL,
       A.PASSELIVRE,
       to_char(A.CODAUXILIAR) CODAUXILIAR,
       A.CODECF,
       A.PESOLIQ,
       A.VOLUME,
       A.QTUNIT,
       A.QTUNITCX,
       A.RUA,
       A.IVARESSARC,
       A.ICMSRESSARC,
       A.ALIQAVULSADARE,
       A.PERCIVAICMANTECIP,
       A.PERCALIQINTICMANTECIP,
       A.PERCALIQEXTICMANTECIP,
       A.TRIBFEDERAL,
       A.TIPOTRIBUTMEDIC,
       A.VLPAUTAICMSANTEC,
       A.CALCCREDIPI,
       A.NUMTRANSITEM,
       A.CODSITTRIBPISCOFINS,
       ROUND(NVL(C.VLICMS,(NVL(A.BASEICMS,0) + NVL(C.VLBASEFRETE,0)+
        NVL(C.VLBASEOUTROS,0))*(NVL(A.PERCICM,0)/100)),2) AS VLICMS,
       C.CODTRIBPISCOFINS,
       C.CODSITTRIBIPI,
       A.DTCANCEL,
       C.VLBASEFRETE,
       C.VLBASEOUTROS,
       A.BCISS,
       A.PERCISS,
       A.VLISS,
       A.ISSRETIDO,
       C.CSLLRETIDO,
       C.VLCSLLRETIDO,
       NVL(C.REGIMEESPECIAL, 'N') REGIMEESPECIAL,
       NVL(C.VLSUBTOTITEM,0) VLSUBTOTITEM,
       C.ORIGMERCTRIB, 
       C.CODMOTIVOICMSDESONERADO,
       NVL(C.VLICMSDESONERACAO, 0) VLICMSDESONERACAO,
       NVL(C.VLICMSDIFERIDO, 0) VLICMSDIFERIDO,
       A.PERCDESCICMSDIF, 
       C.PERDIFEREIMENTOICMS,
       C.CODENQIPI,
       A.PERCBASERED,
       C.VLBASEPARTDEST,
       C.ALIQFCP,
       C.ALIQINTERNADEST,
       C.ALIQINTERORIGPART,
       C.PERCPROVPART,
       C.VLFCPPART,
       C.VLICMSPARTDEST, 
       C.VLICMSPARTREM,
       C.CODCEST,
       A.IVA PERCIVAVENDA,
       A.VLDESCICMSDIF,
       C.CODAGREGACAO,
       A.NUMLOTE,
       C.CODBENEFICIOFISCAL,
       C.CODBENEFICIONOTA,
       C.INDESCALARELEVANTE,
       C.CNPJFABRICANTE,
       C.FABRICANTE, 
       C.VLBASEFCPICMS,		
       C.VLBASEFCPST,	    	
       C.VLBCFCPSTRET,		
       C.PERFCPSTRET,	    	
       C.VLFCPSTRET,			
       C.PERFCPSN,			
       C.VLCREDFCPICMSSN,		
       C.VLFECP	,			
       C.VLACRESCIMOFUNCEP,	
       C.PERACRESCIMOFUNCEP,	
       C.ALIQICMSFECP,	
       C.PERCREDBASEEFET, 
       C.VLBASEEFET, 
       C.PERCICMSEFET, 
       C.VLICMSEFET, 
       NVL(C.VLIPIDEVFORNEC, 0) VLIPIDEVFORNEC, 
       C.CODSERVISS, 
       C.PERCREDBASCALPC, 
       C.NITEMXML 
FROM PCMOV A,
     PCNFSAID SA, 
     PCMOVCOMPLE C
WHERE A.NUMTRANSVENDA = :NUMTRANSVENDA
  AND A.NUMTRANSITEM = C.NUMTRANSITEM(+) 
  AND A.NUMTRANSVENDA = SA.NUMTRANSVENDA 
  AND A.NUMNOTA = :NUMNOTA
  AND A.NUMTRANSVENDA > 0
  AND A.STATUS <> 'B'
ORDER BY DESCRICAO
SERIE = '1'
NUMTRANSVENDA = 377868
NUMNOTA = 9681
----------------------------------
Timestamp: 16:03:43.283
SELECT
  SUM(ROUND(NVL(A.QTCONT,0) * NVL(A.VLIPI,0),2)) AS VLIPI,
  SUM(ROUND(NVL(A.QTCONT,0) * NVL(C.VLIPIDEVFORNEC,0),2)) AS VLIPIDEVFORNEC,
  SUM(ROUND(NVL(A.QTCONT,0) * NVL(A.VLDESCONTO,0),2)) AS VLDESCONTO,
  SUM(ROUND(NVL(A.QTCONT,0) * NVL(A.ST,0),2)) AS VLST,
  SUM(ROUND(NVL(A.QTCONT,0) * NVL(A.ST,0),2)) AS VLST,
  SUM(ROUND(NVL(A.QTCONT,0) *(NVL(A.VLOUTROS,0)+ NVL(A.VLOUTRASDESP,0)),2)) AS VLOUTROS,
  SUM(ROUND(NVL(A.QTCONT,0) * NVL(C.VLFECP,0),2)) AS VLFECP,
  SUM((CASE WHEN ((:SERIE IN ('CF','CP','SF')) OR (SUBSTR(SA.CHAVENFE,21,2) = '65')) THEN 
        ROUND(NVL(C.VLSUBTOTITEM,0),2) 
      WHEN (SA.TIPOVENDA = 'DF' OR A.CODOPER = 'SD') THEN 
        CASE WHEN SA.ROTINACAD NOT LIKE '%1302%' THEN 
          ROUND(A.QTCONT * (NVL(A.PUNITCONT, 0) - NVL(A.VLFRETE, 0)), 2)
        ELSE
          ROUND(A.QTCONT *  NVL(A.PTABELA,0),2)
          - ROUND(A.QTCONT * NVL(A.VLDESCONTO,0), 2) 
          - ROUND(A.QTCONT * NVL(A.VLSUFRAMA,0), 2) 
          - ROUND(A.QTCONT * NVL(C.VLICMSDESONERACAO,0), 2) 
          + ROUND(A.QTCONT * NVL(A.VLFRETE,0), 2) 
          + ROUND(A.QTCONT * NVL(A.VLDESPDENTRONF,0), 2) 
          + ROUND(A.QTCONT * NVL(A.VLSEGURO,0), 2) 
          + ROUND(A.QTCONT * NVL(C.VLFECP,0), 2) 
          + ROUND(A.QTCONT * DECODE(NVL(C.VLIPIDEVFORNEC,0),0,NVL (A.VLIPI, 0),NVL(C.VLIPIDEVFORNEC,0)), 2) 
          + ROUND(A.QTCONT * DECODE(NVL(C.VLSTDEVFORNEC,0),0,NVL (A.ST, 0),NVL(C.VLSTDEVFORNEC,0)), 2) 
        END 
      ELSE 
        ROUND(A.QTCONT * (NVL(A.PUNITCONT,0) - NVL(A.ST,0) - NVL(A.VLIPI,0) - NVL(C.VLIPIDEVFORNEC,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(A.ST,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(A.VLIPI,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(A.VLOUTROS,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(C.VLIPIDEVFORNEC,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(A.VLFRETE,0)), 2) 
      END)
     ) AS VLTOTITEM
  FROM PCNFSAID SA, PCMOV A, PCMOVCOMPLE C
  WHERE SA.NUMTRANSVENDA = :NUMTRANSACAO
  AND SA.NUMTRANSVENDA = A.NUMTRANSVENDA
  AND NVL(SA.CODFILIALNF, SA.CODFILIAL) = :CODFILIAL
  AND SA.NUMNOTA = A.NUMNOTA
  AND A.NUMTRANSITEM = C.NUMTRANSITEM
SERIE = '1'
NUMTRANSACAO = 377868
CODFILIAL = '2'
----------------------------------
Timestamp: 16:03:43.392
SELECT NUMTRANSENT NUMTRANSORIGENT
FROM PCDEVFORNEC 
WHERE NUMTRANSVENDA = :NUMTRANSVENDA
NUMTRANSVENDA = 377868
----------------------------------
Timestamp: 16:03:43.564
SELECT A.ROWID, 
       A.DESCRICAO,
       A.EMBALAGEM,
       NVL(A.BASEICMS,0) + NVL(C.VLBASEFRETE,0) +
        NVL(C.VLBASEOUTROS,0) AS BASEICMS,
       A.CODPROD,
       A.CODINTERNO,
       -----------------------------------------------------
      (CASE WHEN ((:SERIE IN ('CF','CP','SF')) OR (SUBSTR(SA.CHAVENFE,21,2) = '65')) THEN 
        ROUND(NVL(C.VLSUBTOTITEM,0),2) 
      WHEN (SA.TIPOVENDA = 'DF' OR A.CODOPER = 'SD') THEN 
        CASE WHEN SA.ROTINACAD NOT LIKE '%1302%' THEN 
          ROUND(A.QTCONT * (NVL(A.PUNITCONT, 0) - NVL(A.VLFRETE, 0)), 2)
        ELSE
          ROUND(A.QTCONT *  NVL(A.PTABELA,0),2)
          - ROUND(A.QTCONT * NVL(A.VLDESCONTO,0), 2) 
          - ROUND(A.QTCONT * NVL(A.VLSUFRAMA,0), 2) 
          - ROUND(A.QTCONT * NVL(C.VLICMSDESONERACAO,0), 2) 
          + ROUND(A.QTCONT * NVL(A.VLFRETE,0), 2) 
          + ROUND(A.QTCONT * NVL(A.VLDESPDENTRONF,0), 2) 
          + ROUND(A.QTCONT * NVL(A.VLSEGURO,0), 2) 
          + ROUND(A.QTCONT * NVL(C.VLFECP,0), 2) 
          + ROUND(A.QTCONT * DECODE(NVL(C.VLIPIDEVFORNEC,0),0,NVL (A.VLIPI, 0),NVL(C.VLIPIDEVFORNEC,0)), 2) 
          + ROUND(A.QTCONT * DECODE(NVL(C.VLSTDEVFORNEC,0),0,NVL (A.ST, 0),NVL(C.VLSTDEVFORNEC,0)), 2) 
        END 
      ELSE 
        ROUND(A.QTCONT * (NVL(A.PUNITCONT,0) - NVL(A.ST,0) - NVL(A.VLIPI,0) - NVL(C.VLIPIDEVFORNEC,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(A.ST,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(A.VLIPI,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(A.VLOUTROS,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(C.VLIPIDEVFORNEC,0)), 2) + 
        ROUND((NVL(A.QTCONT,0) * NVL(A.VLFRETE,0)), 2) 
      END)
VLTOTAL,
       -----------------------------------------------------
       A.PUNITCONT,
       A.QTCONT,
       A.ST,
       NVL(C.VLSUBTOTDESCONTO, A.VLDESCONTO) AS VLDESCONTO,
       A.VLFRETE,
       A.VLIPI,
       A.VLOUTRASDESP,
       A.VLOUTROS,
       A.DTMOV,
       A.STATUS,
       A.PERCICM,
       A.PERCIPI,
       A.NUMTRANSVENDA,
       A.CODEPTO,
       A.CODSEC,
       A.NUMNOTA,
       A.CODOPER,
       A.CODFILIAL,
       A.CODCLI,
       A.CODFORNEC,
       A.CODUSUR,
       A.CUSTOFIN,
       A.CUSTOCONT,
       A.CUSTOREAL,
       A.VALORULTENT,
       A.BASEICST,
       A.VLBASEIPI,
       A.PERCDESC,
       A.SITTRIBUT,
       A.CODST,
       A.CODFISCAL,
       A.CODFILIALNF,
       A.NUMFORMULARIO,
       A.NUMFORMULARIO2,
       A.CLASSIFICFISCAL,
       A.VLREPASSE,       
       A.NUMIDF,
       A.BASEICMSBCR,
       A.VLICMSBCR,
       A.BASEBCR,
       A.STBCR,
       A.CODFISCALOUTRASDESPENT,
       A.ALIQICMOUTRASDESPENT,
       A.CODFISCALFRETEENT,
       A.ALIQICMFRETEENT,
       A.ROTINALANC,
       A.PERICMSANTECIPADO,
       A.VLCREDPRESUMIDO,
       A.PERCCREDICMPRESUMIDO,
       A.ALIQICMS1,
       A.ALIQICMS2,
       A.PERCIVA,
       A.BASEDIFALIQUOTAS,
       A.PERCDIFALIQUOTAS,
       A.VLDIFALIQUOTAS,
       A.VLBASESTFORANF,
       A.VLDESPADICIONAL,
       A.VLBASEGNRE,
       A.STCLIENTEGNRE,
       A.BASEACRESCIMOPF,
       A.PERACRESCIMOPF,
       A.VLACRESCIMOPF,
       A.PISCOFINSRETIDO,
       A.VLBASEPISCOFINS,
       A.PERPIS,
       A.PERCOFINS,
       A.VLCREDPIS,
       A.VLCREDCOFINS,
       A.VLPIS,
       A.VLCOFINS,
       NVL(A.TRUNCARITEM, 0) TRUNCARITEM,
       NVL(A.GERAICMSLIVROFISCAL,'S') GERAICMSLIVROFISCAL,
       A.UNIDADE,
       A.DESCRICAO1,
       A.TIPOMERCDEPTO,
       A.TIPOMERC,
       A.CODFORNECPROD,
       A.TIPOFORNEC,
       A.NBM,
       A.CODPRODSINTEGRA,
       A.IMPORTADO,
       A.CODPASSEFISCAL,
       A.CODGENEROFISCAL,
       A.PASSELIVRE,
       to_char(A.CODAUXILIAR) CODAUXILIAR,
       A.CODECF,
       A.PESOLIQ,
       A.VOLUME,
       A.QTUNIT,
       A.QTUNITCX,
       A.RUA,
       A.IVARESSARC,
       A.ICMSRESSARC,
       A.ALIQAVULSADARE,
       A.PERCIVAICMANTECIP,
       A.PERCALIQINTICMANTECIP,
       A.PERCALIQEXTICMANTECIP,
       A.TRIBFEDERAL,
       A.TIPOTRIBUTMEDIC,
       A.VLPAUTAICMSANTEC,
       A.CALCCREDIPI,
       A.NUMTRANSITEM,
       A.CODSITTRIBPISCOFINS,
       ROUND(NVL(C.VLICMS,(NVL(A.BASEICMS,0) + NVL(C.VLBASEFRETE,0)+
        NVL(C.VLBASEOUTROS,0))*(NVL(A.PERCICM,0)/100)),2) AS VLICMS,
       C.CODTRIBPISCOFINS,
       C.CODSITTRIBIPI,
       A.DTCANCEL,
       C.VLBASEFRETE,
       C.VLBASEOUTROS,
       A.BCISS,
       A.PERCISS,
       A.VLISS,
       A.ISSRETIDO,
       C.CSLLRETIDO,
       C.VLCSLLRETIDO,
       NVL(C.REGIMEESPECIAL, 'N') REGIMEESPECIAL,
       NVL(C.VLSUBTOTITEM,0) VLSUBTOTITEM,
       C.ORIGMERCTRIB, 
       C.CODMOTIVOICMSDESONERADO,
       NVL(C.VLICMSDESONERACAO, 0) VLICMSDESONERACAO,
       NVL(C.VLICMSDIFERIDO, 0) VLICMSDIFERIDO,
       A.PERCDESCICMSDIF, 
       C.PERDIFEREIMENTOICMS,
       C.CODENQIPI,
       A.PERCBASERED,
       C.VLBASEPARTDEST,
       C.ALIQFCP,
       C.ALIQINTERNADEST,
       C.ALIQINTERORIGPART,
       C.PERCPROVPART,
       C.VLFCPPART,
       C.VLICMSPARTDEST, 
       C.VLICMSPARTREM,
       C.CODCEST,
       A.IVA PERCIVAVENDA,
       A.VLDESCICMSDIF,
       C.CODAGREGACAO,
       A.NUMLOTE,
       C.CODBENEFICIOFISCAL,
       C.CODBENEFICIONOTA,
       C.INDESCALARELEVANTE,
       C.CNPJFABRICANTE,
       C.FABRICANTE, 
       C.VLBASEFCPICMS,		
       C.VLBASEFCPST,	    	
       C.VLBCFCPSTRET,		
       C.PERFCPSTRET,	    	
       C.VLFCPSTRET,			
       C.PERFCPSN,			
       C.VLCREDFCPICMSSN,		
       C.VLFECP	,			
       C.VLACRESCIMOFUNCEP,	
       C.PERACRESCIMOFUNCEP,	
       C.ALIQICMSFECP,	
       C.PERCREDBASEEFET, 
       C.VLBASEEFET, 
       C.PERCICMSEFET, 
       C.VLICMSEFET, 
       NVL(C.VLIPIDEVFORNEC, 0) VLIPIDEVFORNEC, 
       C.CODSERVISS, 
       C.PERCREDBASCALPC, 
       C.NITEMXML 
FROM PCMOV A,
     PCNFSAID SA, 
     PCMOVCOMPLE C
WHERE A.NUMTRANSVENDA = :NUMTRANSVENDA
  AND A.NUMTRANSITEM = C.NUMTRANSITEM(+) 
  AND A.NUMTRANSVENDA = SA.NUMTRANSVENDA 
  AND A.NUMNOTA = :NUMNOTA
  AND A.NUMTRANSVENDA > 0
  AND A.STATUS <> 'B'
ORDER BY DESCRICAO
SERIE = '1'
NUMTRANSVENDA = 377868
NUMNOTA = 9681