SELECT
CLI.CODCLI AS CODIGOCLIENTE,
CLI.DTULTCOMP AS DATAULTIMACOMPRA,
CAST (ROUND(SYSDATE - CLI.DTULTCOMP, 0) AS NUMERIC(8,0)) AS DIASULTIMAVENDA,
CLI.DTCADASTRO AS DATACADASTRO,
CAST (ROUND(SYSDATE - CLI.DTCADASTRO, 0) AS NUMERIC(8,0))  AS DIASCADASTRO,
CAST (ROUND(SYSDATE - CLI.DTPRIMCOMPRA, 0) AS NUMERIC(8,0))  AS DIASPRIMEIRACOMPRA,
CAST (ROUND(SYSDATE - CLI.DTULTCONTATOCOB , 0) AS NUMERIC(8,0))  AS DIASULTIMACOBRANCA,
CLI.LIMCRED AS LIMITECREDITO,
CAST ( (SELECT SUM(NVL(VALOR,0)) VALOR              
FROM PCPREST                              
WHERE DTPAG IS NULL                        
AND CODCLI = CLI.CODCLI) AS NUMERIC(18,6)) AS VALORRECEBER,

CAST( (SELECT SUM (NVL (VLATEND, 0)) AS TOTAL
FROM   PCPEDC
WHERE  POSICAO IN ('L', 'M')
AND    DTCANCEL IS NULL
AND    CODCLI = CLI.CODCLI) AS NUMERIC(18,6)) AS VALORPEDIDOFATURAR,

CAST( (SELECT SUM (NVL (VALORDESCFIN, 0)) AS DESCFIN
FROM   PCPEDC
WHERE  POSICAO IN ('L', 'M')
AND    DTCANCEL IS NULL
AND    CODCLI = CLI.CODCLI) AS NUMERIC(18,6)) AS VALORDESCONTOFINANCEIRO

FROM PCCLIENT CLI