SELECT GRI.CODGRUPO AS CODIGOGRUPO,
GRI.CODITEM  AS CODIGOPRODUTO,
GRC.CODFILIAL AS CODIGOFILIAL,
CASE WHEN GRI.DTEXCLUSAO IS NULL THEN 'ATIVO'
ELSE 'EXCLUIDO' END AS SITUACAOITEM
FROM PCGRUPOSCAMPANHAI GRI
INNER JOIN PCGRUPOSCAMPANHAC GRC ON GRC.CODGRUPO = GRI.CODGRUPO
WHERE GRC.TIPO = 'GP'