SELECT 
PCPRODUT.CODPROD AS CODIGOPRODUTO,                                            
CAST( NVL(PCTABPR.PVENDA1, 0) AS NUMERIC(18,6)) AS VALORUNITARIOVENDA,
CAST( NVL(PCPRODUT.TEMREPOS, 0) AS NUMERIC(8,0))  AS TEMPOREPOSICAO,
CAST( NVL(PCFORNEC.PRAZOENTREGA, 0) AS NUMERIC(8,0)) AS PRAZOENTREGA,
PCTABPR.MARGEM AS MARGEMIDEAL,
PCPRODUT.DTCADASTRO AS DATACADASTRO,
CAST( ROUND(SYSDATE - NVL(PCPRODUT.DTCADASTRO, SYSDATE), 0) AS NUMERIC(8,0))  AS DIASCADASTRO,
PCTABPR.PERDESCMAXTAB AS DESCONTOMAXIMO,
PCTABPR.PERDESCMAXTABBALCAO AS DESCONTOMAXIMOBALCAO,
PCPRODUT.PESOBRUTO AS PESOBRUTO,
PCPRODUT.PESOLIQ AS PESOLIQUIDO,
PCPRODUT.VOLUME AS VOLUME,
PCPRODUT.QTUNIT AS QUANTIDADEUNITARIA,
PCPRODUT.QTUNITCX AS QUANTIDADEUNITARIACAIXA
FROM PCPRODUT, PCTABPR, PCFORNEC  
 WHERE PCPRODUT.CODPROD = PCTABPR.CODPROD
 AND PCFORNEC.CODFORNEC = PCPRODUT.CODFORNEC
 AND PCTABPR.NUMREGIAO IN (1)