SELECT 
PCAUTORI.NRAUTORIZACAO AS NUMEROAUTORIZACAO,
TRUNC(PCAUTORI.DATAAUTORIZACAO) DATAAUTORIZACAO,
PCAUTORI.CODFUNCUTILIZ AS CODIGOFUNCIONARIORESPONSAVEL,             
PCAUTORI.CODFILIAL AS CODIGOFILIAL,              
PCAUTORI.CODCLI AS CODIGOCLIENTE,
PCPEDC.CODUSUR AS CODIGORCA,
PCAUTORI.CODPROD AS CODIGOPRODUTO,
PCAUTORI.CODPLPAG AS CODIGOPLANOPAGAMENTO, 
PCPEDC.CODCOB AS CODIGOCOBRANCA,   
PCAUTORI.NUMPED AS NUMEROPEDIDO, 
PCAUTORI.PVENDAATUAL AS VALORORIGINAL,                                                     
PCAUTORI.PVENDIDO AS VALORVENDIDO,
(SELECT SUM(NVL(QT,0))  FROM PCPEDI                                       
         WHERE PCPEDI.NUMPED  = PCAUTORI.NUMPED                                    
         AND PCPEDI.CODPROD = PCAUTORI.CODPROD) AS QUANTIDADE,
         
         CAST((SELECT SUM(NVL(VLCUSTOFIN,0)) 
         FROM PCPEDI                               
         WHERE PCPEDI.NUMPED  = PCAUTORI.NUMPED                                      
         AND PCPEDI.CODPROD = PCAUTORI.CODPROD) AS NUMERIC(18,6)) AS VALORCUSTO             
FROM PCAUTORI, PCUSUARI, PCEMPR, PCCLIENT, PCPRODUT, PCPLPAG, PCPEDC                      
WHERE PCAUTORI.CODUSUR = PCUSUARI.CODUSUR                 
AND PCAUTORI.CODCLI = PCCLIENT.CODCLI
AND PCAUTORI.CODPROD = PCPRODUT.CODPROD 
AND PCAUTORI.CODPLPAG = PCPLPAG.CODPLPAG 
AND PCAUTORI.CODFUNCCADASTRO = PCEMPR.MATRICULA
AND PCAUTORI.NUMPED = PCPEDC.NUMPED
AND PCAUTORI.DATA_UTILIZACAO IS NOT NULL
AND  TO_CHAR(PCAUTORI.DATAAUTORIZACAO , 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -36), 'YYYY')