SELECT 
 PCMOVCRFOR.NUMTRANSCRFOR AS NUMEROTRANSACAO,
 PCMOVCRFOR.DATA AS DATAMOVIMENTACAO,      
 PCMOVCRFOR.CODFORNEC AS CODIGOFORNECEDOR,
 PCMOVCRFOR.NUMVERBA AS NUMEROVERBA,
 PCMOVCRFOR.CODFILIAL AS CODIGOFILIAL,
 PCMOVCRFOR.DATA AS DATAVENCIMENTO,       
 CAST ( DECODE(PCMOVCRFOR.TIPO, 'D', PCMOVCRFOR.VALOR, 0) AS NUMERIC(18,6) ) AS VALORDEBITO,       
 CAST ( DECODE(PCMOVCRFOR.TIPO, 'C', PCMOVCRFOR.VALOR *(-1), 0) AS NUMERIC(18,6) ) AS VALORCREDITO
 FROM PCMOVCRFOR,                                                        
      PCVERBA                                         
 WHERE PCMOVCRFOR.NUMVERBA = PCVERBA.NUMVERBA(+)