select 
tab_r.CodGerente
, tab_r.CodSupervisor
, tab_r.Nome_Superv
, tab_r.CodUsur
, tab_r.nome
, tab_r.CodCidade
, tab_r.NomeCidade
, tab_r.QtCliAtivos
, tab_r.QTCLIPOS
, round(tab_r.QTCLIPOS/tab_r.QtCliAtivos * 100,2) AS "% Pos."
, tab_r.QT
, tab_r.PVENDA 
 from 
(Select
tab2_qtcliativos.QTCLIATIVOS 
,tab1_base.codgerente, tab1_base.codsupervisor, tab1_base.Nome_Superv, tab1_base.codusur, tab1_base.nome, tab1_base.CODCIDADE, tab1_base.NOMECIDADE,
       tab1_base.QT,
       tab1_base.QTCLIPOS,
       tab1_base.PVENDA


from (
SELECT pcsuperv.codgerente
    , PCUSUari.codsupervisor, pcsuperv.nome As Nome_Superv
    , PCUSUARI.codusur, PCUSUARI.nome
    , PCCIDADE.CODCIDADE, PCCIDADE.NOMECIDADE,
       SUM(PCPEDI.QT) AS QT,
       COUNT(DISTINCT(PCPEDC.CODCLI)) QTCLIPOS,
       SUM(ROUND(NVL(PCPEDI.QT,0)*(NVL(PCPEDI.PVENDA, 0) + NVL(PCPEDI.VLOUTRASDESP, 0) + NVL(PCPEDI.VLFRETE, 0)),2)) AS PVENDA,
       SUM(ROUND(NVL(PCPRODUT.PESOBRUTO,0)*NVL(PCPEDI.QT,0),2)) AS TOTPESO,
       SUM(ROUND(NVL(PCPRODUT.VOLUME,0)*NVL(PCPEDI.QT,0),2)) Volume,
       ROUND(SUM(NVL(PCPRODUT.LITRAGEM, 0)*NVL(PCPEDI.QT,0)) ,2) LITRAGEM,
       SUM(NVL(PCPEDI.QT,0) / DECODE(NVL(PCPRODUT.QTUNIT,0),0,1,NVL(PCPRODUT.QTUNIT,1))) TOTQTUNIT,
       SUM(NVL(PCPEDI.QT,0) / DECODE(NVL(PCPRODUT.QTUNITCX,0),0,1,NVL(PCPRODUT.QTUNITCX,1))) TOTQTUNITCX
FROM PCPEDI, PCPEDC, PCPRODUT, PCFORNEC, PCDEPTO, PCUSUARI, PCCLIENT, PCATIVI, PCPRACA, PCCIDADE, pcsuperv
WHERE PCPEDI.NUMPED = PCPEDC.NUMPED
AND PCUSUARI.CODSUPERVISOR NOT IN ('9999')
AND pcsuperv.codsupervisor = PCUSUARI.CODSUPERVISOR
AND PCPEDC.DATA BETWEEN :DATAI AND :DATAF

AND pcsuperv.codgerente in (:Cod_Ger)
AND PCUSUari.codsupervisor in (:Cod_Superv)
AND PCUSUARI.codusur in (:Cod_Rca)

AND PCPEDC.CODFILIAL IN ('2')
AND PCPEDC.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
 AND NVL(PCPEDI.BONIFIC, 'N') =  'N' 
AND PCPEDC.CODCLI      = PCCLIENT.CODCLI
AND PCCLIENT.CODATV1   = PCATIVI.CODATIV(+)
AND PCPEDC.DTCANCEL IS NULL
AND PCPEDI.CODPROD     = PCPRODUT.CODPROD(+)
AND PCPRODUT.CODEPTO   = PCDEPTO.CODEPTO(+)
AND PCPRACA.CODPRACA   = PCCLIENT.CODPRACA(+)
AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC(+)
AND PCPEDC.CODUSUR     = PCUSUARI.CODUSUR(+)
AND PCCLIENT.CODCIDADE = PCCIDADE.CODCIDADE(+)
GROUP BY pcsuperv.codgerente, PCUSUari.codsupervisor, pcsuperv.nome, PCUSUARI.codusur, PCUSUARI.nome, PCCIDADE.CODCIDADE, PCCIDADE.NOMECIDADE
ORDER BY PVENDA DESC
) tab1_base,
(
SELECT 
        PCUSUArI.codusur,
 COUNT  (DISTINCT(PCCLIENT.CODCLI)) QTCLIATIVOS 
  FROM  PCCLIENT, PCUSUARI
 WHERE  ( (PCCLIENT.CODUSUR1 = PCUSUARI.CODUSUR)  
    OR  ( (PCCLIENT.CODUSUR2 = PCUSUARI.CODUSUR ) 
   AND  ( NVL(PCCLIENT.codusur1,0) <> NVL(PCCLIENT.codusur2,0)))  
    OR  EXISTS (SELECT PCUSURCLI.CODUSUR
                  FROM PCUSURCLI
                 WHERE PCUSURCLI.CODUSUR = PCUSUARI.CODUSUR
   AND  NVL(PCUSURCLI.CODUSUR,0) <> NVL(PCCLIENT.codusur1,0)
   AND  NVL(PCUSURCLI.CODUSUR,0) <> NVL(PCCLIENT.codusur2,0)
   AND  PCUSURCLI.CODCLI  = PCCLIENT.CODCLI))
   AND  ( PCCLIENT.DTULTCOMP >= trunc(sysdate - (SELECT nvl(numdiascliinativ,0) FROM pcconsum) ) )
Group BY PCUSUArI.codusur
) tab2_qtcliativos
Where tab1_base.codusur = tab2_qtcliativos.codusur

) tab_r
 