SELECT DISTINCT(PCCARREG.NUMCAR) AS NUMEROCARREGAMENTO
     , PCCARREG.CODVEICULO AS CODIGOVEICULO
     , PCCARREG.CODMOTORISTA AS CODIGOMOTORISTA
     , PCEMPR.CODFILIAL AS CODIGOFILIAL
     , PCEMPR.MATRICULA AS CODIGOFUNCIONARIO
     , PCROTAEXP.CODROTA AS CODIGOROTA
     , PCCARREG.CODROTAPRINC AS CODIGOROTAPRINCIPAL
     , PCCARREG.DTFECHA AS DATAFECHAMENTO
     , PCCARREG.DTFAT AS DATAFATURAMENTO
     , PCCARREG.DTSAIDA AS DATASAIDA
     , PCCARREG.NUMNOTAS AS QUANTIDADENOTA
     , PCVEICUL.VOLUME AS VOLUMEVEICULO
	 , PCCARREG.TOTVOLUME AS VOLUMETOTAL
	 , PCCARREG.TOTPESO AS PESOTOTAL
	 , PCCARREG.VLTOTAL AS VALORTOTAL

 FROM PCCARREG   
     , PCEMPR   
     , PCROTAEXP   
     , PCVEICUL   
 WHERE PCCARREG.CODMOTORISTA = PCEMPR.MATRICULA(+)   
   AND PCCARREG.CODROTAPRINC = PCROTAEXP.CODROTA(+)  
   AND PCCARREG.CODVEICULO = PCVEICUL.CODVEICULO(+)
  AND PCCARREG.NUMCAR BETWEEN 0 AND 99999999 
  AND NOT EXISTS (SELECT PCPEDC.NUMCAR
             FROM PCPEDC 
             WHERE PCPEDC.ORIGEMPED IN ('B', 'R', 'A') 
                   AND PCPEDC.NUMCAR = PCCARREG.NUMCAR)
AND PCCARREG.DTFECHA IS NULL 
AND PCCARREG.DT_CANCEL IS NULL
AND PCCARREG.DTSAIDA >= ADD_MONTHS(SYSDATE, -1)
ORDER BY NUMCAR