SELECT 
PCMOV.NUMPED AS NUMEROPEDIDO,
PCMOV.NUMTRANSVENDA AS NUMEROTRANSACAOVENDA,
PCMOV.CODPROD AS CODIGOPRODUTO,
PCMOV.CODUSUR AS CODIGORCA,
PCMOV.CODCLI AS CODIGOCLIENTE,
PCMOV.CODFILIAL AS CODIGOFILIAL,
CAST(NVL(PCMOV.CODAUXILIAR, PCPRODUT.CODAUXILIAR) AS NUMERIC(20,0)) AS CODIGOAUXILIAR,
PCNFSAID.CODCOB AS CODIGOCOBRANCA,
PCNFSAID.CODPLPAG AS CODIGOPLANOPAGAMENTO,
PCNFSAID.NUMCAR AS NUMEROCARREGAMENTO,
TO_CHAR(PCNFSAID.DTSAIDA, 'YYYY-MM-DD') AS DATAFATURAMENTO,
 
CAST(DECODE(PCMOV.CODOPER,
       'S',
       (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT, PCMOV.QT),0)),
       'ST',
       (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT), 0)),
       'SM',
       (NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.QTCONT,PCMOV.QT),0)),
       0)AS NUMERIC(18,6)) AS QUANTIDADE,

CAST((NVL(DECODE(PCNFSAID.CONDVENDA,7,PCMOV.PUNITCONT,NVL(PCMOV.PUNIT, 0) +
                                                        NVL(PCMOV.VLFRETE, 0) +
                                                        NVL(PCMOV.VLOUTRASDESP, 0) +
                                                        NVL(PCMOV.VLFRETE_RATEIO, 0) +
                                                        NVL(PCMOV.VLOUTROS, 0) -
                                                        NVL(PCMOV.VLREPASSE, 0)  ),                                                        
                                                        0))AS NUMERIC(18,6)) AS VALORUNITARIO,
                                                        
                                                        
cast(
         NVL(
          NVL((CASE
                WHEN ROUND(PCMOVCOMPLE.VLSUBTOTITEM, 2) IS NOT NULL THEN
                 (CASE
                   WHEN (SELECT TIPOVLVENDA FROM PCPARAMPLANOVOO) = 'DEDUZIRFRETE' THEN
                    (ROUND(PCMOVCOMPLE.VLSUBTOTITEM, 2) - (ROUND(NVL(PCMOV.VLFRETE, 0), 2) * PCMOV.QT))
                          WHEN (SELECT TIPOVLVENDA FROM PCPARAMPLANOVOO) = 'DEDUZIROUTRASDESP' THEN
                           (ROUND(PCMOVCOMPLE.VLSUBTOTITEM, 2) - (ROUND(NVL(PCMOV.VLOUTRASDESP, 0), 2) * PCMOV.QT))
                          WHEN (SELECT TIPOVLVENDA FROM PCPARAMPLANOVOO) = 'DEDUZIRAMBOS' THEN
                           (ROUND(PCMOVCOMPLE.VLSUBTOTITEM, 2) - (ROUND(NVL(PCMOV.VLFRETE, 0), 2) * PCMOV.QT) -
                           (ROUND(NVL(PCMOV.VLOUTRASDESP, 0), 2) * PCMOV.QT))
                   ELSE
                    ROUND(PCMOVCOMPLE.VLSUBTOTITEM, 2)
                 END)
                ELSE
                 NULL
               END)
         , (ROUND(
             (DECODE(PCMOV.CODOPER,
                     'S', (NVL(DECODE(PCNFSAID.CONDVENDA, 7, DECODE(NVL(PCMOV.TIPOITEM, 'C'), 'C', PCMOV.QT, PCMOV.QTCONT), PCMOV.QT), 0)),
                     'ST', (NVL(DECODE(PCNFSAID.CONDVENDA, 7, DECODE(NVL(PCMOV.TIPOITEM, 'C'), 'C', PCMOV.QT, PCMOV.QTCONT), PCMOV.QT), 0)),
                     'SM', (NVL(DECODE(PCNFSAID.CONDVENDA, 7, DECODE(NVL(PCMOV.TIPOITEM, 'C'), 'C', PCMOV.QT, PCMOV.QTCONT), PCMOV.QT), 0)),
                     0))
             * ((CASE
                  WHEN (SELECT TIPOVLVENDA FROM PCPARAMPLANOVOO) = 'DEDUZIRFRETE'
                  THEN
                   (NVL(
                     DECODE(PCNFSAID.CONDVENDA,
                            7, DECODE(NVL(PCMOV.TIPOITEM, 'C'), 'C', NVL(PCMOV.PUNIT, 0), PCMOV.PUNITCONT) + NVL(PCMOV.VLOUTRASDESP, 0) + NVL(PCMOV.VLFRETE_RATEIO, 0) + NVL(PCMOV.VLOUTROS, 0),
                            NVL(PCMOV.PUNIT, 0) + NVL(PCMOV.VLOUTRASDESP, 0) + NVL(PCMOV.VLFRETE_RATEIO, 0) + NVL(PCMOV.VLOUTROS, 0))
                   , 0))
                  WHEN (SELECT TIPOVLVENDA FROM PCPARAMPLANOVOO) = 'DEDUZIROUTRASDESP'
                  THEN
                   (NVL(
                     DECODE(PCNFSAID.CONDVENDA,
                            7, DECODE(NVL(PCMOV.TIPOITEM, 'C'), 'C', NVL(PCMOV.PUNIT, 0), PCMOV.PUNITCONT) + NVL(PCMOV.VLFRETE, 0) + NVL(PCMOV.VLFRETE_RATEIO, 0) + NVL(PCMOV.VLOUTRASDESP, 0),
                            NVL(PCMOV.PUNIT, 0) + NVL(PCMOV.VLFRETE, 0) + NVL(PCMOV.VLFRETE_RATEIO, 0) + NVL(PCMOV.VLOUTRASDESP, 0))
                   , 0))
                  WHEN (SELECT TIPOVLVENDA FROM PCPARAMPLANOVOO) = 'DEDUZIRAMBOS'
                  THEN
                   (NVL(
                     DECODE(PCNFSAID.CONDVENDA,
                            7, DECODE(NVL(PCMOV.TIPOITEM, 'C'), 'C', NVL(PCMOV.PUNIT, 0), PCMOV.PUNITCONT) + NVL(PCMOV.VLFRETE_RATEIO, 0) + NVL(PCMOV.VLOUTRASDESP, 0),
                            NVL(PCMOV.PUNIT, 0) + NVL(PCMOV.VLFRETE_RATEIO, 0) + NVL(PCMOV.VLOUTRASDESP, 0))
                   , 0))
                  ELSE
                   (NVL(
                     DECODE(
                      PCNFSAID.CONDVENDA
                    , 7
                    ,   DECODE(NVL(PCMOV.TIPOITEM, 'C'), 'C', NVL(PCMOV.PUNIT, 0), PCMOV.PUNITCONT)
                      + NVL(PCMOV.VLFRETE, 0)
                      + NVL(PCMOV.VLOUTRASDESP, 0)
                      + NVL(PCMOV.VLFRETE_RATEIO, 0)
                      + NVL(PCMOV.VLOUTROS, 0)
                    , NVL(PCMOV.PUNIT, 0) + NVL(PCMOV.VLFRETE, 0) + NVL(PCMOV.VLOUTRASDESP, 0) + NVL(PCMOV.VLFRETE_RATEIO, 0) + NVL(PCMOV.VLOUTROS, 0))
                   , 0))
                 END)
                - NVL(PCMOV.VLIPI, 0)
                - NVL(PCMOV.ST, 0))
           , 2))
           + ROUND(
              NVL(PCMOV.VLIPI, 0)
              * (DECODE(PCMOV.CODOPER,
                        'S', (NVL(DECODE(PCNFSAID.CONDVENDA, 7, DECODE(NVL(PCMOV.TIPOITEM, 'C'), 'C', PCMOV.QT, PCMOV.QTCONT), PCMOV.QT), 0)),
                        'ST', (NVL(DECODE(PCNFSAID.CONDVENDA, 7, DECODE(NVL(PCMOV.TIPOITEM, 'C'), 'C', PCMOV.QT, PCMOV.QTCONT), PCMOV.QT), 0)),
                        'SM', (NVL(DECODE(PCNFSAID.CONDVENDA, 7, DECODE(NVL(PCMOV.TIPOITEM, 'C'), 'C', PCMOV.QT, PCMOV.QTCONT), PCMOV.QT), 0)),
                        0))
            , 2)
           + ROUND(
              NVL(PCMOV.ST, 0)
              * (DECODE(PCMOV.CODOPER,
                        'S', (NVL(DECODE(PCNFSAID.CONDVENDA, 7, DECODE(NVL(PCMOV.TIPOITEM, 'C'), 'C', PCMOV.QT, PCMOV.QTCONT), PCMOV.QT), 0)),
                        'ST', (NVL(DECODE(PCNFSAID.CONDVENDA, 7, DECODE(NVL(PCMOV.TIPOITEM, 'C'), 'C', PCMOV.QT, PCMOV.QTCONT), PCMOV.QT), 0)),
                        'SM', (NVL(DECODE(PCNFSAID.CONDVENDA, 7, DECODE(NVL(PCMOV.TIPOITEM, 'C'), 'C', PCMOV.QT, PCMOV.QTCONT), PCMOV.QT), 0)),
                        0))
            , 2))
        , 0)
       as numeric(18,6))
        as VALORTOTAL,                                                       
 
  NVL(
    DECODE(PCNFSAID.CONDVENDA,
    5,
    DECODE(NVL(PCMOV.PBONIFIC, 0),
    0,
    PCMOV.PTABELA + NVL(PCMOV.VLDESCONTO, 0),
    PCMOV.PBONIFIC + NVL(PCMOV.VLDESCONTO, 0)),
    6,
    DECODE(NVL(PCMOV.PBONIFIC, 0),
    0,
    PCMOV.PTABELA + NVL(PCMOV.VLDESCONTO, 0),
    PCMOV.PBONIFIC + NVL(PCMOV.VLDESCONTO, 0)),
    11,
    DECODE(NVL(PCMOV.PBONIFIC, 0),
    0,
    PCMOV.PTABELA + NVL(PCMOV.VLDESCONTO, 0),
    PCMOV.PBONIFIC + NVL(PCMOV.VLDESCONTO, 0)),
    12,
    DECODE(NVL(PCMOV.PBONIFIC, 0),
    0,
    PCMOV.PTABELA + NVL(PCMOV.VLDESCONTO, 0),
    PCMOV.PBONIFIC + NVL(PCMOV.VLDESCONTO, 0)),
    0),
0) as VALORUNITARIOBONIFICADO,
 NVL((NVL(PCMOV.QT, 0) *
           DECODE(PCNFSAID.CONDVENDA, 5, 1, 6, 1, 11, 1, 12, 1, 0)),
           0) as QUANTIDADEBONIFICADA,
PCMOV.PTABELA AS VALORUNITARIOTABELA,
PCMOV.CUSTOFIN AS VALORUNITARIOCUSTO,
(PCMOV.QT * PCMOV.CUSTOFIN) AS VALORTOTALCUSTO,
PCMOV.PESOLIQ AS PESOUNITARIOLIQUIDO,
PCPRODUT.PESOBRUTO AS PESOUNITARIOBRUTO,
 NVL(ROUND(NVL(PCPRODUT.PESOBRUTO, 0) * NVL(PCMOV.QT, 0), 2), 0) AS PESOBRUTOTOAL,
PCMOV.VOLUME AS VOLUMEUNITARIO,
PCMOV.ST AS VALORST,
PCMOV.VLPIS AS VALORPIS,
PCMOV.VLCOFINS AS VALORCOFINS,
PCMOV.VLIPI AS VALORIPI,
DECODE(PCNFSAID.CONDVENDA, 0, 0, PCMOV.PERCOM*0.01) AS PERCENTUALCOMISSAO,
DECODE(PCPRODUT.QTUNITCX,0,1)  AS QUANTIDADECAIXA,
NVL(PCMOV.VLVERBACMVCLI,0) + NVL(PCMOV.VLVERBACMV,0) AS VALORVERBAUNITARIO,
PCMOV.VLFRETE_RATEIO AS VALORFRETE,
PCMOV.VLOUTRASDESP AS VALOROUTRASDESPESAS


FROM PCNFSAID, PCPLPAG
      , PCCLIENT
      , PCPRACA
      , PCMOV
      , PCPRODUT
      , PCMOVCOMPLE
  WHERE PCNFSAID.NUMTRANSVENDA = PCMOV.NUMTRANSVENDA
    AND PCNFSAID.NUMNOTA = PCMOV.NUMNOTA
    AND PCMOV.CODPROD = PCPRODUT.CODPROD
    AND PCCLIENT.CODPRACA = PCPRACA.CODPRACA
    AND PCNFSAID.CODCLI = PCCLIENT.CODCLI
    AND NVL(PCNFSAID.TIPOVENDA, 'X') NOT IN ('SR', 'DF')
    AND PCNFSAID.DTCANCEL IS NULL
    AND PCMOV.NUMTRANSITEM = PCMOVCOMPLE.NUMTRANSITEM(+)
    AND NVL(PCMOV.TIPOITEM, 'C') IN ('C', 'N')
    AND PCNFSAID.CODFISCAL <> 0
    AND PCNFSAID.DTSAIDA >= (SELECT MIN(DTSAIDA) FROM PCNFSAID)
    AND PCNFSAID.NUMTRANSVENDA >= (SELECT MIN(NUMTRANSVENDA) FROM PCNFSAID)
    AND PCMOVCOMPLE.NUMTRANSITEM >= (SELECT MIN(NUMTRANSITEM) FROM PCMOVCOMPLE)
    AND PCMOV.NUMTRANSVENDA >= (SELECT MIN(NUMTRANSVENDA) FROM PCMOV)
   AND PCNFSAID.CODFISCAL NOT IN (722, 532, 632, 732)
   AND PCNFSAID.CONDVENDA NOT IN (4,0, 8, 13, 20, 98, 99)
and PCPLPAG.CODPLPAG = PCNFSAID.CODPLPAG

   AND TO_CHAR(PCNFSAID.DTSAIDA, 'YYYY') >= TO_CHAR(ADD_MONTHS(SYSDATE, -36), 'YYYY')