SELECT PRO.CODPROD AS CODIGOPRODUTO,
PRO.DESCRICAO AS PRODUTO,
FORN.CODFORNEC AS CODIGOFORNECEDOR,
FORN.FORNECEDOR AS FORNECEDOR,
FORN.FANTASIA AS FORNECEDORFANTASIA,
CAT.CODCATEGORIA AS CODIGOCATEGORIA,
CAT.CATEGORIA AS CATEGORIA,
PRO.TIPOMEDICAMENTO,
SUBCAT.CODSUBCATEGORIA AS CODIGOSUBCATEGORIA,
SUBCAT.SUBCATEGORIA AS SUBCATEGORIA,
SEC.CODSEC AS CODIGOSECAO,
SEC.DESCRICAO AS SECAO,
DEP.CODEPTO AS CODIGODEPARTAMENTO,
DEP.DESCRICAO AS DEPARTAMENTO,
PRO.EMBALAGEM AS EMBALAGEM,
PRO.EMBALAGEMMASTER AS EMBALAGEMMASTER,
PRO.CODFAB AS CODIGOFABRICA,
PRO.CLASSE,
MAR.MARCA AS MARCA,
PRO.IMPORTADO AS IMPORTADO,
LINPRO.DESCRICAO AS LINHAPRODUTO,
CASE 
WHEN PRO.OBS2  = 'FL' THEN 'Fora de Linha'
ELSE 'Em Linha' 
END AS FORALINHA,
FORN.ESTADO AS UFFORNECEDOR,
FORN.CIDADE AS CIDADEFORNECEDOR,
EMP.MATRICULA AS CODIGOCOMPRADOR,
EMP.NOME AS COMPRADOR,
EMP.EMAIL AS EMAILCOMPRADOR,
FORN.CODFORNECPRINC AS CODIGOFORNECEDORPRINCIAPAL,
--(SELECT PCFORNEC.FORNECEDOR FROM PCFORNEC WHERE FORN.CODFORNECPRINC = PCFORNEC.CODFORNEC ) AS FORNECEDORPRINCIPAL,
DIS.CODDISTRIB AS CODIGODISTRIBUICAO,
DIS.DESCRICAO AS DISTRIBUICAO,
CASE WHEN PRO.DTEXCLUSAO IS NULL THEN 'ATIVO' ELSE 'INATIVO' END AS SITUACAO,
FORN.EMAIL AS EMAILFORNECEDOR
FROM PCPRODUT PRO
LEFT JOIN PCCATEGORIA CAT ON ( (CAT.CODCATEGORIA = PRO.CODCATEGORIA) AND (CAT.CODSEC = PRO.CODSEC) ) 
LEFT JOIN PCSUBCATEGORIA SUBCAT ON ( (SUBCAT.CODSUBCATEGORIA = PRO.CODSUBCATEGORIA) AND (SUBCAT.CODSEC = PRO.CODSEC) ) 
LEFT JOIN PCSECAO SEC ON SEC.CODSEC = PRO.CODSEC
LEFT JOIN PCDEPTO DEP ON DEP.CODEPTO = PRO.CODEPTO
LEFT JOIN PCMARCA MAR ON MAR.CODMARCA = PRO.CODMARCA
LEFT JOIN PCLINHAPROD LINPRO ON LINPRO.CODLINHA = PRO.CODLINHAPROD
LEFT JOIN PCFORNEC FORN ON FORN.CODFORNEC = PRO.CODFORNEC
LEFT JOIN PCDISTRIB DIS ON DIS.CODDISTRIB = FORN.CODDISTRIB
LEFT JOIN PCEMPR EMP ON EMP.MATRICULA = FORN.CODCOMPRADOR